// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: MoleculeViewerPluginInfo.C
// ****************************************************************************

#include <MoleculePluginInfo.h>

VISIT_PLOT_PLUGIN_ENTRY_EV(Molecule,Viewer)


// ****************************************************************************
//  Method: MoleculeViewerPluginInfo::XPMIconData
//
//  Purpose:
//    Return a pointer to the icon data.
//
//  Returns:    A pointer to the icon data.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

#include <Molecule.xpm>
const char **
MoleculeViewerPluginInfo::XPMIconData() const
{
    return Molecule_xpm;
}

