/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include "QvisExtremeValueAnalysisWindow.h"

#include <ExtremeValueAnalysisAttributes.h>
#include <ViewerProxy.h>

#include <QCheckBox>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QSpinBox>
#include <QButtonGroup>
#include <QRadioButton>
#include <QvisColorTableButton.h>
#include <QvisOpacitySlider.h>
#include <QvisColorButton.h>
#include <QvisLineStyleWidget.h>
#include <QvisLineWidthWidget.h>
#include <QvisVariableButton.h>
#include <QComboBox>

#include <stdio.h>
#include <string>

using std::string;

// ****************************************************************************
// Method: QvisExtremeValueAnalysisWindow::QvisExtremeValueAnalysisWindow
//
// Purpose: 
//   Constructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisExtremeValueAnalysisWindow::QvisExtremeValueAnalysisWindow(const int type,
                         ExtremeValueAnalysisAttributes *subj,
                         const QString &caption,
                         const QString &shortName,
                         QvisNotepadArea *notepad)
    : QvisOperatorWindow(type,subj, caption, shortName, notepad)
{
    atts = subj;
}


// ****************************************************************************
// Method: QvisExtremeValueAnalysisWindow::~QvisExtremeValueAnalysisWindow
//
// Purpose: 
//   Destructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisExtremeValueAnalysisWindow::~QvisExtremeValueAnalysisWindow()
{
}


// ****************************************************************************
// Method: QvisExtremeValueAnalysisWindow::CreateWindowContents
//
// Purpose: 
//   Creates the widgets for the window.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisExtremeValueAnalysisWindow::CreateWindowContents()
{
    QGridLayout *mainLayout = new QGridLayout(0);
    topLayout->addLayout(mainLayout);

    computeMaxesLabel = new QLabel(tr("Compute Maxes:"), central);
    mainLayout->addWidget(computeMaxesLabel,0,0);
    computeMaxes = new QWidget(central);
    computeMaxesButtonGroup= new QButtonGroup(computeMaxes);
    QHBoxLayout *computeMaxesLayout = new QHBoxLayout(computeMaxes);
    computeMaxesLayout->setMargin(0);
    computeMaxesLayout->setSpacing(10);
    QRadioButton *computeMaxesComputeMaxesMONTHLY = new QRadioButton(tr("Monthly"), computeMaxes);
    computeMaxesButtonGroup->addButton(computeMaxesComputeMaxesMONTHLY,0);
    computeMaxesLayout->addWidget(computeMaxesComputeMaxesMONTHLY);
    QRadioButton *computeMaxesComputeMaxesYEARLY = new QRadioButton(tr("Annually"), computeMaxes);
    computeMaxesButtonGroup->addButton(computeMaxesComputeMaxesYEARLY,1);
    computeMaxesLayout->addWidget(computeMaxesComputeMaxesYEARLY);
    connect(computeMaxesButtonGroup, SIGNAL(buttonClicked(int)),
            this, SLOT(computeMaxesChanged(int)));
    mainLayout->addWidget(computeMaxes, 0,1);

    DisplayMonthLabel = new QLabel(tr("Display Month"), central);
    mainLayout->addWidget(DisplayMonthLabel,1,0);

    displayMonthType = new QComboBox(central);
    displayMonthType->addItem(tr("January"));
    displayMonthType->addItem(tr("February"));
    displayMonthType->addItem(tr("March"));
    displayMonthType->addItem(tr("April"));
    displayMonthType->addItem(tr("May"));
    displayMonthType->addItem(tr("June"));
    displayMonthType->addItem(tr("July"));
    displayMonthType->addItem(tr("August"));
    displayMonthType->addItem(tr("September"));
    displayMonthType->addItem(tr("October"));
    displayMonthType->addItem(tr("November"));
    displayMonthType->addItem(tr("December"));

    mainLayout->addWidget(displayMonthType, 1,1);
    connect(displayMonthType, SIGNAL(activated(int)),
            this, SLOT(DisplayMonthChanged(int)));
}


// ****************************************************************************
// Method: QvisExtremeValueAnalysisWindow::UpdateWindow
//
// Purpose: 
//   Updates the widgets in the window when the subject changes.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisExtremeValueAnalysisWindow::UpdateWindow(bool doAll)
{

    for(int i = 0; i < atts->NumAttributes(); ++i)
    {
        if(!doAll)
        {
            if(!atts->IsSelected(i))
            {
                continue;
            }
        }

        switch(i)
        {
          case ExtremeValueAnalysisAttributes::ID_computeMaxes:
            if (atts->GetComputeMaxes() == ExtremeValueAnalysisAttributes::MONTHLY)
            {
                displayMonthType->setEnabled(true);
                if(DisplayMonthLabel)
                    DisplayMonthLabel->setEnabled(true);
            }
            else
            {
                displayMonthType->setEnabled(false);
                if(DisplayMonthLabel)
                    DisplayMonthLabel->setEnabled(false);
            }
            computeMaxesButtonGroup->blockSignals(true);
            if(computeMaxesButtonGroup->button((int)atts->GetComputeMaxes()) != 0)
                computeMaxesButtonGroup->button((int)atts->GetComputeMaxes())->setChecked(true);
            computeMaxesButtonGroup->blockSignals(false);
            break;
          case ExtremeValueAnalysisAttributes::ID_DisplayMonth:
            displayMonthType->blockSignals(true);
            displayMonthType->setCurrentIndex((int)atts->GetDisplayMonth());
            displayMonthType->blockSignals(false);
            break;
        }
    }
}


// ****************************************************************************
// Method: QvisExtremeValueAnalysisWindow::GetCurrentValues
//
// Purpose: 
//   Gets values from certain widgets and stores them in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisExtremeValueAnalysisWindow::GetCurrentValues(int which_widget)
{
}


//
// Qt Slot functions
//


void
QvisExtremeValueAnalysisWindow::computeMaxesChanged(int val)
{
    if(val != atts->GetComputeMaxes())
    {
        atts->SetComputeMaxes(ExtremeValueAnalysisAttributes::ComputeMaxes(val));
        Apply();
    }
}


void
QvisExtremeValueAnalysisWindow::DisplayMonthChanged(int val)
{
    if(val != atts->GetDisplayMonth())
    {
        atts->SetDisplayMonth(ExtremeValueAnalysisAttributes::Month(val));
        SetUpdate(false);
        Apply();
    }
}

