#include <FLASHPluginInfo.h>

#if defined(__APPLE__)
#define GetEngineInfo FLASH_GetEngineInfo
#endif

// ****************************************************************************
//  Function:  GetEngineInfo
//
//  Purpose:
//    Return a new EnginePluginInfo for the FLASH database.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Tue Aug 23 13:32:06 PST 2005
//
// ****************************************************************************
extern "C" EngineDatabasePluginInfo* GetEngineInfo()
{
    return new FLASHEnginePluginInfo;
}

// ****************************************************************************
//  Method: FLASHCommonPluginInfo::GetWriter
//
//  Purpose:
//      Sets up a FLASH writer.
//
//  Returns:    A FLASH writer.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Tue Aug 23 13:32:06 PST 2005
//
// ****************************************************************************
avtDatabaseWriter *
FLASHEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

