#SET(VISITHOME /Users/childs/visit)
#SET(VISITARCH i386-apple-darwin10_gcc-4.2)

## Compiler flags.
##
VISIT_OPTION_DEFAULT(VISIT_C_COMPILER /opt/intel/bin/icc TYPE FILEPATH)
VISIT_OPTION_DEFAULT(VISIT_CXX_COMPILER /opt/intel/bin/icpc TYPE FILEPATH)
VISIT_OPTION_DEFAULT(VISIT_C_FLAGS "-mmic -I/export/phi/eewingzlib/include -I /export/phi/mesa/install/include" TYPE STRING)
VISIT_OPTION_DEFAULT(VISIT_CXX_FLAGS "-mmic -I/export/phi/eewingzlib/include -I /export/phi/mesa/install/include" TYPE STRING)
VISIT_OPTION_DEFAULT(ZLIB_LIB "-L/export/phi/eewingzlib/lib -lz" TYPE STRING)
VISIT_OPTION_DEFAULT(CMAKE_BUILD_TYPE Release)
VISIT_OPTION_DEFAULT(VISIT_USE_X OFF TYPE BOOL)



##
## VisIt Thread Option
##
VISIT_OPTION_DEFAULT(VISIT_THREAD ON TYPE BOOL)

VISIT_OPTION_DEFAULT(VISIT_SERVER_COMPONENTS_ONLY ON TYPE BOOL)
VISIT_OPTION_DEFAULT(VISIT_USE_GLEW OFF TYPE BOOL)
VISIT_OPTION_DEFAULT(VISIT_ZLIB ON TYPE BOOL)

VISIT_OPTION_DEFAULT(VISIT_VTK_DIR /export/phi/vtk/install)
VISIT_OPTION_DEFAULT(VISIT_MESA_DIR /export/phi/mesa/install)
VISIT_OPTION_DEFAULT(VISIT_NETCDF_DIR /export/phi/netcdf)





