// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: PoincareGUIPluginInfo.C
// ****************************************************************************

#include <PoincarePluginInfo.h>
#include <PoincareAttributes.h>
#include <QApplication>
#include <QvisPoincareWindow.h>

VISIT_OPERATOR_PLUGIN_ENTRY(Poincare,GUI)

// ****************************************************************************
//  Method: PoincareGUIPluginInfo::GetMenuName
//
//  Purpose:
//    Return a pointer to the name to use in the GUI menu.
//
//  Returns:    A pointer to the name to use in the GUI menu.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

QString *
PoincareGUIPluginInfo::GetMenuName() const
{
    return new QString(qApp->translate("OperatorNames", "Poincare"));
}


// ****************************************************************************
//  Method: PoincareGUIPluginInfo::CreatePluginWindow
//
//  Purpose:
//    Return a pointer to an operator's attribute window.
//
//  Arguments:
//    type      The type of the operator.
//    attr      The attribute subject for the operator.
//    notepad   The notepad to use for posting the window.
//
//  Returns:    A pointer to the operator's attribute window.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

QvisPostableWindowObserver *
PoincareGUIPluginInfo::CreatePluginWindow(int type, AttributeSubject *attr,
    const QString &caption, const QString &shortName, QvisNotepadArea *notepad)
{
    return new QvisPoincareWindow(type, (PoincareAttributes *)attr,
        caption, shortName, notepad);
}

// ****************************************************************************
//  Method: PoincareGUIPluginInfo::XPMIconData
//
//  Purpose:
//    Return a pointer to the icon data.
//
//  Returns:    A pointer to the icon data.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

#include <Poincare.xpm>
const char **
PoincareGUIPluginInfo::XPMIconData() const
{
    return Poincare_xpm;
}

