// ************************************************************************* //
//  File: SiloDumpCommonPluginInfo.C
// ************************************************************************* //

#include <SiloDumpPluginInfo.h>
#include <SiloDumpAttributes.h>

// ****************************************************************************
//  Method: SiloDumpCommonPluginInfo::AllocAttributes
//
//  Purpose:
//    Return a pointer to a newly allocated attribute subject.
//
//  Returns:    A pointer to the newly allocated attribute subject.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Fri Jan 4 14:25:24 PST 2002
//
// ****************************************************************************

AttributeSubject *
SiloDumpCommonPluginInfo::AllocAttributes()
{
    return new SiloDumpAttributes;
}

// ****************************************************************************
//  Method: SiloDumpCommonPluginInfo::CopyAttributes
//
//  Purpose:
//    Copy a SiloDump attribute subject.
//
//  Arguments:
//    to        The destination attribute subject.
//    from      The source attribute subject.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Fri Jan 4 14:25:24 PST 2002
//
// ****************************************************************************

void 
SiloDumpCommonPluginInfo::CopyAttributes(AttributeSubject *to,
    AttributeSubject *from)
{
    *((SiloDumpAttributes *) to) = *((SiloDumpAttributes *) from);
}
