// ************************************************************************* //
//  File: LineoutPluginInfo.C
// ************************************************************************* //

#include <LineoutPluginInfo.h>
#include <LineoutAttributes.h>

#include <visit-config.h>
#if defined(__APPLE__)
extern "C" const char *LineoutVisItPluginVersion = VERSION;
#else
extern "C" const char *VisItPluginVersion = VERSION;
#endif

#if defined(__APPLE__)
#define GetGeneralInfo Lineout_GetGeneralInfo
#endif

// ****************************************************************************
//  Function:  GetGeneralInfo
//
//  Purpose:
//    Return a new GeneralPluginInfo for the Lineout operator.
//
//  Programmer:  whitlocb -- generated by xml2info
//  Creation:    Fri Jan 6 18:13:15 PST 2006
//
// ****************************************************************************
extern "C" GeneralOperatorPluginInfo* GetGeneralInfo()
{
    return new LineoutGeneralPluginInfo;
}

// ****************************************************************************
//  Method: LineoutGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the operator plugin.
//
//  Returns:    A pointer to the name of the operator plugin.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:15 PST 2006
//
// ****************************************************************************

char *
LineoutGeneralPluginInfo::GetName() const
{
    return "Lineout";
}

// ****************************************************************************
//  Method: LineoutGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the operator plugin.
//
//  Returns:    A pointer to the version of the operator plugin.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:15 PST 2006
//
// ****************************************************************************

char *
LineoutGeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: LineoutGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the operator plugin.
//
//  Returns:    A pointer to the id of the operator plugin.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:15 PST 2006
//
// ****************************************************************************

char *
LineoutGeneralPluginInfo::GetID() const
{
    return "Lineout_1.0";
}
// ****************************************************************************
//  Method: LineoutGeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:15 PST 2006
//
// ****************************************************************************

bool
LineoutGeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
