// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ************************************************************************* //
//  File: LineoutEnginePluginInfo.C
// ************************************************************************* //

#include <LineoutPluginInfo.h>
#include <avtLineoutFilter.h>

VISIT_OPERATOR_PLUGIN_ENTRY_EV(Lineout,Engine)

// ****************************************************************************
//  Method: LineoutEnginePluginInfo::AllocAvtPluginFilter
//
//  Purpose:
//    Return a pointer to a newly allocated avtPluginFilter.
//
//  Returns:    A pointer to the newly allocated avtPluginFilter.
//
//  Programmer: kbonnell -- generated by xml2info
//  Creation:   Tue May 7 13:13:46 PST 2002
//
//  Modifications:
//
//    Hank Childs, Thu Jan 24 09:26:14 PST 2008
//    Forced to hand-edit return of avtLineoutPluginFilter ... not
//    avtLineoutFilter.
//
// ****************************************************************************
#include <avtLineoutPluginFilter.h>
avtPluginFilter *
LineoutEnginePluginInfo::AllocAvtPluginFilter()
{
    return new avtLineoutPluginFilter;
}

