INCLUDE(${TEEM_SOURCE_DIR}/CTestConfig.cmake)
SET(NIGHTLY_START_TIME "${CTEST_NIGHTLY_START_TIME}")
SET(DROP_METHOD "${CTEST_DROP_METHOD}")
SET(DROP_SITE "${CTEST_DROP_SITE}")
SET(DROP_LOCATION "${CTEST_DROP_LOCATION}")
SET(TRIGGER_SITE "${CTEST_TRIGGER_SITE}")

