sudo: required
services: docker
dist: trusty
env:
  global:
    - TRAVIS_HOME=`pwd`
  matrix:
    - BUILD_SHARED_LIBS=ON
script:
- docker run -v ${TRAVIS_BUILD_DIR}:/visit-clone visitdav/visit-ci-develop:current /visit-clone/scripts/ci/travis/travis-test-visit-ci-develop.sh 
notifications:
  email:
    recipients:
      - cyrush@llnl.gov
    on_success: always
    on_failure: always
