FROM rockylinux:8.9

ENV TZ=America/Phoenix

# the default repos for rockylinux use mirrors.
# if there is difficulty running yum due to the mirrors, then
# hand-modify /etc/yum.repos.d/* to comment out the mirrors and uncomment
# the baseurl.
# then the packages below will have to be installed by hand.

RUN yum update -y && yum install -y yum-utils

# enable the 'devel' repo, it has some packages we need but is not
# enabled by default
RUN yum-config-manager --enable devel

# fetch build env
RUN yum install -y \
    libX11 \
    libX11-devel \
    libX11-xcb \
    libXext \
    libXext-devel \
    fontconfig \
    fontconfig-devel \
    xorg-x11-utils \
    xorg-x11-xkb-utils \
    libXt-devel \
    libXrender-devel \
    libXfixes \
    libXfixes-devel \
    libXcursor \
    libXcursor-devel


## Install other visit dependencies
RUN yum install -y \
    patch \
    libtool \
    autoconf \
    automake \
    git \
    wget \
    curl \
    unzip \
    zlib-devel \
    python3 \
    libSM-devel \
    openssl-devel \
    freetype-devel \
    libxml2 \
    libxml2-devel \
    vim \
    libffi-devel \
    bison \
    flex

RUN cd /usr/include && ln -s freetype2 freetype

RUN yum -y install  gcc-toolset-10


WORKDIR /home/visit

SHELL ["/bin/bash", "-lc"]

# Create the third-party directory
# Copy build_visit and the scripts to run it
COPY build_visit3_5_0 /home/visit
COPY run_build_visit.sh /home/visit
COPY build_visit_docker_cleanup.py /home/visit
# build thirdparty libraries
RUN source /opt/rh/gcc-toolset-10/enable &&  ./run_build_visit.sh
RUN python3 build_visit_docker_cleanup.py

# build and test visit
COPY build_test_visit.sh /home/visit
COPY test_visit.py /home/visit
COPY visit3.5.0.tar.gz /home/visit
# Build visit, package, install and test.
RUN source /opt/rh/gcc-toolset-10/enable && ./build_test_visit.sh -v 3.5.0

