FROM rockylinux:9.3

ENV TZ=America/Phoenix

RUN yum update -y && yum install -y yum-utils

# enable the 'devel' repo, it has some packages we need but is not
# enabled by default
RUN yum-config-manager --enable devel

# fetch build env
RUN yum install -y \
    libxcb \
    libxcb-devel \
    xcb-util \
    xcb-util-devel \
    xcb-util-image \
    xcb-util-image-devel \
    xcb-util-keysyms \
    xcb-util-keysyms-devel \
    xcb-util-renderutil \
    xcb-util-renderutil-devel \
    xcb-util-wm \
    xcb-util-wm-devel \
    xcb-proto \
    libxkbcommon \
    libxkbcommon-devel \
    libxkbcommon-x11 \
    libxkbcommon-x11-devel \
    expat \
    expat-devel \
    libX11 \
    libX11-common \
    libX11-devel \
    libX11-xcb \
    libXext \
    libXext-devel \
    fontconfig \
    fontconfig-devel \
    xorg-x11-utils \
    libXt-devel \
    libXrender-devel \
    libXfixes \
    libXfixes-devel \
    libXcursor \
    libXcursor-devel


## Install other visit dependencies
RUN yum install -y \
    patch \
    perl \
    libtool \
    autoconf \
    automake \
    git \
    wget \
    unzip \
    zlib-devel \
    python3 \
    libSM-devel \
    openssl-devel \
    freetype-devel \
    libxml2 \
    libxml2-devel \
    vim \
    libffi-devel  \
    gcc \
    g++ \
    xz \
    cpio \
    bison \
    flex

RUN yum install -y --allowerasing curl

RUN cd /usr/include && ln -s freetype2 freetype


WORKDIR /home/visit
SHELL ["/bin/bash", "-lc"]


# Copy build_visit and the script to run it
COPY build_visit3_5_0 /home/visit
COPY run_build_visit.sh /home/visit
COPY build_visit_docker_cleanup.py /home/visit
# build thirdparty libraries
RUN /bin/bash run_build_visit.sh
RUN python3 build_visit_docker_cleanup.py

# build and test visit
COPY build_test_visit.sh /home/visit
COPY test_visit.py /home/visit
COPY visit3.5.0.tar.gz /home/visit
# Build visit, package, install and test.
RUN /bin/bash build_test_visit.sh -v 3.5.0

