FROM centos:centos8
MAINTAINER Eric Brugger <brugger1@llnl.gov>

# fetch build env
RUN dnf -y upgrade \
 && dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
 && dnf -y install \
    git \
    wget \
    bzip2 \
    p7zip \
    unzip \
    xz \
    patch \
    hostname \
    subversion \
    make \
    gcc \
    gcc-c++ \
    gcc-gfortran \
    zlib-devel \
    python2 \
    libICE-devel \
    libSM-devel \
    libxcb-devel \
    libXext-devel \
    libXt-devel \
    freetype-devel \
    fontconfig \
    fontconfig-devel \
    autoconf \
    libtool \
    libxml2 \
    libxml2-devel \
    vim \
    emacs \
    bison \
    flex \
    cpio \
 && dnf -y --enablerepo=PowerTools install bison-devel flex-devel \
 && rm -rf /var/lib/apt/lists/*

RUN dnf -y upgrade && dnf -y install libffi-devel && rm -rf /var/lib/apt/lists/*

RUN cd /usr/include && ln -s freetype2 freetype
RUN cd /usr/bin && ln -s bison yacc
RUN cd /usr/bin && ln -s python2 python

RUN groupadd -r visit && useradd -ms /bin/bash --no-log-init -r -g visit visit
USER visit
WORKDIR /home/visit

# Create the third-party directory
RUN mkdir third_party
# Copy build_visit and the script to run it
COPY build_visit3_1_0 /home/visit
COPY run_build_visit_centos8.sh /home/visit
COPY build_visit_docker_cleanup.py /home/visit
COPY build_test_visit.sh /home/visit
COPY test_visit.py /home/visit
# Build the third party libraries
RUN /bin/bash run_build_visit_centos8.sh
