// ************************************************************************* //
//                        PseudocolorScriptingPluginInfo.C
// ************************************************************************* //
#include <PseudocolorPluginInfo.h>
#include <PyPseudocolorAttributes.h>

#if defined(__APPLE__)
#define GetScriptingInfo Pseudocolor_GetScriptingInfo
#endif

// ****************************************************************************
//  Function:  GetScriptingInfo
//
//  Purpose:
//    Return a new ScriptingPluginInfo for the Pseudocolor plot.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:16 PDT 2006
//
// ****************************************************************************
extern "C" ScriptingPlotPluginInfo* GetScriptingInfo()
{
    return new PseudocolorScriptingPluginInfo;
}

// ****************************************************************************
// Method: PseudocolorScriptingPluginInfo::InitializePlugin
//
// Purpose: 
//   Calls the initialization function for the plugin.
//
// Arguments:
//   subj    : A pointer to the plugin's state object.
//   data    : A pointer to data to be used by the observer function.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:16 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

void
PseudocolorScriptingPluginInfo::InitializePlugin(AttributeSubject *subj,
    void *data)
{
    PyPseudocolorAttributes_StartUp((PseudocolorAttributes *)subj, data);
}

// ****************************************************************************
// Method: PseudocolorScriptingPluginInfo::GetMethodTable
//
// Purpose: 
//   Returns a pointer to the plugin's Python method table. These methods are
//   added to the top-level visit module's methods.
//
// Arguments:
//   nMethods : Returns the number of methods in the method table.
//
// Returns:    A pointer to the method table.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:16 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

void *
PseudocolorScriptingPluginInfo::GetMethodTable(int *nMethods)
{
    return PyPseudocolorAttributes_GetMethodTable(nMethods);
}

// ****************************************************************************
// Method: PseudocolorScriptingPluginInfo::TypesMatch
//
// Purpose: 
//   Returns whether or not the input PyObject is Pseudocolor plot attributes.
//
// Arguments:
//   pyobject : A PyObject cast to void*.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:16 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

bool
PseudocolorScriptingPluginInfo::TypesMatch(void *pyobject)
{
    return PyPseudocolorAttributes_Check((PyObject *)pyobject);
}

// ****************************************************************************
// Method: PseudocolorScriptingPluginInfo::GetLogString
//
// Purpose: 
//   Gets a string representation of the current attributes.
//
// Arguments:
//   val : Whether or not to log state information.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:16 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

char *
PseudocolorScriptingPluginInfo::GetLogString()
{
    std::string s(PyPseudocolorAttributes_GetLogString());
    char *v = new char[s.size() + 1];
    strcpy(v, s.c_str());
    return v;
}

// ****************************************************************************
// Method: PseudocolorScriptingPluginInfo::SetDefaults
//
// Purpose: 
//   Used to set the default values for a plugin's state object.
//
// Arguments:
//   atts : The new state.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:16 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

void
PseudocolorScriptingPluginInfo::SetDefaults(const AttributeSubject *atts)
{
    PyPseudocolorAttributes_SetDefaults((const PseudocolorAttributes *)atts);
}
