// ************************************************************************* //
//  File: SmoothEnginePluginInfo.C
// ************************************************************************* //

#include <SmoothPluginInfo.h>
#include <avtSmoothFilter.h>

#if defined(__APPLE__)
#define GetEngineInfo Smooth_GetEngineInfo
#endif

// ****************************************************************************
//  Function:  GetEngineInfo
//
//  Purpose:
//    Return a new EnginePluginInfo for the Smooth operator.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Sun Aug 14 11:59:57 PDT 2005
//
// ****************************************************************************
extern "C" EngineOperatorPluginInfo* GetEngineInfo()
{
    return new SmoothEnginePluginInfo;
}

// ****************************************************************************
//  Method: SmoothEnginePluginInfo::AllocAvtPluginFilter
//
//  Purpose:
//    Return a pointer to a newly allocated avtPluginFilter.
//
//  Returns:    A pointer to the newly allocated avtPluginFilter.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Sun Aug 14 11:59:57 PDT 2005
//
// ****************************************************************************

avtPluginFilter *
SmoothEnginePluginInfo::AllocAvtPluginFilter()
{
    return new avtSmoothFilter;
}
