#!/bin/sh
# This follows the same idea as the `pre-commit' script, but is meant to be run
# after the commit is accepted/completed/finalized.  This would be a good place
# to inform a buildbot to start an automated build, for example.

REPOS="$1"
REV="$2"

function run_sh()
{
   SCRIPT="$@"
   bash ${REPOS}/hooks/${SCRIPT} ${REPOS} ${REV}
   if [ $? != 0 ]; then
      exit 1
   fi
}

# background it -- this might take some time, and shouldnt slow down the
# users commit.
bash ${REPOS}/hooks/ciabot_svn.sh "${REPOS}" "${REV}" &

# Uncomment if you want to grab the committing user's email.
#email=`sh ${REPOS}/hooks/output_email.sh ${REPOS} ${REV}`

runtest_sh "state_update.sh"
