#!/bin/sh
#
# VisIt pre-commit hook script.
#
# Subversion requires a specific name for hook scripts.  To avoid getting us in
# a situation where we want to add a pre-commit script, but we've already
# implemented one, this script is a `meta-script' which simply runs others.  To
# add a new hook script, you should add a `runhook' line before the `exit 0' at
# the bottom of this file.  The argument to runhook is a script which must
# reside in the `hooks' directory of our repository.
# All pre-commit scripts take REPOSITORY_PATH and TRANSACTION_ID as arguments,
# in that order.  See the subversion redbook for more information.
# Mark Miller test
# Mark Miller test

REPOS="$1"
TXN="$2"

#
# Set some env variables used by the scripts
#
source ${REPOS}/hooks/hook_vars.sh

function runhook_sh()
{
   TEST="$@"
   sh ${REPOS}/hooks/${TEST} ${REPOS} ${TXN}
   if [ $? != 0 ]; then
      exit 1
   fi
}
function runhook_py()
{
   TEST="$@"
   /usr/bin/python ${REPOS}/hooks/${TEST} ${REPOS} ${TXN}
   if [ $? != 0 ]; then
      exit 1
   fi
}

# Unfortunately we want something more warning-esque, which isn't quite
# possible with subversion's hooks.
#runhook_sh "verify_versioning.sh"

# Cyrus says the TRY/ENDTRY test is rejecting too much valid code right now.
# Until we have time to make it a bit smarter, we're disabling that test.
#runhook_py "exceptions.py"

# Check that we're using correct versin of autoconf
runhook_sh "check_autoconf_version.sh"

# All checks passed, so allow the commit.
exit 0
