#!/bin/sh

# Change directories to the working directory.
cd visit_run_tests

# Get the latest version of the scripts
rm -rf svn_bin
svn co svn+ssh://brugger@svn.nersc.gov/svn/visit/trunk/src/svn_bin
cd svn_bin

# Run the test suite.
./regressiontest_alastor
