#!/bin/sh
# Do a little magic to run perl from anywhere in your path.

lines=`cat $0 | wc -l`
lines=`expr $lines - 16`
if [ "$checksys" != "SunOS" ]
then
  tail -n $lines $0 > /tmp/visitperl$$
else
  tail -$lines $0 > /tmp/visitperl$$
fi
echo "__END__" >> /tmp/visitperl$$
echo "$0 $*" >> /tmp/visitperl$$
exec perl /tmp/visitperl$$ $0 ${1+"$@"}

unlink($0);
$0 = shift @ARGV;

# ----------------------------------------------------------------------------

if  (! -d "src")
{
   die "invoke $0 from the root of the VisIt source tree\n";
}

sub get ($@)
{
    my ($dir, $recursearg) = @_;
    @tmpfiles = `svn ls $recursearg $dir | egrep -v /\$`;
    my @files = ();
    foreach (@tmpfiles)
    {
        chomp;
        push @files, "$dir/$_";
    }
    return @files
}

sub get_svn_recursive ($@)
{
    my ($dir) = @_;
    return get($dir, "-R");
}

sub get_svn_norecursive ($@)
{
    my ($dir) = @_;
    return get($dir, "");
}

sub get_norecursive ($@)
{
    my ($files) = @_;
    @tmpfiles = `ls $files | egrep -v /\$`;
    my @files = ();
    foreach (@tmpfiles)
    {
        chomp;
        push @files, "$_";
    }
    return @files
}


@files = ();

push @files, get_svn_norecursive  "./src";
push @files, get_svn_recursive    "./src/common";
push @files, get_svn_recursive    "./src/visit_vtk";
push @files, get_svn_recursive    "./src/engine";
push @files, get_svn_recursive    "./src/launcher";
push @files, get_svn_recursive    "./src/components";
push @files, get_svn_recursive    "./src/vtkqt";
push @files, get_svn_recursive    "./src/plots";
push @files, get_svn_recursive    "./src/operators";
push @files, get_svn_recursive    "./src/databases";
push @files, get_svn_recursive    "./src/winutil";
push @files, get_svn_recursive    "./src/viewer";
push @files, get_svn_recursive    "./src/gui";
push @files, get_svn_recursive    "./src/mdserver";
push @files, get_svn_recursive    "./src/visitpy";
push @files, get_svn_recursive    "./src/java";
push @files, get_svn_recursive    "./src/tools";
push @files, get_svn_recursive    "./src/sim";
push @files, get_svn_recursive    "./src/include";
push @files, get_svn_recursive    "./src/bin";
push @files, get_svn_recursive    "./src/exe";
push @files, get_svn_norecursive  "./src/lib";
push @files, get_svn_norecursive  "./src/help";
push @files, get_svn_recursive    "./src/archives";
push @files, get_svn_recursive    "./src/plugins";
push @files, get_svn_recursive    "./src/clearcase_bin";
push @files, get_svn_recursive    "./src/svn_bin";
push @files, get_svn_recursive    "./src/config-site";
push @files, get_svn_recursive    "./src/cqscore";
push @files, get_svn_recursive    "./src/third_party_builtin";
push @files, get_norecursive      "./src/help/visit.helpml";
push @files, get_norecursive      "./src/help/help*.html";
push @files, get_norecursive      "./src/help/list*.html";
push @files, get_norecursive      "./data/Makefile.in";
push @files, get_norecursive      "./data/*.C";

foreach (sort @files)
{
    print "$_\n";
}

