#!/bin/sh
#-----------------------------------------------------------------------
#
# VISIT-INSTALL-CLOSED - Install the visit distributions on the closed
#                        network.
#
# Author: Eric Brugger
# Date:   February 12, 2001
#
# Usage:
#    visit-install-closed [-beta | -private | -public] -v <version>
#
# Modifications:
#   Brad Whitlock, Tue Mar 7 14:10:26 PST 2006
#   I added -b bdivp to the visit-install invokations.
#
#   Eric Brugger, Mon Apr  7 13:52:50 PDT 2008
#   Removed sc install.
#
#   Hank Childs, Sat May  2 13:26:51 CDT 2009
#   Renamed config file to llnl_closed.
#
#   Eric Brugger, Fri Nov  5 15:40:02 PDT 2010
#   Replaced hopi with inca and removed pruple.
#
#   Eric Brugger, Wed Jan  5 09:40:00 PST 2011
#   Added terminator.
#
#   Eric Brugger, Fri Mar 25 10:20:49 PDT 2011
#   Added cielo.
#
#   Eric Brugger, Mon Jul 30 10:31:10 PDT 2012
#   Added gremlin.
#
#   Eric Brugger, Wed Mar 20 11:49:58 PDT 2013
#   Deleted gremlin. Deleted terminator. Replaced termite with hitit.
#
#   Eric Brugger, Thu Jun 20 10:37:05 PDT 2013
#   I modified the hitit install since it is now an x86_64 system instead
#   of an i686 system.
#
#   Eric Brugger, Tue Jul  9 11:23:43 PDT 2013
#   I changed the gateway node to login to cielo.
#
#-----------------------------------------------------------------------

test=no

user=`whoami`

#
# Parse the execute line, providing default values for error checking.
#
hitit=true
inca=true
cielo=true

ver=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
         hitit=false
         inca=false
         cielo=false
         shift
         ;;
      -hitit)
         hitit=false
         shift
         ;;
      +hitit)
         hitit=true
         shift
         ;;
      -inca)
         inca=false
         shift
         ;;
      +inca)
         inca=true
         shift
         ;;
      -cielo)
         cielo=false
         shift
         ;;
      +cielo)
         cielo=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
   esac
done

#
# Check that the version was provided.
#
if [ $ver = undefined ]
then
   echo "Usage: [-none] [-<machine name>] -v <version>"
   exit
fi

#
# Check that the visit install script is present.
#
if [ ! -e visit-install ]
then
   echo "visit-install is missing."
   exit
fi

ver2=`echo $ver | tr "." "_"`
ver=`echo $ver2 | tr "_" "."`

#
# Install on hitit.
#
rm -f hitit
cat <<EOF > hitit
#!/bin/sh
./visit-install -private -c llnl_closed -g visit -b bdivp -gw -l $ver linux-x86_64-hitit /misc/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                          > resultlog 2>&1
echo "        install of visit on hitit"         >> resultlog 2>&1
echo "       ---------------------------"        >> resultlog 2>&1
echo ""                                          >> resultlog 2>&1
df -k /misc/gapps/visit                          >> resultlog 2>&1
echo ""                                          >> resultlog 2>&1
ls -l /misc/gapps/visit/$ver+/linux-x86_64/bin   >> resultlog 2>&1
echo ""                                          >> resultlog 2>&1
echo "number of database plugins = "\`ls /misc/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /misc/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /misc/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                          >> resultlog 2>&1
echo "The database plugins:"                     >> resultlog 2>&1
ls /misc/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/misc\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.hitit
EOF

if [ $hitit = true ]
then
   if [ $test = no ]
   then
      scp -P 22 hitit:hitit/visitbuild/visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-x86_64-hitit.tar.gz
      scp -P 22 visit$ver2.linux-x86_64-hitit.tar.gz hitit:
      scp -P 22 visit-install hitit:
      scp -P 22 hitit hitit:hitit_install
      ssh -p 22 hitit "chmod 750 hitit_install;./hitit_install"
   fi
fi

#
# Install on inca.
#
rm -f inca
cat <<EOF > inca
#!/bin/sh
./visit-install -private -c llnl_closed -g visit -b bdivp -gw -l $ver linux-x86_64-inca /usr/gapps/visit > installlog 2>&1
cp /usr/gapps/visit/nvidia304-libs/*.304.54 /usr/gapps/visit/$ver+/linux-x86_64/lib
ln -s libGL.so.304.54 /usr/gapps/visit/$ver+/linux-x86_64/lib/libGL.so
ln -s libGL.so.304.54 /usr/gapps/visit/$ver+/linux-x86_64/lib/libGL.so.1
chmod 775 /usr/gapps/visit/$ver+/linux-x86_64/lib/*.304.54
chgrp visit /usr/gapps/visit/$ver+/linux-x86_64/lib/*.304.54
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on inca"            >> resultlog 2>&1
echo "       --------------------------"           >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin      >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.inca
EOF

if [ $inca = true ]
then
   if [ $test = no ]
   then
      scp inca3:/usr/tmp/$user/inca/visitbuild/visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-x86_64-inca.tar.gz
      scp visit$ver2.linux-x86_64-inca.tar.gz inca3:
      scp visit-install inca3:
      scp inca inca3:inca_install
      ssh inca3 "chmod 750 inca_install;./inca_install"
   fi
fi

#
# Install on cielo.
#
rm -f cielo
cat <<EOF > cielo
#!/bin/sh
./visit-install -private -c llnl_closed -l $ver linux-x86_64-cielo /usr/projects/views/visit > installlog 2>&1
rm -f resultlog
echo ""                                                > resultlog 2>&1
echo "        install of visit on cielo"               >> resultlog 2>&1
echo "       ---------------------------"              >> resultlog 2>&1
echo ""                                                >> resultlog 2>&1
df -k /usr/projects/views/visit                        >> resultlog 2>&1
echo ""                                                >> resultlog 2>&1
ls -l /usr/projects/views/visit/$ver+/linux-x86_64/bin >> resultlog 2>&1
echo ""                                                >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/projects/views/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/projects/views/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/projects/views/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/projects/views/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/projects\/views\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.cielo
EOF

if [ $cielo = true ]
then
   if [ $test = no ]
   then
      ssh rfta15.lanl.gov "ssh ci-fe2 'cp /tmp/$user/cielo/visitbuild/visit$ver2.linux-x86_64.tar.gz .'"
      scp rfta15.lanl.gov:visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-x86_64-cielo.tar.gz
      scp visit$ver2.linux-x86_64-cielo.tar.gz rfta15.lanl.gov:
      scp visit-install rfta15.lanl.gov:
      scp cielo rfta15.lanl.gov:cielo_install
      ssh rfta15.lanl.gov "ssh ci-fe2 'chmod 750 cielo_install;./cielo_install'"
   fi
fi

#
# Clean up.
#
if [ $test = no ]
then
   rm -f hitit inca cielo
fi
