#!/bin/sh
#-----------------------------------------------------------------------
#
# VISIT-INSTALL-OPEN - Install the visit distributions on the open
#                      network.
#
# Author: Eric Brugger
# Date:   October 27, 2000
#
# Usage:
#    visit-install-open [-beta | -private | -public] -v <version>
#
# Modifications:
#   Brad Whitlock, Tue Mar 7 14:08:59 PST 2006
#   Added -b bank to the visit-install invokations.
#
#   Hank Childs, Wed Oct 17 16:25:14 PDT 2007
#   Add a subject line to the status e-mail.
#
#   Hank Childs, Sat May  2 13:26:51 CDT 2009
#   Change config file to "llnl_open".
#
#   Eric Brugger, Fri Nov  5 15:22:54 PDT 2010
#   I replaced yana with aztec.
#
#   Eric Brugger, Mon May 16 14:53:23 PDT 2011
#   I added glory and redsky.
#
#   Eric Brugger, Fri Aug  5 09:53:51 PDT 2011
#   I added kickit.
#
#   Eric Brugger, Tue Sep  6 14:13:59 PDT 2011
#   I added rzzeus.
#
#   Brad Whitlock, Wed Oct 12 10:01:07 PDT 2011
#   Install as llnl_open_cz or llnl_open_rz depending on machine.
#
#-----------------------------------------------------------------------

test=no

user=`whoami`

#
# Set the user e-mail address.
#
emailName=brugger1@llnl.gov
case $user in
   kbonnell)
      emailName=bonnell2@llnl.gov
      ;;
   brugger)
      emailName=brugger1@llnl.gov
      ;;
   childs)
      emailName=childs3@llnl.gov
      ;;
   mcmiller)
      emailName=miller86@llnl.gov
      ;;
   miller)
      emailName=miller86@llnl.gov
      ;;
   whitlocb)
      emailName=whitlock2@llnl.gov
      ;;
esac

#
# Parse the execute line, providing default values for error checking.
#
hoth=true
kickit=true
aztec=true
rzzeus=true
xchem=false
euclid=true
ellipse=true
glory=true
redsky=true

ver=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
         hoth=false
         kickit=false
         aztec=false
         rzzeus=false
         xchem=false
         euclid=false
         ellipse=false
         glory=false
         redsky=false
         shift
         ;;
      -hoth)
         hoth=false
         shift
         ;;
      +hoth)
         hoth=true
         shift
         ;;
      -kickit)
         kickit=false
         shift
         ;;
      +kickit)
         kickit=true
         shift
         ;;
      -aztec)
         aztec=false
         shift
         ;;
      +aztec)
         aztec=true
         shift
         ;;
      -rzzeus)
         rzzeus=false
         shift
         ;;
      +rzzeus)
         rzzeus=true
         shift
         ;;
      -xchem)
         xchem=false
         shift
         ;;
      +xchem)
         xchem=true
         shift
         ;;
      -euclid)
         euclid=false
         shift
         ;;
      +euclid)
         euclid=true
         shift
         ;;
      -ellipse)
         ellipse=false
         shift
         ;;
      +ellipse)
         ellipse=true
         shift
         ;;
      -glory)
         glory=false
         shift
         ;;
      +glory)
         glory=true
         shift
         ;;
      -redsky)
         redsky=false
         shift
         ;;
      +redsky)
         redsky=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
   esac
done

#
# Check that the version was provided.
#
if [ $ver = undefined ]
then
   echo "Usage: [-none] [-<machine name>] -v <version>"
   exit
fi

#
# Check that the visit install script is present.
#
if [ ! -e visit-install ]
then
   echo "visit-install is missing."
   exit
fi

ver2=`echo $ver | tr "." "_"`
ver=`echo $ver2 | tr "_" "."`

#
# Install on hoth.
#
rm -f hoth
cat <<EOF > hoth
#!/bin/sh
./visit-install -private -c llnl_open -g visit -b bdivp -gw -l $ver linux-rhel3 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on hoth"            > resultlog 2>&1
echo "       --------------------------"           >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-intel/bin       >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): hoth" $emailName < resultlog
EOF

if [ $hoth = true ]
then
   if [ $test = no ]
   then
      scp hoth:/scratch/$user/hoth/visitbuild/visit$ver2.linux-intel.tar.gz visit$ver2.linux-rhel3.tar.gz
      scp visit$ver2.linux-rhel3.tar.gz hoth:visit$ver2.linux-rhel3.tar.gz
      scp visit-install hoth:
      scp hoth hoth:hoth_install
      ssh hoth "chmod 750 hoth_install;./hoth_install"
   fi
fi

#
# Install on kickit.
#
rm -f kickit
cat <<EOF > kickit
#!/bin/sh
./visit-install -private -c llnl_open -g visit -b bdivp -gw -l $ver linux-rhel5 /scratch/$user/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on kickit"          > resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /scratch/$user/visit                         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /scratch/$user/visit/$ver+/linux-intel/bin   >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /scratch/$user/visit/$ver+/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /scratch/$user/visit/$ver+/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /scratch/$user/visit/$ver+/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /scratch/$user/visit/$ver+/linux-intel/plugins/databases/libI* | sed "s/\/scratch\/$user\/visit\/$ver+\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
EOF

if [ $kickit = true ]
then
   if [ $test = no ]
   then
      scp kickit:/scratch/$user/kickit/visitbuild/visit$ver2.linux-intel.tar.gz visit$ver2.linux-rhel5.tar.gz
      scp visit$ver2.linux-rhel5.tar.gz kickit:visit$ver2.linux-rhel5.tar.gz
      scp visit-install kickit:
      scp kickit kickit:kickit_install
      ssh kickit "chmod 750 kickit_install;./kickit_install"
   fi
fi

#
# Install on aztec.
#
rm -f aztec
cat <<EOF > aztec
#!/bin/sh
./visit-install -private -c llnl_open_cz -g visit -b bdivp -gw -l $ver linux-x86_64 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on aztec"           > resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin      >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): aztec" $emailName < resultlog
EOF

if [ $aztec = true ]
then
   if [ $test = no ]
   then
      scp aztec3:/usr/tmp/$user/aztec/visitbuild/visit$ver2.linux-x86_64.tar.gz .
      scp visit$ver2.linux-x86_64.tar.gz aztec:visit$ver2.linux-x86_64.tar.gz
      scp visit-install aztec:
      scp aztec aztec:aztec_install
      ssh aztec "chmod 750 aztec_install;./aztec_install"
   fi
fi

#
# Install on rzzeus.
#
rm -f rzzeus
cat <<EOF > rzzeus
#!/bin/sh
./visit-install -private -c llnl_open_rz -g visit -b bdivp -gw -l $ver linux-x86_64 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on rzzeus"          > resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin      >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): rzzeus" $emailName < resultlog
EOF

if [ $rzzeus = true ]
then
   if [ $test = no ]
   then
      cp /usr/tmp/$user/rzzeus/visitbuild/visit$ver2.linux-x86_64.tar.gz .
      cp rzzeus rzzeus_install
      chmod 750 rzzeus_install;./rzzeus_install
   fi
fi

#
# Install on xchem.
#
rm -f xchem
cat <<EOF > xchem
#!/bin/sh
./visit-install -private -c llnl_open -b bdivp -gw -l $ver linux-x86_64-fedora4 /opt/llnl/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on xchem"           > resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /opt/llnl/visit                              >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /opt/llnl/visit/$ver+/linux-x86_64/bin       >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /opt/llnl/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /opt/llnl/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /opt/llnl/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /opt/llnl/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/opt\/llnl\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): xchem" $emailName < resultlog
EOF

if [ $xchem = true ]
then
   if [ $test = no ]
   then
      scp xchem:tmp/$user/xchem/visitbuild/visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-x86_64-fedora4.tar.gz
      scp visit$ver2.linux-x86_64-fedora4.tar.gz xchem:
      scp visit-install xchem:
      scp xchem xchem:xchem_install
      ssh xchem "chmod 750 xchem_install;./xchem_install"
   fi
fi

#
# Install on euclid.
#
rm -f euclid
cat <<EOF > euclid
#!/bin/sh
./visit-install -private -c nersc -b bdivp $ver linux-euclid visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on euclid"          > resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k visit                                        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l visit/$ver+/linux-x86_64/bin                 >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): euclid " $emailName < resultlog
EOF

if [ $euclid = true ]
then
   if [ $test = no ]
   then
      scp euclid.nersc.gov:/usr/tmp/$user/euclid/visitbuild/visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-euclid.tar.gz
      scp visit$ver2.linux-euclid.tar.gz euclid.nersc.gov:
      scp visit-install euclid.nersc.gov:
      scp euclid euclid.nersc.gov:euclid_install
      ssh euclid.nersc.gov "chmod 750 euclid_install;./euclid_install"
   fi
fi

#
# Install on ellipse.
#
rm -f ellipse
cat <<EOF > ellipse
#!/bin/sh
./visit-install -private -c llnl_open_cz -b bdivp $ver linux-rhel4 visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on ellipse"         > resultlog 2>&1
echo "       -----------------------------"        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k visit                                        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l visit/$ver+/linux-intel/bin                  >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls visit/$ver+/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls visit/$ver+/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls visit/$ver+/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls visit/$ver+/linux-intel/plugins/databases/libI* | sed "s/visit\/$ver+\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): ellipse" $emailName < resultlog
EOF

if [ $ellipse = true ]
then
   if [ $test = no ]
   then
      scp ellipse.uchicago.edu:tmp/$user/ellipse/visitbuild/visit$ver2.linux-intel.tar.gz visit$ver2.linux-rhel4.tar.gz
      scp visit$ver2.linux-rhel4.tar.gz ellipse.uchicago.edu:
      scp visit-install ellipse.uchicago.edu:
      scp ellipse ellipse.uchicago.edu:ellipse_install
      ssh ellipse.uchicago.edu "chmod 750 ellipse_install;./ellipse_install"
   fi
fi

#
# Install on glory.
#
rm -f glory
cat <<EOF > glory
#!/bin/sh
./visit-install -private -c sandia $ver linux-glory /projects/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on glory"           > resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /projects/visit                              >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /projects/visit/$ver+/linux-x86_64/bin       >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /projects/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /projects/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /projects/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /projects/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/projects\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): glory" $emailName < resultlog
EOF

if [ $glory = true ]
then
   if [ $test = no ]
   then
      cp /usr/tmp/$user/glory/visitbuild/visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-glory.tar.gz
      cp glory glory_install
      chmod 750 glory_install;./glory_install
   fi
fi

#
# Install on redsky.
#
rm -f redsky
cat <<EOF > redsky
#!/bin/sh
./visit-install -private -c sandia $ver linux-redsky /projects/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on redsky"          > resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /projects/visit                              >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /projects/visit/$ver+/linux-x86_64/bin       >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /projects/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /projects/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /projects/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /projects/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/projects\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail -s "VisIt install ($ver): redsky" $emailName < resultlog
EOF

if [ $redsky = true ]
then
   if [ $test = no ]
   then
      cp /usr/tmp/$user/redsky/visitbuild/visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-redsky.tar.gz
      cp redsky redsky_install
      chmod 750 redsky_install;./redsky_install
   fi
fi

#
# Clean up.
#
if [ $test = no ]
then
   rm -f hoth kickit aztec rzzeus xchem euclid ellipse glory redsky
fi
