#!/bin/sh
#-----------------------------------------------------------------------
#
# VISIT-CREATE-CHKSUMS - Create lists of the md5 checksums, sha1
#                        checksums, and file sizes for the visit
#                        distribution.
#
# Author: Eric Brugger
# Date:   August 30, 2005
#
# Usage:
#    visit-create-chksums -v <version> -d <distribution>
#
#-----------------------------------------------------------------------

dist=undefined
version=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.  
#
for abc
do
   case $1 in
      -d)
         dist=$2
         shift 2
         ;;
      -v)
         version=$2
         shift 2
         ;;
   esac
done

#
# Check that the distribution name and version number was provided.
#
if [ $dist = undefined ]
then
   echo "Usage: -v <version> -d <distribution>"
   exit
fi

if [ $version = undefined ]
then
   echo "Usage: -v <version> -d <distribution>"
   exit
fi

version2=`echo $version | tr "." "_"`

#
# Create an awk script for use with the filesize command
#
rm -f format_filesize
cat <<EOF > format_filesize
BEGIN { FS = " " }
      { printf "%-25s %s\n", \$5, \$9}
EOF

#
# Create a script to generate the file size.
#
rm -f filesize
cat <<EOF > filesize
#!/bin/sh
ls -l \$1 | sed "s/  */ /g" | gawk -f ../visit$version/format_filesize
EOF
chmod 755 filesize

#
# Create the md5 checksums, the sha1 checksums, and the file sizes.
#
cmds="md5sum sha1sum ../visit$version/filesize"
for cmd in $cmds
do
   case $cmd in
      md5sum)
         property=checksums
         output=visit_md5_checksums
         ;;
      sha1sum)
         property=checksums
         output=visit_sha1_checksums
         ;;
      ../visit$version/filesize)
         property="file sizes"
         output=visit_filesizes
         ;;
   esac

   rm -f $output

   echo ""                                         >  $output
   echo "The VisIt executable $property"           >> $output
   echo ""                                         >> $output
   $cmd INSTALL_NOTES                              >> $output
   $cmd VisIt-$version-i386-installer.dmg          >> $output
   $cmd VisIt-$version-x86_64-installer.dmg        >> $output
   $cmd visit-install                              >> $output
   $cmd jvisit$version.tar.gz                      >> $output
   $cmd visit$version.exe                          >> $output
   $cmd visit$version2.ibm-aix-pwr.tar.gz          >> $output
   $cmd visit$version2.ibm-aix-pwr64.tar.gz        >> $output
   $cmd visit$version2.linux-rhel3.tar.gz          >> $output
   $cmd visit$version2.linux-ubuntu8.tar.gz        >> $output
   $cmd visit$version2.linux-x86_64-rhel4.tar.gz   >> $output
   $cmd visit$version2.linux-x86_64-ubuntu8.tar.gz >> $output
   $cmd visit$version2.linux-x86_64.tar.gz         >> $output

   echo ""                                         >> $output
   echo "The VisIt source code $property"          >> $output
   echo ""                                         >> $output
   $cmd BUILD_NOTES                                >> $output
   $cmd BUILD_NOTES_MacOSX                         >> $output
   $cmd build_visit                                >> $output
   $cmd $dist.tar.gz                               >> $output
   $cmd visitdev$version.exe                       >> $output
   cd ../visit_third_party
   $cmd AdvIO-1.2.tar.gz                           >> ../visit$version/$output
   $cmd H5Part-1.4.2.tar.gz                        >> ../visit$version/$output
   $cmd H5Part-1.6.0.tar.gz                        >> ../visit$version/$output
   $cmd HDF4.2r1.tar.gz                            >> ../visit$version/$output
   $cmd ITAPS-FMDB-1.0-15Apr09.tar.gz              >> ../visit$version/$output
   $cmd ITAPS-GRUMMP-0.5.0-20Apr09.tar.gz          >> ../visit$version/$output
   $cmd ITAPS-MOAB-3.99-20Apr09.tar.gz             >> ../visit$version/$output
   $cmd IceT-0-5-4.tar.gz                          >> ../visit$version/$output
   $cmd Imaging-1.1.6.tar.gz                       >> ../visit$version/$output
   $cmd Mesa-5.0-mangled.tar.gz                    >> ../visit$version/$output
   $cmd MesaLib-6.4.2.tar.gz                       >> ../visit$version/$output
   $cmd MesaLib-7.5.tar.gz                         >> ../visit$version/$output
   $cmd Python-2.5.tgz                             >> ../visit$version/$output
   $cmd Python-2.6.4.tgz                           >> ../visit$version/$output
   $cmd Xdmf-2.1.tar.gz                            >> ../visit$version/$output
   $cmd boxlib.tar.gz                              >> ../visit$version/$output
   $cmd cfitsio3006.tar.gz                         >> ../visit$version/$output
   $cmd cgnslib_2.4-3.tar.gz                       >> ../visit$version/$output
   $cmd cmake-2.4.5.tar.gz                         >> ../visit$version/$output
   $cmd cmake-2.8.0.tar.gz                         >> ../visit$version/$output
   $cmd exodusii-4.46.tar.gz                       >> ../visit$version/$output
   $cmd fastbit-ibis1.0.9.tar.gz                   >> ../visit$version/$output
   $cmd gdal-1.3.2.tar.gz                          >> ../visit$version/$output
   $cmd gdal-1.7.1.tar.gz                          >> ../visit$version/$output
   $cmd google-perftools-0.97.tar.gz               >> ../visit$version/$output
   $cmd hdf5-1.8.2.tar.gz                          >> ../visit$version/$output
   $cmd hdf5-1.8.4.tar.gz                          >> ../visit$version/$output
   $cmd libccmio-2.6.1.tar.gz                      >> ../visit$version/$output
   $cmd netcdf-3.6.3.tar.gz                        >> ../visit$version/$output
   $cmd qt-everywhere-opensource-src-4.6.1.tar.gz  >> ../visit$version/$output
   $cmd qt-mac-free-3.3.8.tar.gz                   >> ../visit$version/$output
   $cmd qt-x11-free-3.3.8.tar.gz                   >> ../visit$version/$output
   $cmd silo-4.7.2.tar.gz                          >> ../visit$version/$output
   $cmd silo-4.7.tar.gz                            >> ../visit$version/$output
   $cmd szip-2.1.tar.gz                            >> ../visit$version/$output
   $cmd vtk-5.0.0c.tar.gz                          >> ../visit$version/$output
   $cmd vtk-5.0.0d.tar.gz                          >> ../visit$version/$output
   $cmd vtk-5.0.0e.tar.gz                          >> ../visit$version/$output
   $cmd vtk-5.0.0f.tar.gz                          >> ../visit$version/$output
   cd ../visit$version

   shift
done
