// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <XmdvPluginInfo.h>
#include <avtXmdvWriter.h>

VISIT_DATABASE_PLUGIN_ENTRY(Xmdv,Engine)

// ****************************************************************************
//  Method: XmdvEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a Xmdv writer.
//
//  Returns:    A Xmdv writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
XmdvEnginePluginInfo::GetWriter(void)
{
    return new avtXmdvWriter(writeOptions);
}

