SET(VISIT_NSIS_SEARCHPATH)

IF (WIN32)
    SET(VISIT_NSIS_SEARCHPATH "$ENV{PROGRAMFILES}/NSIS" 
                              "$ENV{PROGRAMFILES(X86)}/NSIS" )
ENDIF (WIN32)

FIND_PROGRAM(MAKENSIS
    makensis
    PATHS ${VISIT_NSIS_SEARCHPATH}
    DOC "Location of the NSIS executable"
)

STRING(COMPARE NOTEQUAL ${MAKENSIS} "MAKENSIS-NOTFOUND" MAKENSIS_FOUND)

