#include <ANALYZEPluginInfo.h>
#include <avtANALYZEFileFormat.h>
#include <avtSTSDFileFormatInterface.h>
#include <avtGenericDatabase.h>

// ****************************************************************************
//  Method:  ANALYZECommonPluginInfo::GetDatabaseType
//
//  Purpose:
//    Returns the type of a ANALYZE database.
//
//  Programmer:  whitlocb -- generated by xml2info
//  Creation:    Mon Nov 24 16:51:12 PST 2003
//
// ****************************************************************************
DatabaseType
ANALYZECommonPluginInfo::GetDatabaseType()
{
    return DB_TYPE_STSD;
}

// ****************************************************************************
//  Method:  ANALYZECommonPluginInfo::GetDefaultExtensions
//
//  Purpose:
//    Returns the default extensions for a ANALYZE database.
//
//  Programmer:  whitlocb -- generated by xml2info
//  Creation:    Mon Nov 24 16:51:12 PST 2003
//
// ****************************************************************************
std::vector<std::string>
ANALYZECommonPluginInfo::GetDefaultExtensions()
{
    std::vector<std::string> defaultExtensions;
    defaultExtensions.push_back("img");
    defaultExtensions.push_back("hdr");

    return defaultExtensions;
}

// ****************************************************************************
//  Method: ANALYZECommonPluginInfo::GetWriter
//
//  Purpose:
//      Sets up a ANALYZE writer.
//
//  Returns:    A ANALYZE writer.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Nov 24 16:51:12 PST 2003
//
// ****************************************************************************
avtDatabaseWriter *
ANALYZECommonPluginInfo::GetWriter(void)
{
    return NULL;
}

// ****************************************************************************
//  Method: ANALYZECommonPluginInfo::SetUpANALYZEDatabase
//
//  Purpose:
//      Sets up a ANALYZE database.
//
//  Arguments:
//      list    A list of file names.
//      nList   The number of timesteps in list.
//      nBlocks The number of blocks in the list.
//
//  Returns:    A ANALYZE database from list.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Nov 24 16:51:12 PST 2003
//
// ****************************************************************************
avtDatabase *
ANALYZECommonPluginInfo::SetupDatabase(const char *const *list,
                                   int nList, int nBlock)
{
    avtSTSDFileFormat ***ffl = new avtSTSDFileFormat**[nList];
    int nTimestep = nList / nBlock;
    for (int i = 0 ; i < nTimestep ; i++)
    {
        ffl[i] = new avtSTSDFileFormat*[nBlock];
        for (int j = 0 ; j < nBlock ; j++)
        {
            ffl[i][j] = new avtANALYZEFileFormat(list[i*nBlock + j]);
        }
    }
    avtSTSDFileFormatInterface *inter 
           = new avtSTSDFileFormatInterface(ffl, nTimestep, nBlock);
    return new avtGenericDatabase(inter);
}
