#include <PyMergeOperatorAttributes.h>
#include <ObserverToCallback.h>
#include <ColorAttribute.h>

// ****************************************************************************
// Module: PyMergeOperatorAttributes
//
// Purpose: 
//   Attributes for Merge operaetor
//
// Note:       Autogenerated by xml2python. Do not modify by hand!
//
// Programmer: xml2python
// Creation:   Thu Sep 22 16:56:21 PST 2005
//
// ****************************************************************************

//
// This struct contains the Python type information and a MergeOperatorAttributes.
//
struct MergeOperatorAttributesObject
{
    PyObject_HEAD
    MergeOperatorAttributes *data;
    bool owns;
};

//
// Internal prototypes
//
static PyObject *NewMergeOperatorAttributes();

static PyObject *
MergeOperatorAttributes_Notify(PyObject *self, PyObject *args)
{
    MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)self;
    obj->data->Notify();
    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
MergeOperatorAttributes_SetParallelMerge(PyObject *self, PyObject *args)
{
    MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)self;

    int ival;
    if(!PyArg_ParseTuple(args, "i", &ival))
        return NULL;

    // Set the parallelMerge in the object.
    obj->data->SetParallelMerge(ival != 0);

    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
MergeOperatorAttributes_GetParallelMerge(PyObject *self, PyObject *args)
{
    MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)self;
    PyObject *retval = PyInt_FromLong(obj->data->GetParallelMerge()?1L:0L);
    return retval;
}

static PyObject *
MergeOperatorAttributes_SetTolerance(PyObject *self, PyObject *args)
{
    MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)self;

    double dval;
    if(!PyArg_ParseTuple(args, "d", &dval))
        return NULL;

    // Set the tolerance in the object.
    obj->data->SetTolerance(dval);

    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
MergeOperatorAttributes_GetTolerance(PyObject *self, PyObject *args)
{
    MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)self;
    PyObject *retval = PyFloat_FromDouble(obj->data->GetTolerance());
    return retval;
}



static struct PyMethodDef MergeOperatorAttributes_methods[] = {
    {"Notify", MergeOperatorAttributes_Notify, METH_VARARGS},
    {"SetParallelMerge", MergeOperatorAttributes_SetParallelMerge, METH_VARARGS},
    {"GetParallelMerge", MergeOperatorAttributes_GetParallelMerge, METH_VARARGS},
    {"SetTolerance", MergeOperatorAttributes_SetTolerance, METH_VARARGS},
    {"GetTolerance", MergeOperatorAttributes_GetTolerance, METH_VARARGS},
    {NULL, NULL}
};

//
// Type functions
//

static void
MergeOperatorAttributes_dealloc(PyObject *v)
{
   MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)v;
   if(obj->owns)
       delete obj->data;
}

static int
MergeOperatorAttributes_compare(PyObject *v, PyObject *w)
{
    MergeOperatorAttributes *a = ((MergeOperatorAttributesObject *)v)->data;
    MergeOperatorAttributes *b = ((MergeOperatorAttributesObject *)w)->data;
    return (*a == *b) ? 0 : -1;
}

static PyObject *
MergeOperatorAttributes_getattr(PyObject *self, char *name)
{
    if(strcmp(name, "parallelMerge") == 0)
        return MergeOperatorAttributes_GetParallelMerge(self, NULL);
    if(strcmp(name, "tolerance") == 0)
        return MergeOperatorAttributes_GetTolerance(self, NULL);

    return Py_FindMethod(MergeOperatorAttributes_methods, self, name);
}

static int
MergeOperatorAttributes_setattr(PyObject *self, char *name, PyObject *args)
{
    // Create a tuple to contain the arguments since all of the Set
    // functions expect a tuple.
    PyObject *tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(tuple, 0, args);
    Py_INCREF(args);
    bool retval = false;

    if(strcmp(name, "parallelMerge") == 0)
        retval = (MergeOperatorAttributes_SetParallelMerge(self, tuple) != NULL);
    else if(strcmp(name, "tolerance") == 0)
        retval = (MergeOperatorAttributes_SetTolerance(self, tuple) != NULL);

    Py_DECREF(tuple);
    return retval ? 0 : -1;
}

static int
MergeOperatorAttributes_print(PyObject *v, FILE *fp, int flags)
{
    MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)v;

    if(obj->data->GetParallelMerge())
        fprintf(fp, "parallelMerge = 1\n");
    else
        fprintf(fp, "parallelMerge = 0\n");
    fprintf(fp, "tolerance = %g\n", obj->data->GetTolerance());

    return 0;
}

#include <snprintf.h>
PyObject *
PyMergeOperatorAttributes_StringRepresentation(const MergeOperatorAttributes *atts)
{
   std::string str; 
   char tmpStr[1000]; 

    if(atts->GetParallelMerge())
        SNPRINTF(tmpStr, 1000, "parallelMerge = 1\n");
    else
        SNPRINTF(tmpStr, 1000, "parallelMerge = 0\n");
    str += tmpStr;
    SNPRINTF(tmpStr, 1000, "tolerance = %g\n", atts->GetTolerance());
    str += tmpStr;
    return PyString_FromString(str.c_str());
}

static PyObject *
MergeOperatorAttributes_str(PyObject *v)
{
    MergeOperatorAttributesObject *obj = (MergeOperatorAttributesObject *)v;
    return PyMergeOperatorAttributes_StringRepresentation(obj->data);
}


//
// The doc string for the class.
//
static char *MergeOperatorAttributes_Purpose = "Attributes for Merge operaetor";

//
// The type description structure
//
static PyTypeObject MergeOperatorAttributesType =
{
    //
    // Type header
    //
    PyObject_HEAD_INIT(&PyType_Type)
    0,                                   // ob_size
    "MergeOperatorAttributes",                    // tp_name
    sizeof(MergeOperatorAttributesObject),        // tp_basicsize
    0,                                   // tp_itemsize
    //
    // Standard methods
    //
    (destructor)MergeOperatorAttributes_dealloc,  // tp_dealloc
    (printfunc)MergeOperatorAttributes_print,     // tp_print
    (getattrfunc)MergeOperatorAttributes_getattr, // tp_getattr
    (setattrfunc)MergeOperatorAttributes_setattr, // tp_setattr
    (cmpfunc)MergeOperatorAttributes_compare,     // tp_compare
    (reprfunc)0,                         // tp_repr
    //
    // Type categories
    //
    0,                                   // tp_as_number
    0,                                   // tp_as_sequence
    0,                                   // tp_as_mapping
    //
    // More methods
    //
    0,                                   // tp_hash
    0,                                   // tp_call
    (reprfunc)MergeOperatorAttributes_str,        // tp_str
    0,                                   // tp_getattro
    0,                                   // tp_setattro
    0,                                   // tp_as_buffer
    Py_TPFLAGS_CHECKTYPES,               // tp_flags
    MergeOperatorAttributes_Purpose,              // tp_doc
    0,                                   // tp_traverse
    0,                                   // tp_clear
    0,                                   // tp_richcompare
    0                                    // tp_weaklistoffset
};

//
// Helper functions for object allocation.
//

static MergeOperatorAttributes *defaultAtts = 0;

static PyObject *
NewMergeOperatorAttributes()
{
    MergeOperatorAttributesObject *newObject;
    newObject = PyObject_NEW(MergeOperatorAttributesObject, &MergeOperatorAttributesType);
    if(newObject == NULL)
        return NULL;
    if(defaultAtts)
        newObject->data = new MergeOperatorAttributes(*defaultAtts);
    else
        newObject->data = new MergeOperatorAttributes;
    newObject->owns = true;
    return (PyObject *)newObject;
}

static PyObject *
WrapMergeOperatorAttributes(const MergeOperatorAttributes *attr)
{
    MergeOperatorAttributesObject *newObject;
    newObject = PyObject_NEW(MergeOperatorAttributesObject, &MergeOperatorAttributesType);
    if(newObject == NULL)
        return NULL;
    newObject->data = (MergeOperatorAttributes *)attr;
    newObject->owns = false;
    return (PyObject *)newObject;
}

///////////////////////////////////////////////////////////////////////////////
//
// Interface that is exposed to the VisIt module.
//
///////////////////////////////////////////////////////////////////////////////

PyObject *
MergeOperatorAttributes_new(PyObject *self, PyObject *args)
{
    if (!PyArg_ParseTuple(args, ""))
        return NULL;
    return (PyObject *)NewMergeOperatorAttributes();
}

//
// Plugin method table. These methods are added to the visitmodule's methods.
//
static PyMethodDef MergeOperatorAttributesMethods[] = {
    {"MergeOperatorAttributes", MergeOperatorAttributes_new, METH_VARARGS},
    {NULL,      NULL}        /* Sentinel */
};

static Observer *MergeOperatorAttributesObserver = 0;
static bool MergeOperatorAttributesEnableLogging = true;

static void
PyMergeOperatorAttributes_WriteLog(Subject *subj, void *data)
{
    MergeOperatorAttributes *atts = (MergeOperatorAttributes *)subj;
    FILE *logFile = (FILE *)data;

    if(!MergeOperatorAttributesEnableLogging || (logFile == NULL))
        return;

    fprintf(logFile, "# MergeOperatorAttributes_WriteLog()\n");
}

void
PyMergeOperatorAttributes_StartUp(MergeOperatorAttributes *subj, FILE *logFile)
{
    if(subj == 0)
        return;

    PyMergeOperatorAttributes_SetDefaults(subj);

    //
    // Create the observer that will be notified when the attributes change.
    //
    if(MergeOperatorAttributesObserver == 0)
    {
        MergeOperatorAttributesObserver = new ObserverToCallback(subj,
            PyMergeOperatorAttributes_WriteLog, (void *)logFile);
    }

    MergeOperatorAttributesEnableLogging = true;
}

void
PyMergeOperatorAttributes_CloseDown()
{
    delete defaultAtts;
    defaultAtts = 0;
    delete MergeOperatorAttributesObserver;
    MergeOperatorAttributesObserver = 0;
}

PyMethodDef *
PyMergeOperatorAttributes_GetMethodTable(int *nMethods)
{
    *nMethods = 1;
    return MergeOperatorAttributesMethods;
}

bool
PyMergeOperatorAttributes_Check(PyObject *obj)
{
    return (obj->ob_type == &MergeOperatorAttributesType);
}

MergeOperatorAttributes *
PyMergeOperatorAttributes_FromPyObject(PyObject *obj)
{
    MergeOperatorAttributesObject *obj2 = (MergeOperatorAttributesObject *)obj;
    return obj2->data;
}

PyObject *
PyMergeOperatorAttributes_NewPyObject()
{
    return NewMergeOperatorAttributes();
}

PyObject *
PyMergeOperatorAttributes_WrapPyObject(const MergeOperatorAttributes *attr)
{
    return WrapMergeOperatorAttributes(attr);
}

void
PyMergeOperatorAttributes_SetLogging(bool val)
{
    MergeOperatorAttributesEnableLogging = val;
}

void
PyMergeOperatorAttributes_SetDefaults(const MergeOperatorAttributes *atts)
{
    if(defaultAtts)
        delete defaultAtts;

    defaultAtts = new MergeOperatorAttributes(*atts);
}

