#!/bin/sh

# Change directories to the working directory.
cd visit_run_tests

# Get the latest version of the test script
rm -f regressiontest_pascal
wget https://raw.githubusercontent.com/visit-dav/visit/develop/src/tools/dev/scripts/regressiontest_pascal

# Run the test suite.
chmod 755 regressiontest_pascal
./regressiontest_pascal
