#!/bin/sh -x
#
# Modifications:
#   Mark C. Miller, Thu Jul 29 23:35:19 PDT 2010
#   Added option to ignore third party lib problems to cmake invokation.
#
#   Eric Brugger, Thu Mar 31 09:38:38 PDT 2011
#   Modified the script to work with the 2.2RC instead of the 2.0RC.
#
#   Eric Brugger, Tue Apr 12 10:53:02 PDT 2011
#   Removed the specular lighting tests from the skip list.
#
#   Jeremy Meredith, Tue Aug  9 17:19:55 EDT 2011
#   Updated the subversion host/path.
#
#   Eric Brugger, Thu Aug 25 11:22:39 PDT 2011
#   Modified the script to work on edge.
#
#   Eric Brugger, Thu Aug 25 14:11:16 PDT 2011
#   Modified the script to send out the e-mail only after the results
#   were posted.
#
#   Eric Brugger, Wed Jan 25 13:26:36 PST 2012
#   Modified the command that submits the batch job to run the test suite
#   to specify that it isn't using any of the Lustre file systems so that
#   the job will run even if one of the Lustre file systems is down.
#
#   Eric Brugger, Fri Jun 22 07:54:19 PDT 2012
#   I modified the script to use cmake 2.8.8. I also added several failing
#   tests to the skip list.
#
#   Mark C. Miller, Wed Jun 27 12:30:13 PDT 2012
#   Removed zipwrapper tests from skip list because the tests were updated
#   to use STL in place of VTK.
#
#   Cyrus Harrison, Wed Aug 15 12:31:00 PDT 2012
#   Update to use python test suite
#
#   Eric Brugger, Fri Oct 11 14:10:51 PDT 2013
#   Change the path to the cmake used to build visit to the latest 2.8.10.2
#   version.
#
#   Eric Brugger, Fri Oct 18 15:01:56 PDT 2013
#   I changed "make test" to "make testdata" in the data directory since the
#   name of the target changed.
#
#   Eric Brugger, Fri Aug 15 11:02:18 PDT 2014
#   I added "--parallel-launch srun" to the runtest command to specify srun
#   as the parallel launch method.
#
#   Eric Brugger, Fri Aug 15 12:54:39 PDT 2014
#   I modified the script to use cmake 2.8.12.2 to configure visit.
#
#   Eric Brugger, Wed Oct 29 08:04:01 PDT 2014
#   I modified the script to use surface.
#
#   Eric Brugger, Tue Jan 13 14:09:04 PST 2015
#   I modified the script to use the account views for submitting the batch
#   job.
#
#   Eric Brugger, Thu Feb 12 08:17:18 PST 2015
#   I modified the script to use cmake 3.0.2 to configure visit.
#
#   Eric Brugger, Fri Sep 11 14:05:18 PDT 2015
#   I added the command line option "-branch", which takes a branch name.
#   While I was at it I also modified the script to use 16 cores instead of
#   12 since it is grabbing an entire node of surface, which has 16 cores.
#
#   Eric Brugger, Wed Sep  7 09:17:29 PDT 2016
#   I updated the script to build using the newly built 2.12 libraries.
#
#   Eric Brugger, Mon Jun 25 14:35:01 PDT 2018
#   I modified the script to run on pascal.
#
#   Kathleen Biagas, Thu Nov  8 10:14:27 PST 2018
#   Added creation and installation of package to the build.
#   Added cmakeCmd, pass it to test suite.
#
#   Eric Brugger, Wed Dec  5 13:06:31 PST 2018
#   I modified the script to handle the new structure of the src, data and
#   test directories.
#
#   Eric Brugger, Fri Jan  4 09:34:59 PST 2019
#   I modified the script to work with the GitHub repository.
#
#   Eric Brugger, Fri Oct  4 09:12:49 PDT 2019
#   I modified the installation of visit to no longer add toss3 to the
#   installation path.
#
#   Cyrus Harrison, Tue Nov 26 16:50:14 PST 2019
#   Directly call visit_test_suite.py instead of old runtest wrapper
#
#   Kathleen Biagas, Mon Feb 24 2020
#   VISIT_BUILD_AVTEXAMPLES renamed to VISIT_ENABLE_AVTEXAMPLES
#
#   Eric Brugger, Mon Dec 21 09:11:31 PST 2020
#   Update cmakeCmd to use CMake 3.14.7, required by new VTKm.
#
#   Eric Brugger, Fri Jan  8 11:12:04 PST 2021
#   I modified the script to also make the manuals before making the package
#   since the manuals are now required to make the package.
#
#   Kathleen Biagas, Thu June 16, 2022
#   Modified cmakeCmd to use 3.3's 3.18.2 version and to use gcc-7.3
#   for test_trunk. Modified the test_branch to build 3.2.
#
#   Cyrus Harrison, Thu Sep  8 12:42:42 PDT 2022
#   Use new entry point for visit testing module.
#
#   Eric Brugger, Wed Sep 28 10:11:32 PDT 2022
#   Changed all paths using /usr/workspace/wsa to /usr/WS1 so that the
#   launcher test would pass. They are both the same directory, but the
#   current directory when running the tests needs to start with /usr/WS1
#   for the launcher test to work properly.
#
#   Eric Brugger, Wed Feb 15 16:29:23 PST 2023
#   I corrected the path to the pascal config site file to take into account
#   that we were now doing out of source builds.
#
#   Eric Brugger, Thu Mar  9 13:10:16 PST 2023
#   I changed the script to run the test scripts directly in the current
#   directory without scp'ing the scripts to the test machine and running
#   the scripts on the test machine through ssh. This looses some generality
#   in that the tests need to be run on the same machine as the script
#   but avoids some potential authentication issues with scp and ssh. We
#   currently run the script and the tests on the same machine so this
#   isn't an issue.
#
#   I removed references to nersc, since we no longer involve any nersc
#   systems in our testing. 
#
#   I updated the script to take into account that pascal is now toss4
#   instead of toss3. This included switching from msub to sbatch, using
#   a toss4 config site file, and using a toss4 cmake.
#
#   Eric Brugger, Fri Mar 10 07:09:59 PST 2023
#   I reduced the alloted time for the test suite to run from 10 hours to
#   8 hours. Running the tests with 2 processors reduced the typical time
#   to complete the tests to 5 1/2 hours, so 8 hours should be plenty. I
#   also changed the directory to copy the results to the "old_results"
#   directory outside the repo, which should speed up git operations. I
#   changed a python reference to python3.
#
#   Eric Brugger, Fri Mar 10 14:32:00 PST 2023
#   I renamed the "linux-x86_64" directory in the visit install to
#   "linux-x86_64-toss4" so that the launcher script would find the
#   installation on toss4.
#
#   Eric Brugger, Sun Mar 12 16:40:54 PDT 2023
#   Install git lfs before updating the repository. Added more logging
#   to the git repository update.
#
#   Eric Brugger, Wed Mar 15 13:41:38 PDT 2023
#   Update the location of where libstripack is copied from.
#
#   Eric Brugger, Tue Jun  4 10:30:31 PDT 2024
#   I moved the setting of the permissions so that others may access the
#   test directory to another script.
#
#   Kathleen Biagas, Tue July 16, 2024 
#   Added repoDir and buildDir vars to aid in changing directories between
#   them.  Call `git submodule init` when cloning, and 'git submodule update`
#   when updating. Don't 'lfs pull' in test and data dir, since it is already
#   performed at the repo root. Perform the build completely outside the repo
#   dir. Have make.out, make.err and installlog be local to the build dir.
#
#   Justin Privitera, Mon Sep 23 10:18:29 PDT 2024
#   Update visit-install location.
#
#   Eric Brugger, Mon Oct  7 11:15:18 PDT 2024
#   Updated to run the test suite on poodle instead of pascal. Made
#   the logic that detects new test results more general.
#
#   Eric Brugger, Thu Nov 21 12:15:11 PST 2024
#   Reorder some git operations when committing changes to GitHub to
#   avoid unnecessary merges.
#
#   Eric Brugger, Mon Mar  3 09:11:37 PST 2025
#   Include the actual hostname in the name of the sbatch output filename.
# 
#   Cyrus Harrison, 
#   Removed cuda LD_LIBRARY_PATH Wed Sep 10 11:57:45 PDT 2025
#
#   Eric Brugger, Fri Oct 31 13:53:46 PDT 2025
#   I changed some output to go to the buildlog instead of standard out.
#
#   Eric Brugger, Fri Nov  7 10:32:18 PST 2025
#   I changed the time limit on the batch job from 8 to 10 hours. I
#   increased the number of cores used to build visit from 36 to 56.
# 
#   Cyrus Harrison, Mon Dec  1 14:34:33 PST 2025
#   Changed to run on dane (instead of poodle)
#
#   Eric Brugger, Fri Dec 12 14:57:38 PST 2025
#   Updated the logging so that the checkout, run and post scripts each
#   create their own log file. The post script now runs after a file
#   indicating the test run finished appears rather than a fixed amount
#   of time. Removed the debug option.
#
#   Eric Brugger, Tue Dec 30 09:36:22 PST 2025
#   Add code to allow group read/write access to the dashboard repository
#   after updating it.
#
#   Kathleen Biagas, Tue Jan 27, 2026
#   Copied from regressiontest_dane, and generalized to be run on any 
#   supported machine, currently only dane and rzwhippet.
#   This script no longer creates the other scripts to be run.
#





# Determine the users name and e-mail address.
#
user=`whoami`

#
# Set the user e-mail address.
#
userEmail=unknown
case $user in
    kbonnell)
        userEmail=biagas2@llnl.gov
        ;;
    brugger)
        userEmail=brugger1@llnl.gov
        ;;
    cyrush)
        userEmail=cyrush@llnl.gov
        ;;
    hrchilds)
        userEmail=hank@uoregon.edu
        ;;
    mcmiller)
        userEmail=miller86@llnl.gov
        ;;
    miller)
        userEmail=miller86@llnl.gov
        ;;
    miller86)
        userEmail=miller86@llnl.gov
        ;;
    harrison37)
        userEmail=cyrush@llnl.gov
        ;;
    cyrush)
        userEmail=cyrush@llnl.gov
        ;;
    justin)
        userEmail=privitera1@llnl.gov
        ;;
esac

if test "$userEmail" = "unknown" ; then
    echo "Unknown user name. Exiting."
    exit 1
fi

#
# Parse the command line to determine if we should run the test suite
# on the trunk or RC.
#
branch="trunk"
revision="latest"
serial="false"
testDir="/usr/WS1/visit"
post="true"

for abc
do
    case $1 in
        -trunk)
            branch="trunk"
            shift
            ;;
        -branch)
            branch=$2
            shift 2
            ;;
        -serial)
            serial="true"
            shift
            ;;
        -parallel)
            serial="false"
            shift
            ;;
        -r)
            revision=$2
            shift 2
            ;;
        -no-post)
            post="false"
            shift
            ;;
    esac
done

testHost=`hostname`

# when the paths are consistent on cz/rz then setting of cmakeCmd can be removed from the if-test

# shorten the testHost
if [[ $testHost == *"rzwhippet"* ]]; then
    testHost="rzwhippet"
    configFile="rzwhippet10.cmake"
    cmakeCmd="/usr/workspace/visit/visit/thirdparty_shared/3.5.0-python-3.13/toss4/cmake/3.31.8/linux-x86_64_gcc-10.3/bin/cmake"
elif [[ $testHost == *"dane"* ]]; then
    testHost="dane"
    configFile="dane1.cmake"
    cmakeCmd="/usr/workspace/visit/visit/thirdparty_shared/3.5.0-python3.13/toss4/cmake/3.31.8/linux-x86_64_gcc-10.3/bin/cmake"
else
    echo "Unsupported host: $testHost. Valid hosts are dane and rzhwippet."
    exit 1
fi

workingDir="test_trunk"

subTag=`date +%Y-%m-%d-%H:%M`

repoDir=$testDir/$workingDir/visit
scriptDir=$repoDir/src/tools/dev/scripts

logDir=$testDir/$workingDir/nightly_logs
checkoutLogFile=$logDir/$subTag/checkout_${testHost}_log
buildLogFile=$logDir/$subTag/build_${testHost}_log
postLogFile=$logDir/$subTag/post_${testHost}_log
runFinishedFile=$testDir/$workingDir/nightly_cron/run_finished

# Create the working directory if necessary.
if test ! -e $testDir/$workingDir; then
    mkdir $testDir/$workingDir
fi

# Create the nightly_logs directory if necessary.
if test ! -e $logDir; then
    mkdir $logDir
fi

# Create the log directory for this run.
mkdir $logDir/$subTag

if test "$testHost" = "dane" ; then
    hostPartition="pbatch"
    hostBank="wbronze"
else
    # rzwhippet
    hostPartition="pdebug"
    hostBank="ecopper"
fi


#
# Run the script to checkout/update the source code.
#
$scriptDir/regressiontest_checkout $subTag $branch $revision > $checkoutLogFile 2>&1

rm -f $runFinishedFile

#
# Run the script to compile source and run the tests.
#
sbatch --partition=$hostPartition --account=$hostBank --time=10:00:00 --ntasks=56 --nodes=1 --tasks-per-node=56 \
--output=$buildLogFile \
$scriptDir/regressiontest_buildrun $subTag $serial $testHost $cmakeCmd $configFile

#
# Run the script to post test results
#

$scriptDir/regressiontest_postit $subTag $testHost $serial $post > $postLogFile 2>&1
