#!/bin/sh

# Change directories to the working directory.
cd visit_run_tests

# Get the latest version of the test script
rm -rf svn_bin
svn co svn+ssh://brugger@cori.nersc.gov/project/projectdirs/visit/svn/visit/trunk/src/tools/dev/scripts

# Run the test suite.
scripts/regressiontest_surface

sleep 600

#scripts/regressiontest_surface -branch 2.13RC
