#!/bin/sh
#-----------------------------------------------------------------------
#
# VISIT-INSTALL-CLOSED - Install the visit distributions on the closed
#                        network.
#
# Author: Eric Brugger
# Date:   February 12, 2001
#
# Usage:
#    visit-install-closed [-beta | -private | -public] -v <version>
#
# Modifications:
#   Brad Whitlock, Tue Mar 7 14:10:26 PST 2006
#   I added -b bdivp to the visit-install invokations.
#
#   Eric Brugger, Mon Apr  7 13:52:50 PDT 2008
#   Removed sc install.
#
#   Hank Childs, Sat May  2 13:26:51 CDT 2009
#   Renamed config file to llnl_closed.
#
#   Eric Brugger, Fri Nov  5 15:40:02 PDT 2010
#   Replaced hopi with inca and removed pruple.
#
#   Eric Brugger, Wed Jan  5 09:40:00 PST 2011
#   Added terminator.
#
#   Eric Brugger, Fri Mar 25 10:20:49 PDT 2011
#   Added cielo.
#
#   Eric Brugger, Mon Jul 30 10:31:10 PDT 2012
#   Added gremlin.
#
#   Eric Brugger, Wed Mar 20 11:49:58 PDT 2013
#   Deleted gremlin. Deleted terminator. Replaced termite with hitit.
#
#   Eric Brugger, Thu Jun 20 10:37:05 PDT 2013
#   I modified the hitit install since it is now an x86_64 system instead
#   of an i686 system.
#
#   Eric Brugger, Tue Jul  9 11:23:43 PDT 2013
#   I changed the gateway node to login to cielo.
#
#   Eric Brugger, Mon Nov 21 11:53:53 PST 2016
#   Deleted cielo. Added trinity.
#
#   Eric Brugger, Mon Nov 21 16:43:04 PST 2016
#   Added jade.
#
#   Eric Brugger, Mon Jan  9 13:52:57 PST 2017
#   I replaced inca with zin.
#
#   Eric Brugger, Tue Jan 17 17:12:11 PST 2017
#   I replaced hitit with winnipeg.
#
#   Eric Brugger, Fri Feb 17 12:17:29 PST 2017
#   I changed the bank for all the LLNL systems from bdivp to wbronze.
#
#   Eric Brugger, Mon Mar 19 14:23:59 PDT 2018
#   I removed the modifications to the internallauncher for toss3 
#   systems. I made a change in internallauncher and customlauncher
#   that made this unnecessary.
#
#   Eric Brugger, Mon Nov 19 15:54:23 PST 2018
#   I added shark.
#
#   Eric Brugger, Wed Mar 20 10:31:35 PDT 2019
#   I deleted zin. I added sierra. I updated jade for 3.0.0b.
#
#   Eric Brugger, Thu Sep 26 17:32:41 PDT 2019
#   I removed special logic for installing on toss3 systems.
#
#   Eric Brugger, Mon Jan 13 15:24:51 PST 2020
#   I removed shark.
#
#   Eric Brugger, Wed Jun  8 15:19:01 PDT 2022
#   I added logic to the jade install to copy libraries needed to run
#   on toss4 systems.
#
#   Eric Brugger, Tue Jun 14 11:57:11 PDT 2022
#   I removed the logic on the jade install that copies the libraries
#   needed by Qt, since those now get included by default.
#
#   Eric Brugger, Wed Nov 29 11:16:25 PST 2023
#   I removed the "-none" option since all the machines are now off by
#   default. Turning on a machine is now done with -<machine_name>
#   instead of +<machine_name>.
#
#-----------------------------------------------------------------------

test=no

user=`whoami`

#
# Parse the execute line, providing default values for error checking.
#
magma="false"
sierra="false"

ver=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -magma)
         magma="true"
         shift
         ;;
      -sierra)
         sierra="true"
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
   esac
done

#
# Check that the version was provided.
#
if [ "$ver" = "undefined" ]
then
   echo "Usage: [-<machine name>] -v <version>"
   exit
fi

#
# Check that the visit install script is present.
#
if [ ! -e visit-install ]
then
   echo "visit-install is missing."
   exit
fi

ver2=`echo $ver | tr "." "_"`
ver=`echo $ver2 | tr "_" "."`

#
# Install on magma.
#
rm -f magma_install
cat <<EOF > magma_install
#!/bin/sh
set -e
./visit-install -private -c llnl_closed -g visit -b wbronze -gw -l $ver linux-x86_64-magma /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                              > resultlog 2>&1
echo "        install of visit on magma"              >> resultlog 2>&1
echo "       --------------------------"             >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
df -k /usr/gapps/visit                               >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin  >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "The database plugins:"                         >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.magma
mv resultlog resultlog.magma
EOF

if [ "$magma" = "true" ]
then
   if [ "$test" = "no" ]
   then
      chmod 750 magma_install;./magma_install
   fi
fi

#
# Install on sierra
#
rm -f sierra_install
cat <<EOF > sierra_install
#!/bin/sh
set -e
./visit-install -private -c llnl_closed -g visit -b wbronze -gw -l $ver linux-intel-lassen /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                              > resultlog 2>&1
echo "        install of visit on sierra"            >> resultlog 2>&1
echo "       ----------------------------"           >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
df -k /usr/gapps/visit                               >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-intel/bin         >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "The database plugins:"                         >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.sierra
mv resultlog resultlog.sierra
EOF

if [ "$sierra" = "true" ]
then
   if [ "$test" = "no" ]
   then
      chmod 750 sierra_install;./sierra_install
   fi
fi

#
# Clean up.
#
if [ "$test" = "no" ]
then
   rm -f magma_install sierra_install
fi
