// ************************************************************************* //
//  File: CracksClipperPluginInfo.h
// ************************************************************************* //

#ifndef CRACKSCLIPPER_PLUGIN_INFO_H
#define CRACKSCLIPPER_PLUGIN_INFO_H
#include <OperatorPluginInfo.h>
#include <operator_plugin_exports.h>

class CracksClipperAttributes;

// ****************************************************************************
//  Class: CracksClipperPluginInfo
//
//  Purpose:
//    Five classes that provide all the information about an CracksClipper operator
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:12:33 PST 2006
//
//  Modifications:
//
// ****************************************************************************

class CracksClipperGeneralPluginInfo : public virtual GeneralOperatorPluginInfo
{
  public:
    virtual char *GetName() const;
    virtual char *GetVersion() const;
    virtual char *GetID() const;
    virtual bool  EnabledByDefault() const;
};

class CracksClipperCommonPluginInfo : public virtual CommonOperatorPluginInfo, public virtual CracksClipperGeneralPluginInfo
{
  public:
    virtual AttributeSubject *AllocAttributes();
    virtual void CopyAttributes(AttributeSubject *to, AttributeSubject *from);
};

class CracksClipperGUIPluginInfo : public virtual GUIOperatorPluginInfo, public virtual CracksClipperCommonPluginInfo
{
  public:
    virtual const char *GetMenuName() const;
    virtual QvisPostableWindowObserver *CreatePluginWindow(int type,
        AttributeSubject *attr, QvisNotepadArea *notepad);
};

class CracksClipperViewerPluginInfo : public virtual ViewerOperatorPluginInfo, public virtual CracksClipperCommonPluginInfo
{
  public:
    virtual AttributeSubject *GetClientAtts();
    virtual AttributeSubject *GetDefaultAtts();
    virtual void SetClientAtts(AttributeSubject *atts);
    virtual void GetClientAtts(AttributeSubject *atts);

    virtual void InitializeOperatorAtts(AttributeSubject *atts,
                                        const ViewerPlot *plot,
                                        const bool fromDefault);

    static void InitializeGlobalObjects();
  private:
    static CracksClipperAttributes *defaultAtts;
    static CracksClipperAttributes *clientAtts;
};

class CracksClipperEnginePluginInfo : public virtual EngineOperatorPluginInfo, public virtual CracksClipperCommonPluginInfo
{
  public:
    virtual avtPluginFilter *AllocAvtPluginFilter();
};

class CracksClipperScriptingPluginInfo : public virtual ScriptingOperatorPluginInfo, public virtual CracksClipperCommonPluginInfo
{
  public:
    virtual void InitializePlugin(AttributeSubject *subj, void *data);
    virtual void *GetMethodTable(int *nMethods);
    virtual bool TypesMatch(void *pyobject);
    virtual char *GetLogString();
    virtual void SetDefaults(const AttributeSubject *atts);
};

#endif
