// ************************************************************************* //
//                        DeferExpressionScriptingPluginInfo.C
// ************************************************************************* //
#include <DeferExpressionPluginInfo.h>
#include <PyDeferExpressionAttributes.h>

#if defined(__APPLE__)
#define GetScriptingInfo DeferExpression_GetScriptingInfo
#endif

// ****************************************************************************
//  Function:  GetScriptingInfo
//
//  Purpose:
//    Return a new ScriptingPluginInfo for the DeferExpression plot.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Sep 20 13:25:14 PST 2005
//
// ****************************************************************************
extern "C" ScriptingOperatorPluginInfo* GetScriptingInfo()
{
    return new DeferExpressionScriptingPluginInfo;
}

// ****************************************************************************
// Method: DeferExpressionScriptingPluginInfo::InitializePlugin
//
// Purpose: 
//   Calls the initialization function for the plugin.
//
// Arguments:
//   subj    : A pointer to the plugin's state object.
//   logFile : A pointer to the logFile to be used.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Sep 20 13:25:14 PST 2005
//
// Modifications:
//   
// ****************************************************************************

void
DeferExpressionScriptingPluginInfo::InitializePlugin(AttributeSubject *subj,
    FILE *logFile)
{
    PyDeferExpressionAttributes_StartUp((DeferExpressionAttributes *)subj, logFile);
}

// ****************************************************************************
// Method: DeferExpressionScriptingPluginInfo::GetMethodTable
//
// Purpose: 
//   Returns a pointer to the plugin's Python method table. These methods are
//   added to the top-level visit module's methods.
//
// Arguments:
//   nMethods : Returns the number of methods in the method table.
//
// Returns:    A pointer to the method table.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Sep 20 13:25:14 PST 2005
//
// Modifications:
//   
// ****************************************************************************

void *
DeferExpressionScriptingPluginInfo::GetMethodTable(int *nMethods)
{
    return PyDeferExpressionAttributes_GetMethodTable(nMethods);
}

// ****************************************************************************
// Method: DeferExpressionScriptingPluginInfo::TypesMatch
//
// Purpose: 
//   Returns whether or not the input PyObject is DeferExpression plot attributes.
//
// Arguments:
//   pyobject : A PyObject cast to void*.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Sep 20 13:25:14 PST 2005
//
// Modifications:
//   
// ****************************************************************************

bool
DeferExpressionScriptingPluginInfo::TypesMatch(void *pyobject)
{
    return PyDeferExpressionAttributes_Check((PyObject *)pyobject);
}

// ****************************************************************************
// Method: DeferExpressionScriptingPluginInfo::SetLogging
//
// Purpose: 
//   Used to turn logging of commands on and off.
//
// Arguments:
//   val : Whether or not to log state information.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Sep 20 13:25:14 PST 2005
//
// Modifications:
//   
// ****************************************************************************

void
DeferExpressionScriptingPluginInfo::SetLogging(bool val)
{
    PyDeferExpressionAttributes_SetLogging(val);
}

// ****************************************************************************
// Method: DeferExpressionScriptingPluginInfo::SetDefaults
//
// Purpose: 
//   Used to set the default values for a plugin's state object.
//
// Arguments:
//   atts : The new state.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Sep 20 13:25:14 PST 2005
//
// Modifications:
//   
// ****************************************************************************

void
DeferExpressionScriptingPluginInfo::SetDefaults(const AttributeSubject *atts)
{
    PyDeferExpressionAttributes_SetDefaults((const DeferExpressionAttributes *)atts);
}
