// ************************************************************************* //
//  File: ProjectCommonPluginInfo.C
// ************************************************************************* //

#include <ProjectPluginInfo.h>
#include <ProjectAttributes.h>

// ****************************************************************************
//  Method: ProjectCommonPluginInfo::AllocAttributes
//
//  Purpose:
//    Return a pointer to a newly allocated attribute subject.
//
//  Returns:    A pointer to the newly allocated attribute subject.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Tue May 18 14:35:37 PST 2004
//
// ****************************************************************************

AttributeSubject *
ProjectCommonPluginInfo::AllocAttributes()
{
    return new ProjectAttributes;
}

// ****************************************************************************
//  Method: ProjectCommonPluginInfo::CopyAttributes
//
//  Purpose:
//    Copy a Project attribute subject.
//
//  Arguments:
//    to        The destination attribute subject.
//    from      The source attribute subject.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Tue May 18 14:35:37 PST 2004
//
// ****************************************************************************

void 
ProjectCommonPluginInfo::CopyAttributes(AttributeSubject *to,
    AttributeSubject *from)
{
    *((ProjectAttributes *) to) = *((ProjectAttributes *) from);
}
