
# ----------------------------------------------------------------------------
#  CLASSES: nightly
#
#  Test Case:  lata.py 
#
TurnOffAllAnnotations()
# on change le stride des vecteurs par defaut 
vd=VectorAttributes()
vd.SetUseStride(1)
SetDefaultPlotOptions(vd)
res=res=OpenDatabase(data_path("Lata_test_data/2D_VDF/PAR_2D_VDF.lata"))

ok=AddPlot("Mesh","dom_solide")
ok=AddPlot("Pseudocolor","TEMPERATURE_ELEM_dom_solide")
ok=AddPlot("Vector","VITESSE_ELEM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_00")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/2D_VDF/PAR_2D_VDF.lata"))

ok=AddPlot("Pseudocolor","TEMPERATURE_SOM_dom_solide")
ok=AddPlot("Vector","VITESSE_SOM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_01")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/2D_VDF/PAR_2D_VDF.lata"))

ok=AddPlot("Mesh","dom_fluide")
ok=AddPlot("Vector","VITESSE_FACES_dom_fluide_dual")
AddPlot("Subset", "blocks(dom_solide)")
SetTimeSliderState(2)
DrawPlots()
Test("lata_02")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/3D_VDF/PAR_3D_VDF.lata"))

ok=AddPlot("Mesh","dom_solide")
ok=AddPlot("Pseudocolor","TEMPERATURE_ELEM_dom_solide")
ok=AddPlot("Vector","VITESSE_ELEM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_03")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/3D_VDF/PAR_3D_VDF.lata"))

ok=AddPlot("Pseudocolor","TEMPERATURE_SOM_dom_solide")
ok=AddPlot("Vector","VITESSE_SOM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_04")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/3D_VDF/PAR_3D_VDF.lata"))

ok=AddPlot("Mesh","dom_fluide")
ok=AddPlot("Vector","VITESSE_FACES_dom_fluide_dual")
AddPlot("Subset", "blocks(dom_solide)")
SetTimeSliderState(2)
DrawPlots()
Test("lata_05")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/2D_VEF/PAR_2D_VEF.lata"))

ok=AddPlot("Mesh","dom_solide")
ok=AddPlot("Pseudocolor","TEMPERATURE_ELEM_dom_solide")
ok=AddPlot("Vector","VITESSE_ELEM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_06")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/2D_VEF/PAR_2D_VEF.lata"))

ok=AddPlot("Pseudocolor","TEMPERATURE_SOM_dom_solide")
ok=AddPlot("Vector","VITESSE_SOM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_07")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/2D_VEF/PAR_2D_VEF.lata"))

ok=AddPlot("Mesh","dom_fluide")
ok=AddPlot("Vector","VITESSE_FACES_dom_fluide_dual")
AddPlot("Subset", "blocks(dom_solide)")
SetTimeSliderState(2)
DrawPlots()
Test("lata_08")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/2D_VEF/PAR_2D_VEF.lata"))

ok=AddPlot("Mesh","dom_fluide")
ok=AddPlot("Vector","VITESSE_FACES_dom_fluide_centerfaces")
SetTimeSliderState(2)
DrawPlots()
Test("lata_09")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/3D_VEF/PAR_3D_VEF.lata"))

ok=AddPlot("Mesh","dom_solide")
ok=AddPlot("Pseudocolor","TEMPERATURE_ELEM_dom_solide")
ok=AddPlot("Vector","VITESSE_ELEM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_10")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/3D_VEF/PAR_3D_VEF.lata"))

ok=AddPlot("Pseudocolor","TEMPERATURE_SOM_dom_solide")
ok=AddPlot("Vector","VITESSE_SOM_dom_fluide")
SetTimeSliderState(2)
DrawPlots()
Test("lata_11")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/3D_VEF/PAR_3D_VEF.lata"))

ok=AddPlot("Mesh","dom_fluide")
ok=AddPlot("Vector","VITESSE_FACES_dom_fluide_dual")
AddPlot("Subset", "blocks(dom_solide)")
SetTimeSliderState(2)
DrawPlots()
Test("lata_12")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/3D_VEF/PAR_3D_VEF.lata"))

ok=AddPlot("Mesh","dom_fluide")
ok=AddPlot("Vector","VITESSE_FACES_dom_fluide_centerfaces")
SetTimeSliderState(2)
DrawPlots()
Test("lata_13")
DeleteAllPlots()
res=res=OpenDatabase(data_path("Lata_test_data/./FTD_remaillage_vdf/post.lata"))

ok=AddPlot("Mesh","INTERFACES")
ok=AddPlot("Pseudocolor","COURBURE_som_INTERFACES")
SetTimeSliderState(2)
DrawPlots()
Test("lata_14")
DeleteAllPlots()
Exit()
