// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <lataPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(lata,Engine)

// ****************************************************************************
//  Method: lataEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a lata writer.
//
//  Returns:    A lata writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
lataEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

