// ************************************************************************* //
//                        SliceScriptingPluginInfo.C
// ************************************************************************* //
#include <SlicePluginInfo.h>
#include <PySliceAttributes.h>

#if defined(__APPLE__)
#define GetScriptingInfo Slice_GetScriptingInfo
#endif

// ****************************************************************************
//  Function:  GetScriptingInfo
//
//  Purpose:
//    Return a new ScriptingPluginInfo for the Slice plot.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:50 PST 2006
//
// ****************************************************************************
extern "C" ScriptingOperatorPluginInfo* GetScriptingInfo()
{
    return new SliceScriptingPluginInfo;
}

// ****************************************************************************
// Method: SliceScriptingPluginInfo::InitializePlugin
//
// Purpose: 
//   Calls the initialization function for the plugin.
//
// Arguments:
//   subj    : A pointer to the plugin's state object.
//   data    : A pointer to data to be used by the observer function.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:50 PST 2006
//
// Modifications:
//   
// ****************************************************************************

void
SliceScriptingPluginInfo::InitializePlugin(AttributeSubject *subj,
    void *data)
{
    PySliceAttributes_StartUp((SliceAttributes *)subj, data);
}

// ****************************************************************************
// Method: SliceScriptingPluginInfo::GetMethodTable
//
// Purpose: 
//   Returns a pointer to the plugin's Python method table. These methods are
//   added to the top-level visit module's methods.
//
// Arguments:
//   nMethods : Returns the number of methods in the method table.
//
// Returns:    A pointer to the method table.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:50 PST 2006
//
// Modifications:
//   
// ****************************************************************************

void *
SliceScriptingPluginInfo::GetMethodTable(int *nMethods)
{
    return PySliceAttributes_GetMethodTable(nMethods);
}

// ****************************************************************************
// Method: SliceScriptingPluginInfo::TypesMatch
//
// Purpose: 
//   Returns whether or not the input PyObject is Slice plot attributes.
//
// Arguments:
//   pyobject : A PyObject cast to void*.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:50 PST 2006
//
// Modifications:
//   
// ****************************************************************************

bool
SliceScriptingPluginInfo::TypesMatch(void *pyobject)
{
    return PySliceAttributes_Check((PyObject *)pyobject);
}

// ****************************************************************************
// Method: SliceScriptingPluginInfo::GetLogString
//
// Purpose: 
//   Gets a string representation of the current attributes.
//
// Arguments:
//   val : Whether or not to log state information.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:50 PST 2006
//
// Modifications:
//   
// ****************************************************************************

char *
SliceScriptingPluginInfo::GetLogString()
{
    std::string s(PySliceAttributes_GetLogString());
    char *v = new char[s.size() + 1];
    strcpy(v, s.c_str());
    return v;
}

// ****************************************************************************
// Method: SliceScriptingPluginInfo::SetDefaults
//
// Purpose: 
//   Used to set the default values for a plugin's state object.
//
// Arguments:
//   atts : The new state.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:50 PST 2006
//
// Modifications:
//   
// ****************************************************************************

void
SliceScriptingPluginInfo::SetDefaults(const AttributeSubject *atts)
{
    PySliceAttributes_SetDefaults((const SliceAttributes *)atts);
}
