// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <AMRPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(AMR,Engine)

// ****************************************************************************
//  Method: AMREnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a AMR writer.
//
//  Returns:    A AMR writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
AMREnginePluginInfo::GetWriter(void)
{
    return NULL;
}

