// ************************************************************************* //
//  File: GDALPluginInfo.C
// ************************************************************************* //

#include <GDALPluginInfo.h>

#include <visit-config.h>
#if defined(__APPLE__)
extern "C" const char *GDALVisItPluginVersion = VERSION;
#else
extern "C" const char *VisItPluginVersion = VERSION;
#endif

#if defined(__APPLE__)
#define GetGeneralInfo GDAL_GetGeneralInfo
#endif

// ****************************************************************************
//  Function:  GetGeneralInfo
//
//  Purpose:
//    Return a new GeneralPluginInfo for the GDAL database.
//
//  Programmer:  whitlocb -- generated by xml2info
//  Creation:    Tue Sep 6 11:53:39 PDT 2005
//
// ****************************************************************************
extern "C" GeneralDatabasePluginInfo* GetGeneralInfo()
{
    return new GDALGeneralPluginInfo;
}

// ****************************************************************************
//  Method: GDALGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the database plugin.
//
//  Returns:    A pointer to the name of the database plugin.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Tue Sep 6 11:53:39 PDT 2005
//
// ****************************************************************************

char *
GDALGeneralPluginInfo::GetName() const
{
    return "GDAL";
}

// ****************************************************************************
//  Method: GDALGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the database plugin.
//
//  Returns:    A pointer to the version of the database plugin.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Tue Sep 6 11:53:39 PDT 2005
//
// ****************************************************************************

char *
GDALGeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: GDALGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the database plugin.
//
//  Returns:    A pointer to the id of the database plugin.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Tue Sep 6 11:53:39 PDT 2005
//
// ****************************************************************************

char *
GDALGeneralPluginInfo::GetID() const
{
    return "GDAL_1.0";
}
// ****************************************************************************
//  Method: GDALGeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Tue Sep 6 11:53:39 PDT 2005
//
// ****************************************************************************

bool
GDALGeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
// ****************************************************************************
//  Method: GDALGeneralPluginInfo::HasWriter
//
//  Purpose:
//    Return true if this plugin has a database writer.
//
//  Returns:    true/false
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Tue Sep 6 11:53:39 PDT 2005
//
// ****************************************************************************

bool
GDALGeneralPluginInfo::HasWriter() const
{
    return false;
}
