// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ************************************************************************* //
//                       avtWavefrontOBJWriter.C                             //
// ************************************************************************* //

#include <avtWavefrontOBJWriter.h>

#include <vector>

#include <vtkAlgorithm.h>
#include <vtkAppendPolyData.h>
#include <vtkDataSet.h>
#include <vtkGeometryFilter.h>
#include <vtkDataSetWriter.h>
#include <vtkPolyDataReader.h>
#include <vtkPolyDataWriter.h>
#include <vtkCharArray.h>
#include <vtkPolyData.h>
#include <vtkTriangleFilter.h>
#include <DBOptionsAttributes.h>
#include <avtDatabaseMetaData.h>
#include <vtkImageData.h>
#include <vtkFloatArray.h>
#include <vtkPointData.h>
#include <avtColorTables.h>
#include <ColorTableAttributes.h>
#include <ColorControlPointList.h>
#include <ColorControlPoint.h>

#include <avtDatabaseMetaData.h>
#include <DebugStream.h>
#include <avtParallelContext.h>
#include <avtDatasetFileWriter.h>
#include <vtkPNGWriter.h>

using     std::string;
using     std::vector;


// ****************************************************************************
//  Method: avtWavefrontOBJWriter constructor
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Apr 16 08:33:21 PDT 2013
// 
//  Modifications:
//    Justin Privitera, Fri Nov  3 15:25:32 PDT 2023
//    Now takes options.
// 
//    Justin Privitera, Tue Nov 28 17:31:40 PST 2023
//    Grab whether or not we want the color table inverted.
// 
//    Justin Privitera, Mon Aug 10 15:22:35 PDT 2026
//    Handle min, max, below color, above color, and toggles for these options.
//
// ****************************************************************************

avtWavefrontOBJWriter::avtWavefrontOBJWriter(const DBOptionsAttributes *atts)
{
    doColor = atts->GetBool("Output colors");
    colorTable = atts->GetString("Color table");
    if (colorTable.empty())
    {
        colorTable = avtColorTables::Instance()->GetDefaultContinuousColorTable();
    }
    invertCT = atts->GetBool("Invert color table");
    useMin = atts->GetBool("Use minimum");
    minValue = atts->GetDouble("Minimum");
    useMax = atts->GetBool("Use maximum");
    maxValue = atts->GetDouble("Maximum");
    useBelowMinColor = atts->GetBool("Use color for values < min");
    {
        int red, green, blue, alpha;
        atts->GetColor("Color for values < min", red, green, blue, alpha);
        belowMinColor = ColorAttribute(red, green, blue, alpha);
    }
    useAboveMaxColor = atts->GetBool("Use color for values > max");
    {
        int red, green, blue, alpha;
        atts->GetColor("Color for values > max", red, green, blue, alpha);
        aboveMaxColor = ColorAttribute(red, green, blue, alpha);
    }
}

// ****************************************************************************
//  Method: avtWavefrontOBJWriter::OpenFile
//
//  Purpose:
//      Does no actual work.  Just records the stem name for the files.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Apr 16 08:33:21 PDT 2013
//
// ****************************************************************************

void
avtWavefrontOBJWriter::OpenFile(const string &stemname, int numblocks)
{
    stem = stemname;
}


// ****************************************************************************
//  Method: avtWavefrontOBJWriter::WriteHeaders
//
//  Purpose:
//      Writes out a VisIt file to tie the WavefrontOBJ files together.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Apr 16 08:33:21 PDT 2013
//
// ****************************************************************************

void
avtWavefrontOBJWriter::WriteHeaders(const avtDatabaseMetaData *md,
                                    const vector<string> &scalars,
                                    const vector<string> &vectors,
                                    const vector<string> &materials)
{
    // WRITE OUT HEADER INFO
}


// ****************************************************************************
//  Method: avtWavefrontOBJWriter::WriteChunk
//
//  Purpose:
//      This writes out one chunk of an avtDataset.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Apr 16 08:33:21 PDT 2013
//
//  Modifications:
//    Brad Whitlock, Tue Sep  8 17:04:07 PDT 2015
//    Rely on base class for geometry consolidation. This method will only
//    be called on group leaders.
// 
//    Justin Privitera, Fri Nov  3 15:25:32 PDT 2023
//    Added ability to write out mtllib and texture.
// 
//    Justin Privitera, Mon Aug 10 15:22:35 PDT 2026
//    Send min, max, below color, above color, and toggles to the dataset file
//    writer and be more careful about null color tables and memory leaks.
//
// ****************************************************************************

void
avtWavefrontOBJWriter::WriteChunk(vtkDataSet *ds, int chunk)
{
    std::string filename;
    if(writeContext.GroupSize() > 1)
    {
        char ext[20];
        snprintf(ext, 20, ".%d.obj", writeContext.GroupRank());
        filename = stem + ext;
    }
    else
    {
        filename = stem + ".obj";
    }

    if (doColor)
    {
        // We don't have color tables that have this many control points,
        // so this should be a good choice for the number of colors.
        const int ncolors = 256;

        std::string textureFilename = stem + ".png";

        avtDatasetFileWriter::WriteOBJFile(ds, // dataset to write
                                           filename.c_str(), // filename
                                           nullptr, // label
                                           true, // YES writeMTL
                                           true, // YES MTLHasTex
                                           textureFilename, // name of texture file,
                                           ncolors, // number of pixels in the texture
                                           useMin, // whether or not we should use a min
                                           minValue, // the min value
                                           useMax, // whether or not we should use a max
                                           maxValue, // the max value
                                           useBelowMinColor, // the color to use below min
                                           useAboveMaxColor); // the color to use above max

        vtkImageData *image = GetColorTable(ncolors);
        if (image != nullptr)
        {
            vtkImageWriter *writer = vtkPNGWriter::New();
            writer->SetFileName(textureFilename.c_str());
            writer->SetInputData(image);
            writer->Write();
            writer->Delete();
            image->Delete();
        }
    }
    else
    {
        avtDatasetFileWriter::WriteOBJFile(ds, // dataset to write
                                           filename.c_str(), // filename
                                           nullptr); // label
    }
}

// ****************************************************************************
//  Method: avtWavefrontOBJWriter::CloseFile
//
//  Purpose:
//      Closes the file.  This does nothing in this case.
//
//  Programmer: pugmire -- generated by xml2avt
//  Creation:   Tue Apr 16 08:33:21 PDT 2013
//
// ****************************************************************************

void
avtWavefrontOBJWriter::CloseFile(void)
{
}

// ****************************************************************************
// Method: avtWavefrontOBJWriter::CreateTrianglePolyData
//
// Purpose:
//   Tell VisIt's export that we'll want triangles.
//
// Returns:    True
//
// Programmer: Brad Whitlock
// Creation:   Tue Sep  8 17:00:23 PDT 2015
//
// Modifications:
//
// ****************************************************************************

bool
avtWavefrontOBJWriter::CreateTrianglePolyData() const
{
    return true;
}

// ****************************************************************************
//  Method: avtWavefrontOBJWriter::GetCombineMode
//
//  Purpose:
//     Provides a hint to the export mechanism to tell it how to combine data.
//
//  Note: We combine geometry because WavefrontOBJ tools will want 1 file.
//
//  Programmer: Brad Whitlock
//  Creation:   Tue Sep  8 15:36:45 PDT 2015
//
// ****************************************************************************

avtDatabaseWriter::CombineMode
avtWavefrontOBJWriter::GetCombineMode(const std::string &) const
{
    return CombineAll;
}

//****************************************************************************
// Method:  avtWavefrontOBJWriter::GetColorTable()
//
// Purpose:
//   This function is creating a vtkImageData which contains a 1D strip of
//   pixels representing the selected color table. A vtkImageData is needed
//   to present to the vtkPNGWriter so that it can write out the texture
//   for the OBJ file.
//
// Programmer:  Justin Privitera
// Creation:    11/03/23
//
// Modifications:
//    Justin Privitera, Mon Nov 27 14:57:17 PST 2023
//    I added extra pixels on either end of the color table to act as padding
//    so that texture coordinates do not fall off the ends (and wrap around).
// 
//    Justin Privitera, Tue Nov 28 17:31:40 PST 2023
//    We now handle the inverted color table case.
//
//****************************************************************************

vtkImageData *
avtWavefrontOBJWriter::GetColorTable(const int ncolors)
{
    const ColorTableAttributes *colorTables = avtColorTables::Instance()->GetColorTables();
    const ColorControlPointList *table = colorTables->GetColorControlPoints(colorTable);

    if (! table)
    {
        colorTable = avtColorTables::Instance()->GetDefaultContinuousColorTable();
        table = colorTables->GetColorControlPoints(colorTable);
        if (! table)
        {
            return nullptr;
        }
    }

    unsigned char rgb[ncolors * 3];
    
    table->GetColors(rgb, ncolors);

    vtkImageData *imageData = vtkImageData::New();

    // let's say we have 5 colors and the upper color is U and the lower color is L.
    // then our texture will look like this:
    // 0012344UULL
    // the first and last colors are duplicated, as are the upper and lower colors
    // we duplicate the first and last colors to prevent texture wrapping from
    // harming our colors. If a value in a plot is at the minimum value, then it
    // will map to a texture coordinate of 0.0, which will cause texture wrapping
    // to color it a blend of the color at position 0.0 and 1.0. If a texture coordinate
    // is on a pixel boundary, it gets the colors of both pixels on either side of
    // the boundary. So we pad the ends so that max and min values will get the correct
    // color. We also include duplicated upper and lower colors so that there is no
    // blending when those colors are selected.

    // TODO EXPOSE NCOLORS AS AN OPTION

    // we have the duplicated end pixels plus the 2 pixels for below lower bound and
    // the 2 pixels for above upper bound
    constexpr int num_extra_pixels = 6;
    const int total_num_pixels = ncolors + num_extra_pixels;

    // VTK extents are inclusive
    // hence x: [0, total_num_pixels - 1], y: [0, 0], z: [0, 0]
    imageData->SetExtent(0, total_num_pixels - 1, // x goes from 0 to total_num_pixels - 1
                         0, 0, // no variation in y
                         0, 0); // no variation in z
    imageData->SetSpacing(1., 1., 1.);
    imageData->SetOrigin(0., 0., 0.);
    imageData->AllocateScalars(VTK_UNSIGNED_CHAR, 3);
    unsigned char *pixels = static_cast<unsigned char *>(imageData->GetScalarPointer(0, 0, 0));
    unsigned char *ipixel = pixels;

    auto set_pixel = [&ipixel](unsigned char r, unsigned char g, unsigned char b)
    {
        ipixel[0] = r;
        ipixel[1] = g;
        ipixel[2] = b;
        ipixel += 3;
    };

    if (invertCT)
    {
        // the first extra pixel will get the same color as the first real pixel
        const int last_index = ncolors * 3 - 3;
        set_pixel(rgb[last_index], rgb[last_index + 1], rgb[last_index + 2]);

        // iterate through the colors in reverse
        for (int i = ncolors * 3 - 3; i >= 0; i -= 3)
        {
            set_pixel(rgb[i], rgb[i + 1], rgb[i + 2]);
        }

        // the second (and last) extra pixel will get the same color as the last real pixel
        set_pixel(rgb[0], rgb[1], rgb[2]);
    }
    else
    {
        // the first extra pixel will get the same color as the first real pixel
        set_pixel(rgb[0], rgb[1], rgb[2]);

        // iterate through the colors
        for (int i = 0; i < ncolors * 3; i += 3)
        {
            set_pixel(rgb[i], rgb[i + 1], rgb[i + 2]);
        }

        // the second (and last) extra pixel will get the same color as the last real pixel
        const int last_index = ncolors * 3 - 3;
        set_pixel(rgb[last_index], rgb[last_index + 1], rgb[last_index + 2]);
    }

    unsigned char below_color[3];
    below_color[0] = static_cast<unsigned char>(belowMinColor.Red());
    below_color[1] = static_cast<unsigned char>(belowMinColor.Green());
    below_color[2] = static_cast<unsigned char>(belowMinColor.Blue());

    unsigned char above_color[3];
    above_color[0] = static_cast<unsigned char>(aboveMaxColor.Red());
    above_color[1] = static_cast<unsigned char>(aboveMaxColor.Green());
    above_color[2] = static_cast<unsigned char>(aboveMaxColor.Blue());

    // below min color
    set_pixel(below_color[0], below_color[1], below_color[2]);
    set_pixel(below_color[0], below_color[1], below_color[2]);

    // above max color
    set_pixel(above_color[0], above_color[1], above_color[2]);
    set_pixel(above_color[0], above_color[1], above_color[2]);

    return imageData;
}