#include <CosmosPluginInfo.h>

#if defined(__APPLE__)
#define GetEngineInfo Cosmos_GetEngineInfo
#endif

// ****************************************************************************
//  Function:  GetEngineInfo
//
//  Purpose:
//    Return a new EnginePluginInfo for the Cosmos database.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Tue Feb 22 14:35:19 PST 2005
//
// ****************************************************************************
extern "C" EngineDatabasePluginInfo* GetEngineInfo()
{
    return new CosmosEnginePluginInfo;
}

// ****************************************************************************
//  Method: CosmosCommonPluginInfo::GetWriter
//
//  Purpose:
//      Sets up a Cosmos writer.
//
//  Returns:    A Cosmos writer.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Tue Feb 22 14:35:19 PST 2005
//
// ****************************************************************************
avtDatabaseWriter *
CosmosEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

