This chapter shows all the attributes that can be set to
control the behavior of VisIt. The attributes themselves are
not documented, but their names are usually quite explanatory. When
an attribute can have values from a given list of options, the default
option is printed and the other available options are printed
in a column beneath in italic.

The listing is ordered in alphabetical ordering of the
name of the attribute set. For each set the function that will provide
you with these attributes is printed in italic.

\newpage

