/*****************************************************************************
*
* Copyright (c) 2000 - 2008, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400142
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <PyavtSILMetaData.h>
#include <ObserverToCallback.h>
#include <snprintf.h>
#include <PyavtSILCollectionMetaData.h>

// ****************************************************************************
// Module: PyavtSILMetaData
//
// Purpose: 
//   Contains SIL metadata attributes
//
// Note:       Autogenerated by xml2python. Do not modify by hand!
//
// Programmer: xml2python
// Creation:   Wed Mar 14 16:08:17 PST 2007
//
// ****************************************************************************

//
// This struct contains the Python type information and a avtSILMetaData.
//
struct avtSILMetaDataObject
{
    PyObject_HEAD
    avtSILMetaData *data;
    bool        owns;
    PyObject   *parent;
};

//
// Internal prototypes
//
static PyObject *NewavtSILMetaData(int);

std::string
PyavtSILMetaData_ToString(const avtSILMetaData *atts, const char *prefix)
{
    std::string str; 
    char tmpStr[1000]; 

    SNPRINTF(tmpStr, 1000, "%smeshName = \"%s\"\n", prefix, atts->meshName.c_str());
    str += tmpStr;
    { // new scope
        int index = 0;
        // Create string representation of collections from atts.
        for(AttributeGroupVector::const_iterator pos = atts->GetCollections().begin(); pos != atts->GetCollections().end(); ++pos, ++index)
        {
            const avtSILCollectionMetaData *current = (const avtSILCollectionMetaData *)(*pos);
            SNPRINTF(tmpStr, 1000, "GetCollections(%d).", index);
            std::string objPrefix(prefix + std::string(tmpStr));
            str += PyavtSILCollectionMetaData_ToString(current, objPrefix.c_str());
        }
        if(index == 0)
            str += "#collections does not contain any avtSILCollectionMetaData objects.\n";
    }
    {   const intVector &classIds = atts->classIds;
        SNPRINTF(tmpStr, 1000, "%sclassIds = (", prefix);
        str += tmpStr;
        for(int i = 0; i < classIds.size(); ++i)
        {
            SNPRINTF(tmpStr, 1000, "%d", classIds[i]);
            str += tmpStr;
            if(i < classIds.size() - 1)
            {
                SNPRINTF(tmpStr, 1000, ", ");
                str += tmpStr;
            }
        }
        SNPRINTF(tmpStr, 1000, ")\n");
        str += tmpStr;
    }
    {   const intVector &classDisjointFlags = atts->classDisjointFlags;
        SNPRINTF(tmpStr, 1000, "%sclassDisjointFlags = (", prefix);
        str += tmpStr;
        for(int i = 0; i < classDisjointFlags.size(); ++i)
        {
            SNPRINTF(tmpStr, 1000, "%d", classDisjointFlags[i]);
            str += tmpStr;
            if(i < classDisjointFlags.size() - 1)
            {
                SNPRINTF(tmpStr, 1000, ", ");
                str += tmpStr;
            }
        }
        SNPRINTF(tmpStr, 1000, ")\n");
        str += tmpStr;
    }
    SNPRINTF(tmpStr, 1000, "%stheStorageChunkClassId = %d\n", prefix, atts->theStorageChunkClassId);
    str += tmpStr;
    return str;
}

static PyObject *
avtSILMetaData_Notify(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    obj->data->Notify();
    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
avtSILMetaData_SetMeshName(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;

    char *str;
    if(!PyArg_ParseTuple(args, "s", &str))
        return NULL;

    // Set the meshName in the object.
    obj->data->meshName = std::string(str);

    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
avtSILMetaData_GetMeshName(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    PyObject *retval = PyString_FromString(obj->data->meshName.c_str());
    return retval;
}

static PyObject *
avtSILMetaData_GetCollections(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    int index;
    if(!PyArg_ParseTuple(args, "i", &index))
        return NULL;
    if(index < 0 || index >= obj->data->GetCollections().size())
    {
        char msg[200];
        if(obj->data->GetCollections().size() == 0)
            SNPRINTF(msg, 200, "The index is invalid because collections is empty.");
        else
            SNPRINTF(msg, 200, "The index is invalid. Use index values in: [0, %d).", obj->data->GetCollections().size());
        PyErr_SetString(PyExc_IndexError, msg);
        return NULL;
    }

    // Since the new object will point to data owned by the this object,
    // we need to increment the reference count.
    Py_INCREF(self);

    PyObject *retval = PyavtSILCollectionMetaData_Wrap(&obj->data->GetCollections(index));
    // Set the object's parent so the reference to the parent can be decref'd
    // when the child goes out of scope.
    PyavtSILCollectionMetaData_SetParent(retval, self);

    return retval;
}

PyObject *
avtSILMetaData_GetNumCollections(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    return PyInt_FromLong((long)obj->data->GetCollections().size());
}

PyObject *
avtSILMetaData_AddCollections(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    PyObject *element = NULL;
    if(!PyArg_ParseTuple(args, "O", &element))
        return NULL;
    if(!PyavtSILCollectionMetaData_Check(element))
    {
        char msg[400];
        SNPRINTF(msg, 400, "The AddCollections method only accepts avtSILCollectionMetaData objects.");
        PyErr_SetString(PyExc_TypeError, msg);
        return NULL;
    }
    avtSILCollectionMetaData *newData = PyavtSILCollectionMetaData_FromPyObject(element);
    obj->data->AddCollections(*newData);
    obj->data->SelectCollections();
    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
avtSILMetaData_Remove_One_Collections(PyObject *self, int index)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    // Remove in the AttributeGroupVector instead of calling RemoveCollections() because we don't want to delete the object; just remove it.
    AttributeGroupVector &atts = obj->data->GetCollections();
    AttributeGroupVector::iterator pos = atts.begin();
    // Iterate through the vector "index" times. 
    for(int i = 0; i < index; ++i)
        ++pos;

    // If pos is still a valid iterator, remove that element.
    if(pos != atts.end())
    {
        // NOTE: Leak the object since other Python objects may reference it. Ideally,
        // we would put the object into some type of pool to be cleaned up later but
        // this will do for now.
        //
        // delete *pos;
        atts.erase(pos);
    }

    obj->data->SelectCollections();
    Py_INCREF(Py_None);
    return Py_None;
}

PyObject *
avtSILMetaData_RemoveCollections(PyObject *self, PyObject *args)
{
    int index;
    if(!PyArg_ParseTuple(args, "i", &index))
        return NULL;
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    if(index < 0 || index >= obj->data->GetNumCollections())
    {
        PyErr_SetString(PyExc_IndexError, "Index out of range");
        return NULL;
    }

    return avtSILMetaData_Remove_One_Collections(self, index);
}

PyObject *
avtSILMetaData_ClearCollections(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    int n = obj->data->GetNumCollections();
    for(int i = 0; i < n; ++i)
    {
        avtSILMetaData_Remove_One_Collections(self, 0);
        Py_DECREF(Py_None);
    }
    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
avtSILMetaData_SetClassIds(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;

    intVector  &vec = obj->data->classIds;
    PyObject   *tuple;
    if(!PyArg_ParseTuple(args, "O", &tuple))
        return NULL;

    if(PyTuple_Check(tuple))
    {
        vec.resize(PyTuple_Size(tuple));
        for(int i = 0; i < PyTuple_Size(tuple); ++i)
        {
            PyObject *item = PyTuple_GET_ITEM(tuple, i);
            if(PyFloat_Check(item))
                vec[i] = int(PyFloat_AS_DOUBLE(item));
            else if(PyInt_Check(item))
                vec[i] = int(PyInt_AS_LONG(item));
            else if(PyLong_Check(item))
                vec[i] = int(PyLong_AsLong(item));
            else
                vec[i] = 0;
        }
    }
    else if(PyFloat_Check(tuple))
    {
        vec.resize(1);
        vec[0] = int(PyFloat_AS_DOUBLE(tuple));
    }
    else if(PyInt_Check(tuple))
    {
        vec.resize(1);
        vec[0] = int(PyInt_AS_LONG(tuple));
    }
    else if(PyLong_Check(tuple))
    {
        vec.resize(1);
        vec[0] = int(PyLong_AsLong(tuple));
    }
    else
        return NULL;

    // Mark the classIds in the object as modified.
    obj->data->SelectAll();

    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
avtSILMetaData_GetClassIds(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    // Allocate a tuple the with enough entries to hold the classIds.
    const intVector &classIds = obj->data->classIds;
    PyObject *retval = PyTuple_New(classIds.size());
    for(int i = 0; i < classIds.size(); ++i)
        PyTuple_SET_ITEM(retval, i, PyInt_FromLong(long(classIds[i])));
    return retval;
}

static PyObject *
avtSILMetaData_SetClassDisjointFlags(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;

    intVector  &vec = obj->data->classDisjointFlags;
    PyObject   *tuple;
    if(!PyArg_ParseTuple(args, "O", &tuple))
        return NULL;

    if(PyTuple_Check(tuple))
    {
        vec.resize(PyTuple_Size(tuple));
        for(int i = 0; i < PyTuple_Size(tuple); ++i)
        {
            PyObject *item = PyTuple_GET_ITEM(tuple, i);
            if(PyFloat_Check(item))
                vec[i] = int(PyFloat_AS_DOUBLE(item));
            else if(PyInt_Check(item))
                vec[i] = int(PyInt_AS_LONG(item));
            else if(PyLong_Check(item))
                vec[i] = int(PyLong_AsLong(item));
            else
                vec[i] = 0;
        }
    }
    else if(PyFloat_Check(tuple))
    {
        vec.resize(1);
        vec[0] = int(PyFloat_AS_DOUBLE(tuple));
    }
    else if(PyInt_Check(tuple))
    {
        vec.resize(1);
        vec[0] = int(PyInt_AS_LONG(tuple));
    }
    else if(PyLong_Check(tuple))
    {
        vec.resize(1);
        vec[0] = int(PyLong_AsLong(tuple));
    }
    else
        return NULL;

    // Mark the classDisjointFlags in the object as modified.
    obj->data->SelectAll();

    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
avtSILMetaData_GetClassDisjointFlags(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    // Allocate a tuple the with enough entries to hold the classDisjointFlags.
    const intVector &classDisjointFlags = obj->data->classDisjointFlags;
    PyObject *retval = PyTuple_New(classDisjointFlags.size());
    for(int i = 0; i < classDisjointFlags.size(); ++i)
        PyTuple_SET_ITEM(retval, i, PyInt_FromLong(long(classDisjointFlags[i])));
    return retval;
}

static PyObject *
avtSILMetaData_SetTheStorageChunkClassId(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;

    int ival;
    if(!PyArg_ParseTuple(args, "i", &ival))
        return NULL;

    // Set the theStorageChunkClassId in the object.
    obj->data->theStorageChunkClassId = (int)ival;

    Py_INCREF(Py_None);
    return Py_None;
}

static PyObject *
avtSILMetaData_GetTheStorageChunkClassId(PyObject *self, PyObject *args)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)self;
    PyObject *retval = PyInt_FromLong(long(obj->data->theStorageChunkClassId));
    return retval;
}



static struct PyMethodDef avtSILMetaData_methods[] = {
    {"Notify", avtSILMetaData_Notify, METH_VARARGS},
    {"SetMeshName", avtSILMetaData_SetMeshName, METH_VARARGS},
    {"GetMeshName", avtSILMetaData_GetMeshName, METH_VARARGS},
    {"GetCollections", avtSILMetaData_GetCollections, METH_VARARGS},
    {"GetNumCollections", avtSILMetaData_GetNumCollections, METH_VARARGS},
    {"AddCollections", avtSILMetaData_AddCollections, METH_VARARGS},
    {"RemoveCollections", avtSILMetaData_RemoveCollections, METH_VARARGS},
    {"ClearCollections", avtSILMetaData_ClearCollections, METH_VARARGS},
    {"SetClassIds", avtSILMetaData_SetClassIds, METH_VARARGS},
    {"GetClassIds", avtSILMetaData_GetClassIds, METH_VARARGS},
    {"SetClassDisjointFlags", avtSILMetaData_SetClassDisjointFlags, METH_VARARGS},
    {"GetClassDisjointFlags", avtSILMetaData_GetClassDisjointFlags, METH_VARARGS},
    {"SetTheStorageChunkClassId", avtSILMetaData_SetTheStorageChunkClassId, METH_VARARGS},
    {"GetTheStorageChunkClassId", avtSILMetaData_GetTheStorageChunkClassId, METH_VARARGS},
    {NULL, NULL}
};

//
// Type functions
//

static void
avtSILMetaData_dealloc(PyObject *v)
{
   avtSILMetaDataObject *obj = (avtSILMetaDataObject *)v;
   if(obj->parent != 0)
       Py_DECREF(obj->parent);
   if(obj->owns)
       delete obj->data;
}

static int
avtSILMetaData_compare(PyObject *v, PyObject *w)
{
    avtSILMetaData *a = ((avtSILMetaDataObject *)v)->data;
    avtSILMetaData *b = ((avtSILMetaDataObject *)w)->data;
    return (*a == *b) ? 0 : -1;
}

static PyObject *
avtSILMetaData_getattr(PyObject *self, char *name)
{
    if(strcmp(name, "meshName") == 0)
        return avtSILMetaData_GetMeshName(self, NULL);
    if(strcmp(name, "collections") == 0)
        return avtSILMetaData_GetCollections(self, NULL);
    if(strcmp(name, "classIds") == 0)
        return avtSILMetaData_GetClassIds(self, NULL);
    if(strcmp(name, "classDisjointFlags") == 0)
        return avtSILMetaData_GetClassDisjointFlags(self, NULL);
    if(strcmp(name, "theStorageChunkClassId") == 0)
        return avtSILMetaData_GetTheStorageChunkClassId(self, NULL);

    return Py_FindMethod(avtSILMetaData_methods, self, name);
}

static int
avtSILMetaData_setattr(PyObject *self, char *name, PyObject *args)
{
    // Create a tuple to contain the arguments since all of the Set
    // functions expect a tuple.
    PyObject *tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(tuple, 0, args);
    Py_INCREF(args);
    bool retval = false;

    if(strcmp(name, "meshName") == 0)
        retval = (avtSILMetaData_SetMeshName(self, tuple) != NULL);
    else if(strcmp(name, "classIds") == 0)
        retval = (avtSILMetaData_SetClassIds(self, tuple) != NULL);
    else if(strcmp(name, "classDisjointFlags") == 0)
        retval = (avtSILMetaData_SetClassDisjointFlags(self, tuple) != NULL);
    else if(strcmp(name, "theStorageChunkClassId") == 0)
        retval = (avtSILMetaData_SetTheStorageChunkClassId(self, tuple) != NULL);

    Py_DECREF(tuple);
    return retval ? 0 : -1;
}

static int
avtSILMetaData_print(PyObject *v, FILE *fp, int flags)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)v;
    fprintf(fp, "%s", PyavtSILMetaData_ToString(obj->data, "").c_str());
    return 0;
}

PyObject *
avtSILMetaData_str(PyObject *v)
{
    avtSILMetaDataObject *obj = (avtSILMetaDataObject *)v;
    return PyString_FromString(PyavtSILMetaData_ToString(obj->data,"").c_str());
}

//
// The doc string for the class.
//
static char *avtSILMetaData_Purpose = "Contains SIL metadata attributes";

//
// The type description structure
//
static PyTypeObject avtSILMetaDataType =
{
    //
    // Type header
    //
    PyObject_HEAD_INIT(&PyType_Type)
    0,                                   // ob_size
    "avtSILMetaData",                    // tp_name
    sizeof(avtSILMetaDataObject),        // tp_basicsize
    0,                                   // tp_itemsize
    //
    // Standard methods
    //
    (destructor)avtSILMetaData_dealloc,  // tp_dealloc
    (printfunc)avtSILMetaData_print,     // tp_print
    (getattrfunc)avtSILMetaData_getattr, // tp_getattr
    (setattrfunc)avtSILMetaData_setattr, // tp_setattr
    (cmpfunc)avtSILMetaData_compare,     // tp_compare
    (reprfunc)0,                         // tp_repr
    //
    // Type categories
    //
    0,                                   // tp_as_number
    0,                                   // tp_as_sequence
    0,                                   // tp_as_mapping
    //
    // More methods
    //
    0,                                   // tp_hash
    0,                                   // tp_call
    (reprfunc)avtSILMetaData_str,        // tp_str
    0,                                   // tp_getattro
    0,                                   // tp_setattro
    0,                                   // tp_as_buffer
    Py_TPFLAGS_CHECKTYPES,               // tp_flags
    avtSILMetaData_Purpose,              // tp_doc
    0,                                   // tp_traverse
    0,                                   // tp_clear
    0,                                   // tp_richcompare
    0                                    // tp_weaklistoffset
};

//
// Helper functions for object allocation.
//

static avtSILMetaData *defaultAtts = 0;
static avtSILMetaData *currentAtts = 0;

static PyObject *
NewavtSILMetaData(int useCurrent)
{
    avtSILMetaDataObject *newObject;
    newObject = PyObject_NEW(avtSILMetaDataObject, &avtSILMetaDataType);
    if(newObject == NULL)
        return NULL;
    if(useCurrent && currentAtts != 0)
        newObject->data = new avtSILMetaData(*currentAtts);
    else if(defaultAtts != 0)
        newObject->data = new avtSILMetaData(*defaultAtts);
    else
        newObject->data = new avtSILMetaData;
    newObject->owns = true;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

static PyObject *
WrapavtSILMetaData(const avtSILMetaData *attr)
{
    avtSILMetaDataObject *newObject;
    newObject = PyObject_NEW(avtSILMetaDataObject, &avtSILMetaDataType);
    if(newObject == NULL)
        return NULL;
    newObject->data = (avtSILMetaData *)attr;
    newObject->owns = false;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

///////////////////////////////////////////////////////////////////////////////
//
// Interface that is exposed to the VisIt module.
//
///////////////////////////////////////////////////////////////////////////////

PyObject *
avtSILMetaData_new(PyObject *self, PyObject *args)
{
    int useCurrent = 0;
    if (!PyArg_ParseTuple(args, "i", &useCurrent))
    {
        if (!PyArg_ParseTuple(args, ""))
            return NULL;
        else
            PyErr_Clear();
    }

    return (PyObject *)NewavtSILMetaData(useCurrent);
}

//
// Plugin method table. These methods are added to the visitmodule's methods.
//
static PyMethodDef avtSILMetaDataMethods[] = {
    {"avtSILMetaData", avtSILMetaData_new, METH_VARARGS},
    {NULL,      NULL}        /* Sentinel */
};

static Observer *avtSILMetaDataObserver = 0;

std::string
PyavtSILMetaData_GetLogString()
{
    std::string s("avtSILMetaData = avtSILMetaData()\n");
    if(currentAtts != 0)
        s += PyavtSILMetaData_ToString(currentAtts, "avtSILMetaData.");
    return s;
}

static void
PyavtSILMetaData_CallLogRoutine(Subject *subj, void *data)
{
    avtSILMetaData *atts = (avtSILMetaData *)subj;
    typedef void (*logCallback)(const std::string &);
    logCallback cb = (logCallback)data;

    if(cb != 0)
    {
        std::string s("avtSILMetaData = avtSILMetaData()\n");
        s += PyavtSILMetaData_ToString(currentAtts, "avtSILMetaData.");
        cb(s);
    }
}

void
PyavtSILMetaData_StartUp(avtSILMetaData *subj, void *data)
{
    if(subj == 0)
        return;

    currentAtts = subj;
    PyavtSILMetaData_SetDefaults(subj);

    //
    // Create the observer that will be notified when the attributes change.
    //
    if(avtSILMetaDataObserver == 0)
    {
        avtSILMetaDataObserver = new ObserverToCallback(subj,
            PyavtSILMetaData_CallLogRoutine, (void *)data);
    }

}

void
PyavtSILMetaData_CloseDown()
{
    delete defaultAtts;
    defaultAtts = 0;
    delete avtSILMetaDataObserver;
    avtSILMetaDataObserver = 0;
}

PyMethodDef *
PyavtSILMetaData_GetMethodTable(int *nMethods)
{
    *nMethods = 1;
    return avtSILMetaDataMethods;
}

bool
PyavtSILMetaData_Check(PyObject *obj)
{
    return (obj->ob_type == &avtSILMetaDataType);
}

avtSILMetaData *
PyavtSILMetaData_FromPyObject(PyObject *obj)
{
    avtSILMetaDataObject *obj2 = (avtSILMetaDataObject *)obj;
    return obj2->data;
}

PyObject *
PyavtSILMetaData_New()
{
    return NewavtSILMetaData(0);
}

PyObject *
PyavtSILMetaData_Wrap(const avtSILMetaData *attr)
{
    return WrapavtSILMetaData(attr);
}

void
PyavtSILMetaData_SetParent(PyObject *obj, PyObject *parent)
{
    avtSILMetaDataObject *obj2 = (avtSILMetaDataObject *)obj;
    obj2->parent = parent;
}

void
PyavtSILMetaData_SetDefaults(const avtSILMetaData *atts)
{
    if(defaultAtts)
        delete defaultAtts;

    defaultAtts = new avtSILMetaData(*atts);
}

