#!/bin/sh
dname="visit_data_files"

# Accept 'force' argument
force=0
if [ "$(echo $1 | grep -i force)" ]; then
    force=1
fi

# Check we're in the right place
if [ ! -e silo_pdb_test_data/globe.silo ]; then
    echo "Ensure you are running this from top-level data directory"
    echo "and that you have git-lfs pull'ed the reqired archives"
    echo "and that those archives have been expanded"
    exit 1
fi

# Make a destination directory for the files.
if [ -e $dname ]; then
    if [ $force -eq 1 ]; then
        rm -rf $dname
    else
        echo "There appears to already be a directory named \"$dname\" here."
        echo "Please remove that first."
        exit 1
    fi
fi
mkdir $dname

# Remove any old tarball
if [ -e $dname.tar.gz ]; then
    if [ $force -eq 1 ]; then
        rm -rf $dname.tar.gz
    else
        echo "There appears to already be a directory named \"$dname.tar.gz\" here."
        echo "Please remove that first."
        exit 1
    fi
fi

cd $dname

# Copy protein databank data files
cp ../ProteinDataBank_test_data/1NTS.pdb .
cp ../ProteinDataBank_test_data/1UZ9.pdb .
cp ../ProteinDataBank_test_data/crotamine.pdb .

# Copy PDB data files.
cp ../pdb_test_data/db{A,B,C}00.pdb .

# Copy ANALYZE test data
cp ../ANALYZE_test_data/* .

# Copy Silo files
cp ../silo_pdb_test_data/bigsil.silo .
cp ../silo_pdb_test_data/csg.silo .
cp ../silo_pdb_test_data/curv2d.silo .
cp ../silo_pdb_test_data/curv2d_colmajor.silo .
cp ../silo_pdb_test_data/curv3d.silo .
cp ../silo_pdb_test_data/curv3d_colmajor.silo .
cp ../silo_pdb_test_data/emptydomains.silo .
cp ../silo_pdb_test_data/fullframe.silo .
cp ../silo_pdb_test_data/galaxy0000.silo .
cp ../silo_pdb_test_data/ghost1.silo .
cp ../silo_pdb_test_data/global_node.silo .
cp ../silo_pdb_test_data/globe.silo .
cp ../silo_pdb_test_data/globe_mat0.silo .
cp ../silo_pdb_test_data/globe_matcolors.silo .
cp ../silo_pdb_test_data/lowfrac.silo .
cp ../silo_pdb_test_data/meshorigin.silo .
cp ../silo_pdb_test_data/multi_curv2d.silo .
cp ../silo_pdb_test_data/multi_curv3d.silo .
cp ../silo_pdb_test_data/multi_point2d.silo .
cp ../silo_pdb_test_data/multi_rect2d.silo .
cp ../silo_pdb_test_data/multi_rect3d.silo .
cp ../silo_pdb_test_data/multi_ucd3d.silo .
cp ../silo_pdb_test_data/noise.silo .
cp ../silo_pdb_test_data/noise2d.silo .
cp ../silo_pdb_test_data/odd_multi.silo .
cp ../silo_pdb_test_data/one_quad.silo .
cp ../silo_pdb_test_data/poly3d.silo .
cp ../silo_pdb_test_data/quad_disk.silo .
cp ../silo_pdb_test_data/rect2d.silo .
cp ../silo_pdb_test_data/rect3d.silo .
cp ../silo_pdb_test_data/sid97.silo .
cp ../silo_pdb_test_data/specmix_quad.silo .
cp ../silo_pdb_test_data/specmix_ucd.silo .
cp ../silo_pdb_test_data/thinplane.silo .
cp ../silo_pdb_test_data/tire.silo .
cp ../silo_pdb_test_data/ucd2d.silo .
cp ../silo_pdb_test_data/ucd3d.silo .
cp ../silo_pdb_test_data/wave????.silo .
cp ../silo_pdb_test_data/wave.visit .
cp ../silo_pdb_test_data/CThead_mid.silo .
mkdir hdf5
cp ../silo_hdf5_test_data/globe.silo hdf5/.
cp ../silo_hdf5_test_data/noise.silo hdf5/.
cp ../silo_hdf5_test_data/multi_ucd3d.silo hdf5/.
cp ../silo_hdf5_test_data/csg.silo hdf5/.

# Make the tar file
cd ..
tar cvf - $dname | gzip --best > $dname.tar.gz
echo "The VisIt data distribution is done: $dname.tar.gz" 
rm -rf $dname
