// ************************************************************************* //
//                        TopologyScriptingPluginInfo.C
// ************************************************************************* //
#include <TopologyPluginInfo.h>
#include <PyTopologyAttributes.h>

#if defined(__APPLE__)
#define GetScriptingInfo Topology_GetScriptingInfo
#endif

// ****************************************************************************
//  Function:  GetScriptingInfo
//
//  Purpose:
//    Return a new ScriptingPluginInfo for the Topology plot.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:40 PDT 2006
//
// ****************************************************************************
extern "C" ScriptingPlotPluginInfo* GetScriptingInfo()
{
    return new TopologyScriptingPluginInfo;
}

// ****************************************************************************
// Method: TopologyScriptingPluginInfo::InitializePlugin
//
// Purpose: 
//   Calls the initialization function for the plugin.
//
// Arguments:
//   subj    : A pointer to the plugin's state object.
//   data    : A pointer to data to be used by the observer function.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:40 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

void
TopologyScriptingPluginInfo::InitializePlugin(AttributeSubject *subj,
    void *data)
{
    PyTopologyAttributes_StartUp((TopologyAttributes *)subj, data);
}

// ****************************************************************************
// Method: TopologyScriptingPluginInfo::GetMethodTable
//
// Purpose: 
//   Returns a pointer to the plugin's Python method table. These methods are
//   added to the top-level visit module's methods.
//
// Arguments:
//   nMethods : Returns the number of methods in the method table.
//
// Returns:    A pointer to the method table.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:40 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

void *
TopologyScriptingPluginInfo::GetMethodTable(int *nMethods)
{
    return PyTopologyAttributes_GetMethodTable(nMethods);
}

// ****************************************************************************
// Method: TopologyScriptingPluginInfo::TypesMatch
//
// Purpose: 
//   Returns whether or not the input PyObject is Topology plot attributes.
//
// Arguments:
//   pyobject : A PyObject cast to void*.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:40 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

bool
TopologyScriptingPluginInfo::TypesMatch(void *pyobject)
{
    return PyTopologyAttributes_Check((PyObject *)pyobject);
}

// ****************************************************************************
// Method: TopologyScriptingPluginInfo::GetLogString
//
// Purpose: 
//   Gets a string representation of the current attributes.
//
// Arguments:
//   val : Whether or not to log state information.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:40 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

char *
TopologyScriptingPluginInfo::GetLogString()
{
    std::string s(PyTopologyAttributes_GetLogString());
    char *v = new char[s.size() + 1];
    strcpy(v, s.c_str());
    return v;
}

// ****************************************************************************
// Method: TopologyScriptingPluginInfo::SetDefaults
//
// Purpose: 
//   Used to set the default values for a plugin's state object.
//
// Arguments:
//   atts : The new state.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Mon Jan 9 09:13:40 PDT 2006
//
// Modifications:
//   
// ****************************************************************************

void
TopologyScriptingPluginInfo::SetDefaults(const AttributeSubject *atts)
{
    PyTopologyAttributes_SetDefaults((const TopologyAttributes *)atts);
}
