// ************************************************************************* //
//  File: IndexSelectCommonPluginInfo.C
// ************************************************************************* //

#include <IndexSelectPluginInfo.h>
#include <IndexSelectAttributes.h>

// ****************************************************************************
//  Method: IndexSelectCommonPluginInfo::AllocAttributes
//
//  Purpose:
//    Return a pointer to a newly allocated attribute subject.
//
//  Returns:    A pointer to the newly allocated attribute subject.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Thu Jun 6 17:02:08 PST 2002
//
// ****************************************************************************

AttributeSubject *
IndexSelectCommonPluginInfo::AllocAttributes()
{
    return new IndexSelectAttributes;
}

// ****************************************************************************
//  Method: IndexSelectCommonPluginInfo::CopyAttributes
//
//  Purpose:
//    Copy a IndexSelect attribute subject.
//
//  Arguments:
//    to        The destination attribute subject.
//    from      The source attribute subject.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Thu Jun 6 17:02:08 PST 2002
//
// ****************************************************************************

void 
IndexSelectCommonPluginInfo::CopyAttributes(AttributeSubject *to,
    AttributeSubject *from)
{
    *((IndexSelectAttributes *) to) = *((IndexSelectAttributes *) from);
}
