#!/bin/sh
set -e
#-----------------------------------------------------------------------
#
# VISIT-INSTALL-RUN - Install the visit distributions.
#
# Author: Eric Brugger
# Date:   October 27, 2000
#
# Usage:
#    visit-install-run [-<machine name>] -v <version>
#
# Modifications from visit-install-open:
#   Brad Whitlock, Tue Mar 7 14:08:59 PST 2006
#   Added -b bank to the visit-install invokations.
#
#   Hank Childs, Wed Oct 17 16:25:14 PDT 2007
#   Add a subject line to the status e-mail.
#
#   Hank Childs, Sat May  2 13:26:51 CDT 2009
#   Change config file to "llnl_open".
#
#   Eric Brugger, Fri Nov  5 15:22:54 PDT 2010
#   I replaced yana with aztec.
#
#   Eric Brugger, Mon May 16 14:53:23 PDT 2011
#   I added glory and redsky.
#
#   Eric Brugger, Fri Aug  5 09:53:51 PDT 2011
#   I added kickit.
#
#   Eric Brugger, Tue Sep  6 14:13:59 PDT 2011
#   I added rzzeus.
#
#   Brad Whitlock, Wed Oct 12 10:01:07 PDT 2011
#   Install as llnl_open_cz or llnl_open_rz depending on machine.
#
#   Eric Brugger, Mon Jan 23 13:52:00 PST 2012
#   I added sidious.
#
#   Eric Brugger, Thu Mar  1 12:56:56 PST 2012
#   I added ubuntu1104_64.
#
#   Eric Brugger, Thu May  3 08:30:22 PDT 2012
#   I removed ellipse and xchem.  I modified hoth, kickit, sidious and
#   aztec for various reasons.  I updated the e-mail addresses.
#
#   Eric Brugger, Tue May 15 11:08:05 PDT 2012
#   I changed the name of the ubuntu 11 executable.
#
#   Eric Brugger, Wed Jun 13 08:40:31 PDT 2012
#   I added atlas and rzthriller.
#
#   Eric Brugger, Mon Jul 30 10:21:57 PDT 2012
#   I replaced atlas with prism.
#
#   Eric Brugger, Wed Sep 26 17:11:04 PDT 2012
#   I deleted prism.
#
#   Eric Brugger, Wed Nov 14 10:45:59 PST 2012
#   I deleted hoth. I made the sidious install off by default. I modified
#   the kickit installation since it is now a linux-x86_64 system instead
#   of a linux-intel system.
#
#   Eric Brugger, Tue Oct 22 11:11:01 PDT 2013
#   I removed rzthriller.
#
#   Eric Brugger, Wed Dec 10 13:32:49 PST 2014
#   I added ubuntu1404_64.
#
#   Eric Brugger, Thu Feb 19 09:14:29 PST 2015
#   I removed redsky.
#
#   Kathleen Biagas, Thu May  7 09:35:34 PDT 2015
#   Added vulcan, changed rzuseq bank to wbronze.
#
#   Eric Brugger, Thu Sep 24 09:17:41 PDT 2015
#   I removed sidious.
#
#   Eric Brugger, Tue Nov 22 16:23:56 PST 2016
#   I added quartz.
#
#   Eric Brugger, Mon Jan  9 13:50:10 PST 2017
#   I replaced aztec with surface.
#
#   Eric Brugger, Tue Feb  7 10:42:05 PST 2017
#   I added rztrona.
#
#   Eric Brugger, Fri Feb 17 12:16:04 PST 2017
#   I changed the bank for all the LLNL systems from bdivp to wbronze.
#
#   Eric Brugger, Wed Jun 21 11:23:41 PDT 2017
#   I replaced surface with cab.
#
#   Eric Brugger, Fri Sep 22 11:39:17 PDT 2017
#   I replaced rzzeus with rzalastor.
#
#   Eric Brugger, Mon Mar 19 14:21:54 PDT 2018
#   I removed the modifications to the internallauncher for toss3
#   systems. I made a change in internallauncher and customlauncher
#   that made this unnecessary.
#
#   Eric Brugger, Tue Apr  3 11:09:51 PDT 2018
#   I deleted ubuntu1104_64 and added ifyou (Fedora Core 27).
#
#   Eric Brugger, Wed Oct 17 16:56:58 PDT 2018
#   I deleted cab.
#
#   Eric Brugger, Fri Nov 30 11:11:41 PST 2018
#   I added lassen.
#
#   Eric Brugger, Fri Dec 14 11:52:47 PST 2018
#   I updated quartz for 3.0.0b.
#
#   Eric Brugger, Mon Feb 25 12:31:14 PST 2019
#   I updated rztrona for 3.0.0b and removed rzalastor.
#
#   Eric Brugger, Mon Mar  4 08:28:54 PST 2019
#   I added cooley.
#
#   Eric Brugger, Tue Mar  5 12:35:11 PST 2019
#   I added rzansel. I deleted carver and glory.
#
#   Eric Brugger, Thu Sep 26 17:28:15 PDT 2019
#   I removed special logic for installing on toss3 systems. I removed
#   ifyou and ubuntu1404_64.
#
#   Eric Brugger, Mon Jan 13 15:34:55 PST 2020
#   I removed rzuseq and vulcan.
#
#   Eric Brugger, Wed Jun  8 10:42:23 PDT 2022
#   I added logic to the quartz and rztrona installs to copy libraries
#   needed to run on toss4 systems.
#
#   Eric Brugger, Tue Jun 14 11:55:03 PDT 2022
#   I removed the logic on the quartz and rztrona installs that copies
#   the libraries needed by Qt, since those now get included by default.
#
#   Eric Brugger, Thu Feb  9 09:53:52 PST 2023
#   I modified the rztrona and rzansel installs to install versions
#   built on quartz and lassen. I modified the rztrona install to
#   copy the darshan library into the VisIt lib directory so that it
#   would run on toss4.
#
#   Eric Brugger, Fri Feb 17 09:36:29 PST 2023
#   I added poodle and rzalastor.
#
#   Eric Brugger, Mon Oct 16 14:58:42 PDT 2023
#   I removed quartz and renamed rzalastor with rzgenie. I removed
#   the "-none" option since all the machines are now off by default.
#   Turning on a machine is now done with -<machine_name> instead of
#   +<machine_name>.
#
#   Cyrus Harrison, Mon Mar 11 12:57:17 PDT 2024
#   I removed rzgenie, replaced with rzwhippet. Removed rzansel.
# 
##################################################################
# Modifications from visit-install-closed:
#   Brad Whitlock, Tue Mar 7 14:10:26 PST 2006
#   I added -b bdivp to the visit-install invokations.
#
#   Eric Brugger, Mon Apr  7 13:52:50 PDT 2008
#   Removed sc install.
#
#   Hank Childs, Sat May  2 13:26:51 CDT 2009
#   Renamed config file to llnl_closed.
#
#   Eric Brugger, Fri Nov  5 15:40:02 PDT 2010
#   Replaced hopi with inca and removed pruple.
#
#   Eric Brugger, Wed Jan  5 09:40:00 PST 2011
#   Added terminator.
#
#   Eric Brugger, Fri Mar 25 10:20:49 PDT 2011
#   Added cielo.
#
#   Eric Brugger, Mon Jul 30 10:31:10 PDT 2012
#   Added gremlin.
#
#   Eric Brugger, Wed Mar 20 11:49:58 PDT 2013
#   Deleted gremlin. Deleted terminator. Replaced termite with hitit.
#
#   Eric Brugger, Thu Jun 20 10:37:05 PDT 2013
#   I modified the hitit install since it is now an x86_64 system instead
#   of an i686 system.
#
#   Eric Brugger, Tue Jul  9 11:23:43 PDT 2013
#   I changed the gateway node to login to cielo.
#
#   Eric Brugger, Mon Nov 21 11:53:53 PST 2016
#   Deleted cielo. Added trinity.
#
#   Eric Brugger, Mon Nov 21 16:43:04 PST 2016
#   Added jade.
#
#   Eric Brugger, Mon Jan  9 13:52:57 PST 2017
#   I replaced inca with zin.
#
#   Eric Brugger, Tue Jan 17 17:12:11 PST 2017
#   I replaced hitit with winnipeg.
#
#   Eric Brugger, Fri Feb 17 12:17:29 PST 2017
#   I changed the bank for all the LLNL systems from bdivp to wbronze.
#
#   Eric Brugger, Mon Mar 19 14:23:59 PDT 2018
#   I removed the modifications to the internallauncher for toss3 
#   systems. I made a change in internallauncher and customlauncher
#   that made this unnecessary.
#
#   Eric Brugger, Mon Nov 19 15:54:23 PST 2018
#   I added shark.
#
#   Eric Brugger, Wed Mar 20 10:31:35 PDT 2019
#   I deleted zin. I added sierra. I updated jade for 3.0.0b.
#
#   Eric Brugger, Thu Sep 26 17:32:41 PDT 2019
#   I removed special logic for installing on toss3 systems.
#
#   Eric Brugger, Mon Jan 13 15:24:51 PST 2020
#   I removed shark.
#
#   Eric Brugger, Wed Jun  8 15:19:01 PDT 2022
#   I added logic to the jade install to copy libraries needed to run
#   on toss4 systems.
#
#   Eric Brugger, Tue Jun 14 11:57:11 PDT 2022
#   I removed the logic on the jade install that copies the libraries
#   needed by Qt, since those now get included by default.
#
#   Eric Brugger, Wed Nov 29 11:16:25 PST 2023
#   I removed the "-none" option since all the machines are now off by
#   default. Turning on a machine is now done with -<machine_name>
#   instead of +<machine_name>.
# 
#   Justin Privitera, Tue Mar 26 13:07:18 PDT 2024
#   Removed winnipeg, jade, trinity
#   Added magma and updated sierra.
# 
########################################################################
# Modifications:
#   Justin Privitera, Wed Sep  4 13:29:51 PDT 2024
#   The scripts visit-install-open and visit-install-closed have been
#   combined into a single script called visit-install-run. This script
#   calls the visit-install script as before.
#
#-----------------------------------------------------------------------

test=no

user=`whoami`
result_dir=/usr/workspace/visit/visit/_release_builds/

#
# Set the user e-mail address.
#
emailName=brugger1@llnl.gov
case $user in
   biagas2)
      emailName=biagas2@llnl.gov
      ;;
   kbonnell)
      emailName=biagas2@llnl.gov
      ;;
   brugger1)
      emailName=brugger1@llnl.gov
      ;;
   brugger)
      emailName=brugger1@llnl.gov
      ;;
   harrison37)
      emailName=cyrush@llnl.gov
      ;;
   cyrush)
      emailName=cyrush@llnl.gov
      ;;
   mcmiller)
      emailName=miller86@llnl.gov
      ;;
   miller)
      emailName=miller86@llnl.gov
      ;;
   justin)
      emailName=privitera1@llnl.gov
      ;;
esac

#
# Parse the execute line, providing default values for error checking.
#
kickit=false
poodle=false
lassen=false
rzwhippet=false
magma=false
sierra=false

ver=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -kickit)
         kickit=true
         shift
         ;;
      -poodle)
         poodle=true
         shift
         ;;
      -lassen)
         lassen=true
         shift
         ;;
      -rzwhippet)
         rzwhippet=true
         shift
         ;;
      -rzansel)
         rzansel=true
         shift
         ;;
      -magma)
         magma=true
         shift
         ;;
      -sierra)
         sierra=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
   esac
done

#
# Check that the version was provided.
#
if [ "$ver" = "undefined" ]
then
   echo "Usage: [-<machine name>] -v <version>"
   echo "Valid machine names:"
   echo "    kickit poodle lassen rzwhippet magma sierra"
   exit
fi

#
# Check that the visit install script is present.
#
if [ ! -e visit-install ]
then
   echo "visit-install is missing."
   exit
fi

ver2=`echo $ver | tr "." "_"`
ver=`echo $ver2 | tr "_" "."`

#
# Install on kickit.
#
rm -f kickit_install
cat <<EOF > kickit_install
#!/bin/sh
set -e
./visit-install -private -c llnl_open -g visit -b wbronze -gw -l $ver linux-x86_64-rhel7 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on kickit"          > resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin      >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.kickit
mv resultlog resultlog.kickit
EOF

if [ "$kickit" = "true" ]
then
   if [ "$test" = "no" ]
   then
      cp /home/$user/kickit/visitbuild/visit$ver2.linux-x86_64.tar.gz visit$ver2.linux-x86_64-rhel7.tar.gz
      cp /home/$user/kickit/visitbuild/visit$ver2.linux-x86_64-wmesa.tar.gz visit$ver2.linux-x86_64-rhel7-wmesa.tar.gz
      chmod 750 kickit_install;./kickit_install
   fi
fi

#
# Install on poodle.
#
rm -f poodle_install
cat <<EOF > poodle_install
#!/bin/sh
set -e
./visit-install -private -c llnl_open_cz -g visit -b wbronze -gw -l $ver linux-x86_64-poodle /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                              > resultlog 2>&1
echo "        install of visit on poodle"            >> resultlog 2>&1
echo "       ----------------------------"           >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
df -k /usr/gapps/visit                               >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin  >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "The database plugins:"                         >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.poodle
mv resultlog resultlog.poodle
EOF

if [ "$poodle" = "true" ]
then
   if [ "$test" = "no" ]
   then
      cp $result_dir/visit$ver2.linux-x86_64-poodle.tar.gz .
      chmod 750 poodle_install;./poodle_install
   fi
fi

#
# Install on lassen.
#
rm -f lassen_install
cat <<EOF > lassen_install
#!/bin/sh
set -e
./visit-install -private -c llnl_open_cz -g visit -b wbronze -gw -l $ver linux-intel-lassen /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                              > resultlog 2>&1
echo "        install of visit on lassen"            >> resultlog 2>&1
echo "       ----------------------------"           >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
df -k /usr/gapps/visit                               >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-intel/bin         >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "The database plugins:"                         >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.lassen
mv resultlog resultlog.lassen
EOF

if [ "$lassen" = "true" ]
then
   if [ "$test" = "no" ]
   then
      cp $result_dir/visit$ver2.linux-intel-lassen.tar.gz .
      chmod 750 lassen_install;./lassen_install
   fi
fi

#
# Install on rzwhippet
#
rm -f rzwhippet_install
cat <<EOF > rzwhippet_install
#!/bin/sh
set -e
./visit-install -private -c llnl_open_rz -g visit -b wbronze -gw -l $ver linux-x86_64-rzwhippet /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on rzwhippet"        > resultlog 2>&1
echo "       -----------------------------"         >> resultlog 2>&1
echo ""                                             >> resultlog 2>&1
df -k /usr/gapps/visit                              >> resultlog 2>&1
echo ""                                             >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin >> resultlog 2>&1
echo ""                                             >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                             >> resultlog 2>&1
echo "The database plugins:"                        >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.rzwhippet
mv resultlog resultlog.rzwhippet
mail -s "VisIt install ($ver): rzwhippet" $emailName < resultlog.rzwhippet
EOF

if [ "$rzwhippet" = "true" ]
then
   if [ "$test" = "no" ]
   then
     cp $result_dir/visit$ver2.linux-x86_64-rzwhippet.tar.gz .
     chmod 750 rzwhippet_install;./rzwhippet_install
   fi
fi

#
# Install on magma.
#
rm -f magma_install
cat <<EOF > magma_install
#!/bin/sh
set -e
./visit-install -private -c llnl_closed -g visit -b wbronze -gw -l $ver linux-x86_64-magma /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                              > resultlog 2>&1
echo "        install of visit on magma"              >> resultlog 2>&1
echo "       --------------------------"             >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
df -k /usr/gapps/visit                               >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-x86_64/bin  >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "The database plugins:"                         >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.magma
mv resultlog resultlog.magma
EOF

if [ "$magma" = true ]
then
   if [ "$test" = "no" ]
   then
      cp $result_dir/visit$ver2.linux-x86_64-magma.tar.gz .
      chmod 750 magma_install;./magma_install
   fi
fi

#
# Install on sierra
#
rm -f sierra_install
cat <<EOF > sierra_install
#!/bin/sh
set -e
./visit-install -private -c llnl_closed -g visit -b wbronze -gw -l $ver linux-intel-sierra /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                              > resultlog 2>&1
echo "        install of visit on sierra"            >> resultlog 2>&1
echo "       ----------------------------"           >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
df -k /usr/gapps/visit                               >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver+/linux-intel/bin         >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver+/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                              >> resultlog 2>&1
echo "The database plugins:"                         >> resultlog 2>&1
ls /usr/gapps/visit/$ver+/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver+\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
rm -f resultlog.sierra
mv resultlog resultlog.sierra
EOF

if [ "$sierra" = true ]
then
   if [ "$test" = "no" ]
   then
      cp $result_dir/visit$ver2.linux-intel-sierra.tar.gz .
      chmod 750 sierra_install;./sierra_install
   fi
fi

#
# Clean up.
#
if [ "$test" = "no" ]
then
   rm -f kickit_install poodle_install lassen_install rzwhippet_install magma_install sierra_install
fi
