// ****************************************************************************
//                               ZeusMPPluginInfo.h
// ****************************************************************************

#ifndef ZEUSMP_PLUGIN_INFO_H
#define ZEUSMP_PLUGIN_INFO_H
#include <DatabasePluginInfo.h>
#include <database_plugin_exports.h>

class avtDatabase;
class avtDatabaseWriter;

// ****************************************************************************
//  Class: ZeusMPDatabasePluginInfo
//
//  Purpose:
//    Classes that provide all the information about the ZeusMP plugin.
//    Portions are separated into pieces relevant to the appropriate
//    components of VisIt.
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 13 13:45:30 PST 2006
//
//  Modifications:
//
// ****************************************************************************

class ZeusMPGeneralPluginInfo : public virtual GeneralDatabasePluginInfo
{
  public:
    virtual char *GetName() const;
    virtual char *GetVersion() const;
    virtual char *GetID() const;
    virtual bool  EnabledByDefault() const;
    virtual bool  HasWriter() const;
};

class ZeusMPCommonPluginInfo : public virtual CommonDatabasePluginInfo, public virtual ZeusMPGeneralPluginInfo
{
  public:
    virtual DatabaseType              GetDatabaseType();
    virtual std::vector<std::string>  GetDefaultExtensions();
    virtual avtDatabase              *SetupDatabase(const char * const *list,
                                                    int nList, int nBlock);
};

class ZeusMPMDServerPluginInfo : public virtual MDServerDatabasePluginInfo, public virtual ZeusMPCommonPluginInfo
{
  public:
    // this makes compilers happy... remove if we ever have functions here
    virtual void dummy();
};

class ZeusMPEnginePluginInfo : public virtual EngineDatabasePluginInfo, public virtual ZeusMPCommonPluginInfo
{
  public:
    virtual avtDatabaseWriter        *GetWriter(void);
};

#endif
