// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <PLOT3DPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(PLOT3D,Engine)

// ****************************************************************************
//  Method: PLOT3DEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a PLOT3D writer.
//
//  Returns:    A PLOT3D writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
PLOT3DEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

