#!/bin/csh -f

echo $argv[1]
rm -f tmp

# Ones we don't know what to do with yet...

#s/<qdrawutil.h>/<QDrawutil>/g\
#s/<qobjectdefs.h>/<QObjectdefs>/g\
#s/<qobjectlist.h>/<QObjectlist>/g\
#s/<qsgistyle.h>/<QSGIstyle>/g\
#s/<qsignalslotimp.h>/<QSignalslotimp>/g\
#s/<qtable.h>/<QTable>/g\
#s/<qurloperator.h>/<QUrlOperator>/g\
#s/<qwmatrix.h>/<QWmatrix>/g\

# Do a first pass to convert header files
sed "s/<qaction.h>/<QAction>/g\
s/<qapplication.h>/<QApplication>/g\
s/<qbitmap.h>/<QBitmap>/g\
s/<qbrush.h>/<QBrush>/g\
s/<qbutton.h>/<QButton>/g\
s/<qbuttongroup.h>/<QButtonGroup>/g\
s/<qcanvas.h>/<QCanvas>/g\
s/<qcdestyle.h>/<QCDEstyle>/g\
s/<qcheckbox.h>/<QCheckBox>/g\
s/<qcolor.h>/<QColor>/g\
s/<qcolordialog.h>/<QColorDialog>/g\
s/<qcombobox.h>/<QComboBox>/g\
s/<qcursor.h>/<QCursor>/g\
s/<qdatetime.h>/<QDateTime>/g\
s/<qdatetimeedit.h>/<QDateTimeEdit>/g\
s/<qdial.h>/<QDial>/g\
s/<qdialog.h>/<QDialog>/g\
s/<qdir.h>/<QDir>/g\
s/<qdom.h>/<QDom>/g\
s/<qevent.h>/<QEvent>/g\
s/<qeventloop.h>/<QEventLoop>/g\
s/<qfile.h>/<QFile>/g\
s/<qfiledialog.h>/<QFileDialog>/g\
s/<qfileinfo.h>/<QFileInfo>/g\
s/<qfont.h>/<QFont>/g\
s/<qfontdialog.h>/<QFontDialog>/g\
s/<qfontmetrics.h>/<QFontMetrics>/g\
s/<qframe.h>/<QFrame>/g\
s/<qftp.h>/<QFtp>/g\
s/<qgrid.h>/<QWidget>/g\
s/<qgridview.h>/<QTableView>/g\
s/<qgroupbox.h>/<QGroupBox>/g\
s/<qhbox.h>/<QWidget>/g\
s/<qheader.h>/<QHeaderView>/g\
s/<qiconset.h>/<QIconSet>/g\
s/<qiconview.h>/<QListWidget>/g\
s/<qimage.h>/<QImage>/g\
s/<qinputdialog.h>/<QInputDialog>/g\
s/<qiodevice.h>/<QIODevice>/g\
s/<qlabel.h>/<QLabel>/g\
s/<qlayout.h>/<QLayout>/g\
s/<qlcdnumber.h>/<QLCDnumber>/g\
s/<qlineedit.h>/<QLineEdit>/g\
s/<qlistbox.h>/<QListWidget>/g\
s/<qlistview.h>/<QTreeView>/g\
s/<qlocale.h>/<QLocale>/g\
s/<qmainwindow.h>/<QMainWindow>/g\
s/<qmap.h>/<QMap>/g\
s/<qmenubar.h>/<QMenuBar>/g\
s/<qmessagebox.h>/<QMessageBox>/g\
s/<qmetaobject.h>/<QMetaObject>/g\
s/<qmotifstyle.h>/<QMotifStyle>/g\
s/<qnetwork.h>/<QNetwork>/g\
s/<qobject.h>/<QObject>/g\
s/<qpainter.h>/<QPainter>/g\
s/<qpalette.h>/<QPalette>/g\
s/<qpen.h>/<QPen>/g\
s/<qpixmap.h>/<QPixmap>/g\
s/<qpixmapcache.h>/<QPixmapCache>/g\
s/<qplatinumstyle.h>/<QPlatinumStyle>/g\
s/<qpointarray.h>/<QPolygon>/g\
s/<qpopupmenu.h>/<QPopupMenu>/g\
s/<qprintdialog.h>/<QPrintDialog>/g\
s/<qprinter.h>/<QPrinter>/g\
s/<qprocess.h>/<QProcess>/g\
s/<qprogressbar.h>/<QProgressBar>/g\
s/<qpushbutton.h>/<QPushButton>/g\
s/<qradiobutton.h>/<QRadioButton>/g\
s/<qscrollview.h>/<QScrollArea>/g\
s/<qsignal.h>//g\
s/<qsizepolicy.h>/<QSizePolicy>/g\
s/<qslider.h>/<QSlider>/g\
s/<qsocketnotifier.h>/<QSocketNotifier>/g\
s/<qspinbox.h>/<QSpinBox>/g\
s/<qsplitter.h>/<QSplitter>/g\
s/<qstatusbar.h>/<QStatusBar>/g\
s/<qstring.h>/<QString>/g\
s/<qstringlist.h>/<QStringList>/g\
s/<qstyle.h>/<QStyle>/g\
s/<qtabbar.h>/<QTabBar>/g\
s/<qtabwidget.h>/<QTabWidget>/g\
s/<qtextbrowser.h>/<QTextBrowser>/g\
s/<qtextedit.h>/<QTextEdit>/g\
s/<qtextstream.h>/<QTextStream>/g\
s/<qtimer.h>/<QTimer>/g\
s/<qtoolbar.h>/<QToolBar>/g\
s/<qtoolbutton.h>/<QToolButton>/g\
s/<qtooltip.h>/<QToolTip>/g\
s/<qtranslator.h>/<QTranslator>/g\
s/<qurlinfo.h>/<QUrlInfo>/g\
s/<qvaluelist.h>/<QValueList>/g\
s/<qvaluevector.h>/<QValueVector>/g\
s/<qvariant.h>/<QVariant>/g\
s/<qvbox.h>/<QWidget>/g\
s/<qvgroupbox.h>/<QVGroupBox>/g\
s/<qwidget.h>/<QWidget>/g\
s/<qwidgetfactory.h>/<QFormBuilder>/g\
s/<qwidgetlist.h>//g\
s/<qwidgetstack.h>/<QStackedWidget>/g\
s/<qwindowsstyle.h>/<QWindowsStyle>/g\
s/<qwizard.h>/<QWizard>/g\
s/<qwmatrix.h>/<QWmatrix>/g\
s/latin1()/toStdString()/g\
s/.upper()/.toUpper()/g\
s/.lower()/.toLower()/g\
s/stripWhiteSpace/trimmed/g\
s/simplifyWhiteSpace/simplified/g\
s/findRev/lastIndexOf/g\
s/QPopupMenu/QMenu/g\
s/QPointArray/QPolygon/g\
s/QMultiLineEdit/QTextEdit/g\
s/QGridView/QTableView/g\
s/QHeader/QHeaderView/g\
s/QIconView/QListWidget/g\
s/QListBox/QListWidget/g\
s/QListView/QTreeView/g\
s/QIconSet/QIcon/g\
s/colorGroup()/palette()/g\
s/QWMatrix/QMatrix/g\
s/QScrollView/QScrollArea/g" $argv[1] > tmp

mv tmp $argv[1]

