/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtXolotlFileFormat.h                           //
// ************************************************************************* //

#ifndef AVT_Xolotl_FILE_FORMAT_H
#define AVT_Xolotl_FILE_FORMAT_H

#include <avtMTSDFileFormat.h>

#include <vector>
#include <hdf5.h>

class DBOptionsAttributes;


// ****************************************************************************
//  Class: avtXolotlFileFormat
//
//  Purpose:
//      Reads in Xolotl files as a plugin to VisIt.
//
//  Programmer: js9 -- generated by xml2avt
//  Creation:   Tue Mar 22 15:09:52 PST 2016
//
// ****************************************************************************

class avtXolotlFileFormat : public avtMTSDFileFormat
{
  public:
                       avtXolotlFileFormat(const char *, DBOptionsAttributes *);
    virtual           ~avtXolotlFileFormat();

    void               Initialize();

    virtual void        GetCycles(std::vector<int> &);
    virtual void        GetTimes(std::vector<double> &);

    virtual int            GetNTimesteps(void);

    virtual const char    *GetType(void)   { return "Xolotl"; };
    virtual void           FreeUpResources(void);

    virtual vtkDataSet    *GetMesh(int, const char *);
    virtual vtkDataArray  *GetVar(int, const char *);
    virtual vtkDataArray  *GetVectorVar(int, const char *);

  protected:
    hid_t                  fileId;
    int                    nTimeStates;

    std::string            filename;

    int                    dimension;
    int                    nx, ny, nz;
    int                    hx, hy, hz;
    int                    varMaxes[5];

    std::vector<int>       isurface;
    std::vector<int>       cycleNumbers;
    std::vector<double>    times;
    std::vector<double>    network;
    std::vector<double>    oneDGrid;
    std::vector< std::vector<double> >    concentrations;
    hsize_t                networkSize;
    hsize_t                networkParams;
    hid_t                  concentrationsGroup;

    virtual void           PopulateDatabaseMetaData(avtDatabaseMetaData *, int);
    void                   PopulateHeaderGroupMetaData();
    void                   PopulateConcentrationGroupMetaData();
    void                   GetPositionsOfVariableFromCompositionTable(int *variableIndexes, const char *vn);
    static int             GroupInfo(hid_t loc_id, const char *name, const H5L_info_t *linfo, void *opdata);
};


#endif
