// ************************************************************************* //
//  File: SpheralPluginInfo.C
// ************************************************************************* //

#include <SpheralPluginInfo.h>

// ****************************************************************************
//  Function:  GetGeneralInfo
//
//  Purpose:
//    Return a new GeneralPluginInfo for the Spheral database.
//
//  Programmer:  childs -- generated by xml2info
//  Creation:    Tue Mar 11 15:53:39 PST 2003
//
// ****************************************************************************
extern "C" GeneralDatabasePluginInfo* GetGeneralInfo()
{
    return new SpheralGeneralPluginInfo;
}

// ****************************************************************************
//  Method: SpheralGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the database plugin.
//
//  Returns:    A pointer to the name of the database plugin.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Mar 11 15:53:39 PST 2003
//
// ****************************************************************************

char *
SpheralGeneralPluginInfo::GetName() const
{
    return "Spheral";
}

// ****************************************************************************
//  Method: SpheralGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the database plugin.
//
//  Returns:    A pointer to the version of the database plugin.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Mar 11 15:53:39 PST 2003
//
// ****************************************************************************

char *
SpheralGeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: SpheralGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the database plugin.
//
//  Returns:    A pointer to the id of the database plugin.
//
//  Programmer: childs -- generated by xml2info
//  Creation:   Tue Mar 11 15:53:39 PST 2003
//
// ****************************************************************************

char *
SpheralGeneralPluginInfo::GetID() const
{
    return "Spheral_1.0";
}
