#!/bin/sh

### Purpose:
#   Prints the names of all the important VisIt files.

### Modifications
#   Brad Whitlock, Mon May 22 15:25:13 PST 2000
#   Adapted to VisIt
#
#   Hank Childs, Thu Oct 19 15:05:22 PDT 2000
#   Added directory visit_vtk.
#
#   Brad Whitlock, Tue Oct 31 15:44:03 PST 2000
#   Added directory vtkqt.
#
#   Eric Brugger, Mon Mar  5 12:22:32 PST 2001
#   Added the directory plot.
#
#   Jeremy Meredith, Fri May 11 14:15:41 PDT 2001
#   Renamed plot to plots.  Added archives and plugins.
#
#   Eric Brugger, Fri Aug 31 17:17:36 PDT 2001
#   Added the SplashScreen directory.
#
#   Brad Whitlock, Mon Nov 12 17:34:34 PST 2001
#   Added visitpy directory.
#
#   Eric Brugger, Tue Feb 19 14:58:46 PST 2002
#   Added the data directory.
#
#   Jeremy Meredith, Mon Mar 11 16:49:36 PST 2002
#   Renamed SplashScreen to splashscreen.
#
#   Jeremy Meredith, Mon Jun 17 15:40:39 PDT 2002
#   Made it non-recursive on the lib directory.  This was needed
#   because of the new symlink to the installed python directories.
#
#   Brad Whitlock, Fri Jul 12 17:37:47 PST 2002
#   Added the help directory.
#
#   Brad Whitlock, Wed Aug 14 17:00:05 PST 2002
#   Added the java directory.
#
#   Jeremy Meredith, Tue Aug 27 14:50:02 PDT 2002
#   Added database plugins.
#
#   Brad Whitlock, Mon May 5 09:40:21 PDT 2003
#   Added launcher directory.
#
#   Brad Whitlock, Thu Jun 19 13:17:43 PST 2003
#   Removed splashscreen directory.
#
#   Eric Brugger, Thu Nov 20 08:30:07 PST 2003
#   Only add the help directory if -withhelp specified.
#
#   Brad Whitlock, Fri Apr 23 12:25:56 PDT 2004
#   Added winutil to the top level.
#
#   Jeremy Meredith, Tue Aug 24 21:29:45 PDT 2004
#   Added the simulation prototype.
#
#   Jeremy Meredith, Fri Dec 10 13:30:38 PST 2004
#   Added the new exe directory.
#
#   Brad Whitlock, Thu Feb 17 16:35:39 PST 2005
#   I removed the withhelp argument.

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
#for abc
#do
#   case $1 in
#      -withhelp)
#         withhelp=yes
#         shift
#         ;;
#   esac
#done

if [ ! -d engine ]; then
   echo "invoke $0 from the root of the VisIt source tree" 2>&1
   exit 1
fi

PATH="$PATH:./clearcase_bin"
(
    ./clearcase_bin/mkman --quiet --norecursive --simple .
    ./clearcase_bin/mkman --quiet --norecursive --simple ./config-site
    ./clearcase_bin/mkman --quiet --recursive --simple ./common
    ./clearcase_bin/mkman --quiet --recursive --simple ./visit_vtk
    ./clearcase_bin/mkman --quiet --recursive --simple ./engine
    ./clearcase_bin/mkman --quiet --recursive --simple ./launcher
    ./clearcase_bin/mkman --quiet --recursive --simple ./components
    ./clearcase_bin/mkman --quiet --recursive --simple ./vtkqt
    ./clearcase_bin/mkman --quiet --recursive --simple ./plots
    ./clearcase_bin/mkman --quiet --recursive --simple ./operators
    ./clearcase_bin/mkman --quiet --recursive --simple ./databases
    ./clearcase_bin/mkman --quiet --recursive --simple ./winutil
    ./clearcase_bin/mkman --quiet --recursive --simple ./viewer
    ./clearcase_bin/mkman --quiet --recursive --simple ./gui
    ./clearcase_bin/mkman --quiet --recursive --simple ./mdserver
    ./clearcase_bin/mkman --quiet --recursive --simple ./visitpy
    ./clearcase_bin/mkman --quiet --recursive --simple ./java
    ./clearcase_bin/mkman --quiet --recursive --simple ./tools
    ./clearcase_bin/mkman --quiet --recursive --simple ./sim
    ./clearcase_bin/mkman --quiet --recursive --simple ./data
    ./clearcase_bin/mkman --quiet --recursive --simple ./include
    ./clearcase_bin/mkman --quiet --recursive --simple ./bin
    ./clearcase_bin/mkman --quiet --recursive --simple ./exe
    ./clearcase_bin/mkman --quiet             --simple ./lib
    ./clearcase_bin/mkman --quiet             --simple ./help
    ./clearcase_bin/mkman --quiet --recursive --simple ./archives
    ./clearcase_bin/mkman --quiet --recursive --simple ./plugins
    ./clearcase_bin/mkman --quiet --recursive --simple ./clearcase_bin
    ./clearcase_bin/mkman --quiet --recursive --simple ./config-site
) | sort | uniq
