#!/bin/sh
ssh -x visit@hoth "/usr/atria/bin/cleartool startview visit_VOBowner_main ; /view/visit_VOBowner_main/data_vobs/VisIt/clearcase_bin/unlockrc.script `whoami` $* ; /usr/atria/bin/cleartool endview visit_VOBowner_main"
