#!/bin/sh
#-----------------------------------------------------------------------
#
# VISIT-INSTALL-CLOSED - Install the visit distributions on the closed
#                        network.
#
# Author: Eric Brugger
# Date:   February 12, 2001
#
# Usage:
#    visit-install-closed [-beta | -private] -v <version>
#
#-----------------------------------------------------------------------

test=no

user=`whoami`

#
# Parse the execute line, providing default values for error checking.
#
warp=false
sc=true
tidalwave=true
white=true
emperor=true

ver=undefined
verflag=

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
         warp=false
         sc=false
         tidalwave=false
         white=false
         emperor=false
         shift
         ;;
      -warp)
         warp=false
         shift
         ;;
      +warp)
         warp=true
         shift
         ;;
      -sc)
         sc=false
         shift
         ;;
      +sc)
         sc=true
         shift
         ;;
      -tidalwave)
         tidalwave=false
         shift
         ;;
      +tidalwave)
         tidalwave=true
         shift
         ;;
      -white)
         white=false
         shift
         ;;
      +white)
         white=true
         shift
         ;;
      -emperor)
         emperor=false
         shift
         ;;
      +emperor)
         emperor=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
      -beta)
         verflag=-beta;
         shift
         ;;
      -private)
         verflag=-private;
         shift
         ;;
   esac
done

#
# Check that the version was provided.
#
if [ $ver = undefined ]
then
   echo "Usage: [-beta | -private] [-none] [-<machine name>] -v <version>"
   exit
fi

#
# Check that the visit open configuration file is present.
#
if [ ! -e visit-config-closed ]
then
   echo "visit-config-closed is missing."
   exit
fi

ver2=`echo $ver | tr "." "_"`
ver=`echo $ver2 | tr "_" "."`

#
# Install on warp.
#
rm -f warp
cat <<EOF > warp
#!/bin/sh
cd /scratch/$user/warp/visitbuild
./visit-install $verflag -g bdiv -gw $ver irix6 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on warp"            > resultlog 2>&1
echo "       --------------------------"           >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/sgi-irix6-mips2/bin    >> resultlog 2>&1
EOF

if [ $warp = true ]
then
   if [ $test = no ]
   then
      scp -P 22 warp warp:warp_install
      ssh -p 22 warp "chmod 750 warp_install;./warp_install"
   fi
fi

#
# Install on sc.
#
rm -f sc
cat <<EOF > sc
#!/bin/sh
cd /nfs/tmp2/$user/sc/visitbuild
if [ -d /usr/gapps/visit/$ver ]
then
   ./visit-install -private -a -g bdiv -gw $ver osf1 /usr/gapps/visit > installlog 2>&1
else
   ./visit-install -private -g bdiv -gw $ver osf1 /usr/gapps/visit > installlog 2>&1
fi
rm -f resultlog
echo "        install of visit on sc"              > resultlog 2>&1
echo "       ------------------------"             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/dec-osf1-alpha/bin     >> resultlog 2>&1
EOF

if [ $sc = true ]
then
   if [ $test = no ]
   then
      scp sc sc1:sc_install
      ssh sc1 "chmod 750 sc_install;./sc_install"
   fi
fi

#
# Install on tidalwave.
#
rm -f tidalwave
cat <<EOF > tidalwave
#!/bin/sh
cd /fc/san3/$user/tidalwave/visitbuild
if [ -d /usr/gapps/visit/$ver ]
then
   ./visit-install -private -a -g bdiv -gw $ver irix6 /usr/gapps/visit > installlog 2>&1
else
   ./visit-install -private -g bdiv -gw $ver irix6 /usr/gapps/visit > installlog 2>&1
fi
rm -f resultlog
echo "        install of visit on tidalwave"       > resultlog 2>&1
echo "       -------------------------------"      >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/sgi-irix6-mips2/bin    >> resultlog 2>&1
EOF

if [ $tidalwave = true ]
then
   if [ $test = no ]
   then
      scp tidalwave tidalwave:tidalwave_install
      ssh tidalwave "chmod 750 tidalwave_install;./tidalwave_install"
   fi
fi

#
# Install on white.
#
rm -f white
cat <<EOF > white
#!/bin/sh
cd /p/gw1/$user/white/visitbuild
if [ -d /usr/gapps/visit/$ver ]
then
   ./visit-install -private -a -g bdiv -gw $ver aix /usr/gapps/visit > installlog 2>&1
else
   ./visit-install -private -g bdiv -gw $ver aix /usr/gapps/visit > installlog 2>&1
fi
rm -f resultlog
echo "        install of visit on white"           > resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/ibm-aix-pwr/bin        >> resultlog 2>&1
EOF

if [ $white = true ]
then
   if [ $test = no ]
   then
      scp white white:white_install
      ssh white "chmod 750 white_install;./white_install"
   fi
fi

#
# Install on emperor.
#
rm -f emperor
cat <<EOF > emperor
#!/bin/sh
mv visit-config-closed /usr/tmp/$user/emperor/visitbuild
cd /usr/tmp/$user/emperor/visitbuild
if [ -d /usr/gapps/visit/$ver ]
then
   ./visit-install $verflag -a -g bdiv -gw $ver linux /usr/gapps/visit > installlog 2>&1
else
   ./visit-install $verflag -g bdiv -gw $ver linux /usr/gapps/visit > installlog 2>&1
fi
mkdir /usr/gapps/visit/$ver/.visit
chmod 775 /usr/gapps/visit/$ver/.visit
chgrp visit /usr/gapps/visit/$ver/.visit
cp visit-config-closed /usr/gapps/visit/$ver/.visit/config
chmod 664 /usr/gapps/visit/$ver/.visit/config
chgrp visit /usr/gapps/visit/$ver/.visit/config
rm -f resultlog
echo "        install of visit on emperor"         > resultlog 2>&1
echo "       -----------------------------"        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-intel/bin        >> resultlog 2>&1
EOF
 
if [ $emperor = true ]
then
   if [ $test = no ]
   then
      scp emperor emperor0:emperor_install
      scp visit-config-closed emperor0:visit-config-closed
      ssh emperor0 "chmod 750 emperor_install;./emperor_install"
   fi
fi

#
# Clean up.
#
if [ $test = no ]
then
   rm -f warp sc tidalwave white emperor
fi
