#!/bin/sh
#-----------------------------------------------------------------------
#
# VISIT-INSTALL-OPEN - Install the visit distributions on the open
#                      network.
#
# Author: Eric Brugger
# Date:   October 27, 2000
#
# Usage:
#    visit-install-open [-beta | -private | -public] -v <version>
#
# Modifications:
#   Brad Whitlock, Wed Dec 14 09:50:55 PDT 2005
#   I fixed some errors that prevented other users from installing on
#   mcr and thunder.
#
#   Brad Whitlock, Tue Mar 7 14:08:59 PST 2006
#   Added -b bank to the visit-install invokations.
#
#-----------------------------------------------------------------------

test=no

user=`whoami`

#
# Set the user e-mail address.
#
emailName=brugger1@llnl.gov
case $user in
   kbonnell)
      emailName=bonnell2@llnl.gov
      ;;
   brugger)
      emailName=brugger1@llnl.gov
      ;;
   childs)
      emailName=childs3@llnl.gov
      ;;
   mcmiller)
      emailName=miller86@llnl.gov
      ;;
   miller)
      emailName=miller86@llnl.gov
      ;;
   whitlocb)
      emailName=whitlock2@llnl.gov
      ;;
esac

#
# Parse the execute line, providing default values for error checking.
#
hoth=true
sunspot=true
quad=true
gps=true
berg=true
up=true
pengra=true
thunder=true
vertex=true

ver=undefined
verflag=-private

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
         hoth=false
         sunspot=false
         quad=false
         gps=false
         berg=false
         up=false
         pengra=false
         thunder=false
         vertex=false
         shift
         ;;
      -hoth)
         hoth=false
         shift
         ;;
      +hoth)
         hoth=true
         shift
         ;;
      -sunspot)
         sunspot=false
         shift
         ;;
      +sunspot)
         sunspot=true
         shift
         ;;
      -quad)
         quad=false
         shift
         ;;
      +quad)
         quad=true
         shift
         ;;
      -gps)
         gps=false
         shift
         ;;
      +gps)
         gps=true
         shift
         ;;
      -berg)
         berg=false
         shift
         ;;
      +berg)
         berg=true
         shift
         ;;
      -up)
         up=false
         shift
         ;;
      +up)
         up=true
         shift
         ;;
      -pengra)
         pengra=false
         shift
         ;;
      +pengra)
         pengra=true
         shift
         ;;
      -thunder)
         thunder=false
         shift
         ;;
      +thunder)
         thunder=true
         shift
         ;;
      -vertex)
         vertex=false
         shift
         ;;
      +vertex)
         vertex=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
      -beta)
         verflag=-beta
         shift
         ;;
      -private)
         verflag=-private
         shift
         ;;
      -public)
         verflag=;
         shift
         ;;
   esac
done

#
# Check that the version was provided.
#
if [ $ver = undefined ]
then
   echo "Usage: [-beta | -private | -public] [-none] [-<machine name>] -v <version>"
   exit
fi

#
# Check that the visit install script is present.
#
if [ ! -e visit-install ]
then
   echo "visit-install is missing."
   exit
fi

ver2=`echo $ver | tr "." "_"`
ver=`echo $ver2 | tr "_" "."`

#
# Install on hoth.
#
rm -f hoth
cat <<EOF > hoth
#!/bin/sh
./visit-install -r -private -c open -g visit -b bdivp -gw -l $ver linux_rhel3 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on hoth"            > resultlog 2>&1
echo "       --------------------------"           >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-intel/bin        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $hoth = true ]
then
   if [ $test = no ]
   then
      scp hoth:/scratch/$user/hoth/visitbuild/visit$ver2.linux.tar.gz visit$ver2.linux_rhel3.tar.gz
      scp visit$ver2.linux_rhel3.tar.gz kickit:
      scp visit-install kickit:
      scp hoth kickit:hoth_install
      ssh kickit "chmod 750 hoth_install;./hoth_install"
   fi
fi

#
# Install on sunspot.
#
rm -f sunspot
cat <<EOF > sunspot
#!/bin/sh
./visit-install $verflag -c open -g visit -b bdivp -gw -l $ver sunos5 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on sunspot"         > resultlog 2>&1
echo "       -----------------------------"        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/sun4-sunos5-sparc/bin  >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/sun4-sunos5-sparc\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $sunspot = true ]
then
   if [ $test = no ]
   then
      scp sunspot:/export/scratch/$user/sunspot/visitbuild/visit$ver2.sunos5.tar.gz .
      scp visit$ver2.sunos5.tar.gz kickit:
      scp visit-install kickit:
      scp sunspot kickit:sunspot_install
      ssh kickit "chmod 750 sunspot_install;./sunspot_install"
   fi
fi

#
# Install on quad.
#
rm -f quad
cat <<EOF > quad
#!/bin/sh
./visit-install -r -private -c open -g visit -b bdivp -gw -l $ver irix6 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on quad"            > resultlog 2>&1
echo "       --------------------------"           >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/sgi-irix6-mips2/bin    >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/sgi-irix6-mips2/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/sgi-irix6-mips2/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/sgi-irix6-mips2/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/sgi-irix6-mips2/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/sgi-irix6-mips2\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $quad = true ]
then
   if [ $test = no ]
   then
      scp quad:/usr/tmp/$user/quad/visitbuild/visit$ver2.irix6.tar.gz .
      scp visit$ver2.irix6.tar.gz gps15:
      scp visit-install gps15:
      scp quad gps15:quad_install
      ssh gps15 "chmod 750 quad_install;./quad_install"
   fi
fi

#
# Install on gps.
#
rm -f gps
cat <<EOF > gps
#!/bin/sh
./visit-install -private -c open -g visit -b bdivp -gw -l $ver osf1 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on gps"             > resultlog 2>&1
echo "       -------------------------"            >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/dec-osf1-alpha/bin     >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/dec-osf1-alpha\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $gps = true ]
then
   if [ $test = no ]
   then
      scp gps15:/nfs/tmp0/$user/gps/visitbuild/visit$ver2.osf1.tar.gz .
      scp visit$ver2.osf1.tar.gz gps15:
      scp visit-install gps15:
      scp gps gps15:gps_install
      ssh gps15 "chmod 750 gps_install;./gps_install"
   fi
fi

#
# Install on berg.
#
rm -f berg
cat <<EOF > berg
#!/bin/sh
./visit-install -private -c open -g visit -b bdivp -gw -l $ver aix /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on berg"            > resultlog 2>&1
echo "       --------------------------"           >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/ibm-aix-pwr/bin        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/ibm-aix-pwr\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $berg = true ]
then
   if [ $test = no ]
   then
      scp berg:/g/g17/$user/berg/visitbuild/visit$ver2.aix.tar.gz .
      scp visit$ver2.aix.tar.gz gps15:
      scp visit-install gps15:
      scp berg gps15:berg_install
      ssh gps15 "chmod 750 berg_install;./berg_install"
   fi
fi

#
# Install on up.
#
rm -f up
cat <<EOF > up
#!/bin/sh
./visit-install -private -c open -g visit -b bdivp -gw -l $ver aix64-xlc /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on up"              >> resultlog 2>&1
echo "       ------------------------"             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/bin  >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/ibm-aix-pwr64-xlc\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $up = true ]
then
   if [ $test = no ]
   then
      scp up:/p/gup1/$user/up/visitbuild/visit$ver2.aix64-xlc.tar.gz .
      scp visit$ver2.aix64-xlc.tar.gz gps15:
      scp visit-install gps15:
      scp up gps15:up_install
      ssh gps15 "chmod 750 up_install;./up_install"
   fi
fi

#
# Install on pengra.
#
rm -f pengra
cat <<EOF > pengra
#!/bin/sh
./visit-install -private -c open -g visit -b bdivp -gw -l $ver linux_chaos /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on pengra"          > resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-intel/bin        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $pengra = true ]
then
   if [ $test = no ]
   then
      scp pengra1:/usr/tmp/$user/pengra/visitbuild/visit$ver2.linux.tar.gz visit$ver2.linux_chaos.tar.gz
      scp visit$ver2.linux_chaos.tar.gz gps15:
      scp visit-install gps15:
      scp pengra gps15:pengra_install
      ssh gps15 "chmod 750 pengra_install;./pengra_install"
   fi
fi

#
# Install on thunder.
#
rm -f thunder
cat <<EOF > thunder
#!/bin/sh
./visit-install -private -c open -g visit -b bdivp -gw -l $ver linux-ia64 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on thunder"         > resultlog 2>&1
echo "       -----------------------------"        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-ia64/bin         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-ia64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-ia64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-ia64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-ia64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-ia64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $thunder = true ]
then
   if [ $test = no ]
   then
      scp thunder2:/usr/tmp/$user/thunder/visitbuild/visit$ver2.linux-ia64.tar.gz .
      scp visit$ver2.linux-ia64.tar.gz gps15:
      scp visit-install gps15:
      scp thunder gps15:thunder_install
      ssh gps15 "chmod 750 thunder_install;./thunder_install"
   fi
fi

#
# Install on vertex.
#
rm -f vertex
cat <<EOF > vertex
#!/bin/sh
./visit-install -private -c open -g visit -b bdivp -gw -l $ver linux-x86_64 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo "        install of visit on vertex"          > resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-x86_64/bin       >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-x86_64/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-x86_64/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-x86_64/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-x86_64/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-x86_64\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $vertex = true ]
then
   if [ $test = no ]
   then
      scp vertex2:/usr/tmp/$user/vertex/visitbuild/visit$ver2.linux-x86_64.tar.gz .
      scp visit$ver2.linux-x86_64.tar.gz gps15:
      scp visit-install gps15:
      scp vertex gps15:vertex_install
      ssh gps15 "chmod 750 vertex_install;./vertex_install"
   fi
fi

#
# Clean up.
#
if [ $test = no ]
then
   rm -f hoth sunspot quad gps berg up pengra thunder vertex
fi
