#!/bin/sh
#-----------------------------------------------------------------------
#
# VISIT-INSTALL-CLOSED - Install the visit distributions on the closed
#                        network.
#
# Author: Eric Brugger
# Date:   February 12, 2001
#
# Usage:
#    visit-install-closed [-beta | -private | -public] -v <version>
#
# Modifications:
#   Brad Whitlock, Tue Mar 7 14:10:26 PST 2006
#   I added -b bdivp to the visit-install invokations.
#
#-----------------------------------------------------------------------

test=no

user=`whoami`

#
# Parse the execute line, providing default values for error checking.
#
crier=true
hitit=true
sunset=true
sc=true
ice=true
purple=true
lilac=true
gauss=true

ver=undefined
verflag=-private

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
         crier=false
         hitit=false
         sunset=false
         sc=false
         ice=false
         purple=false
         lilac=false
         gauss=false
         shift
         ;;
      -crier)
         crier=false
         shift
         ;;
      +crier)
         crier=true
         shift
         ;;
      -hitit)
         hitit=false
         shift
         ;;
      +hitit)
         hitit=true
         shift
         ;;
      -sunset)
         sunset=false
         shift
         ;;
      +sunset)
         sunset=true
         shift
         ;;
      -sc)
         sc=false
         shift
         ;;
      +sc)
         sc=true
         shift
         ;;
      -ice)
         ice=false
         shift
         ;;
      +ice)
         ice=true
         shift
         ;;
      -purple)
         purple=false
         shift
         ;;
      +purple)
         purple=true
         shift
         ;;
      -lilac)
         lilac=false
         shift
         ;;
      +lilac)
         lilac=true
         shift
         ;;
      -gauss)
         gauss=false
         shift
         ;;
      +gauss)
         gauss=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
      -beta)
         verflag=-beta
         shift
         ;;
      -private)
         verflag=-private
         shift
         ;;
      -public)
         verflag=
         shift
         ;;
   esac
done

#
# Check that the version was provided.
#
if [ $ver = undefined ]
then
   echo "Usage: [-beta | -private | -public] [-none] [-<machine name>] -v <version>"
   exit
fi

#
# Check that the visit install script is present.
#
if [ ! -e visit-install ]
then
   echo "visit-install is missing."
   exit
fi

ver2=`echo $ver | tr "." "_"`
ver=`echo $ver2 | tr "_" "."`

#
# Install on crier.
#
rm -f crier
cat <<EOF > crier
#!/bin/sh
./visit-install -r -private -c closed -g visit -b bdivp -gw -l $ver linux_rhel3 /usr/gapps/visit > installlog 2>&1
mv /usr/gapps/visit/$ver/linux-intel /usr/gapps/visit/$ver/linux-intel-2.4.29
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on crier"           >> resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-intel-2.4.29/bin >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-intel-2.4.29/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-intel-2.4.29/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-intel-2.4.29/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-intel-2.4.29/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-intel-2.4.29\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.crier
EOF

if [ $crier = true ]
then
   if [ $test = no ]
   then
      scp -P 22 crier:/gscratch/$user/crier/visitbuild/visit$ver2.linux.tar.gz visit$ver2.linux_rhel3.tar.gz
      scp -P 22 visit$ver2.linux_rhel3.tar.gz crier:
      scp -P 22 visit-install crier:
      scp -P 22 crier crier:crier_install
      ssh -p 22 crier "chmod 750 crier_install;./crier_install"
   fi
fi

#
# Install on hitit.
#
rm -f hitit
cat <<EOF > hitit
#!/bin/sh
./visit-install -private -c closed -g visit -b bdivp -gw -l $ver linux_redhat7 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on hitit"           >> resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-intel/bin        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.hitit
EOF

if [ $hitit = true ]
then
   if [ $test = no ]
   then
      scp -P 22 hitit:/gscratch/$user/hitit/visitbuild/visit$ver2.linux.tar.gz visit$ver2.linux_redhat7.tar.gz
      scp visit$ver2.linux_redhat7.tar.gz sunset:
      scp visit-install sunset:
      scp hitit sunset:hitit_install
      ssh sunset "chmod 750 hitit_install;./hitit_install"
   fi
fi

#
# Install on sunset.
#
rm -f sunset
cat <<EOF > sunset
#!/bin/sh
./visit-install $verflag -c closed -g visit -b bdivp -gw -l $ver sunos5 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on sunset"          >> resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/sun4-sunos5-sparc/bin  >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/sun4-sunos5-sparc/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/sun4-sunos5-sparc\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.sunset
EOF

if [ $sunset = true ]
then
   if [ $test = no ]
   then
      scp sunset:/export/scratch/$user/sunset/visitbuild/visit$ver2.sunos5.tar.gz .
      scp visit$ver2.sunos5.tar.gz sunset:
      scp visit-install sunset:
      scp sunset sunset:sunset_install
      ssh sunset "chmod 750 sunset_install;./sunset_install"
   fi
fi

#
# Install on sc.
#
rm -f sc
cat <<EOF > sc
#!/bin/sh
./visit-install -r -private -c closed -g visit -b bdivp -gw -l $ver osf1 /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on sc"              >> resultlog 2>&1
echo "       ------------------------"             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/dec-osf1-alpha/bin     >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/dec-osf1-alpha/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/dec-osf1-alpha\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.sc
EOF

if [ $sc = true ]
then
   if [ $test = no ]
   then
      scp sc8:/nfs/tmp0/$user/sc/visitbuild/visit$ver2.osf1.tar.gz .
      scp visit$ver2.osf1.tar.gz lilac3:
      scp visit-install lilac3:
      scp sc lilac3:sc_install
      ssh lilac3 "chmod 750 sc_install;./sc_install"
   fi
fi

#
# Install on ice.
#
rm -f ice
cat <<EOF > ice
#!/bin/sh
./visit-install -private -c closed -g visit -b bdivp -gw -l $ver aix /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on ice"             >> resultlog 2>&1
echo "       -------------------------"            >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/ibm-aix-pwr/bin        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/ibm-aix-pwr/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/ibm-aix-pwr\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.ice
EOF

if [ $ice = true ]
then
   if [ $test = no ]
   then
      scp ice:/p/gi1/$user/ice/visitbuild/visit$ver2.aix.tar.gz .
      scp visit$ver2.aix.tar.gz lilac3:
      scp visit-install lilac3:
      scp ice lilac3:ice_install
      ssh lilac3 "chmod 750 ice_install;./ice_install"
   fi
fi

#
# Install on purple.
#
rm -f purple
cat <<EOF > purple
#!/bin/sh
./visit-install -private -c closed -g visit -b bdivp -gw -l $ver aix64-xlc /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on purple"          >> resultlog 2>&1
echo "       ----------------------------"         >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/bin  >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/ibm-aix-pwr64-xlc/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/ibm-aix-pwr64-xlc\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.purple
EOF

if [ $purple = true ]
then
   if [ $test = no ]
   then
      scp purple:/p/gscratch3/$user/purple/visitbuild/visit$ver2.aix64-xlc.tar.gz .
      scp visit$ver2.aix64-xlc.tar.gz lilac3:
      scp visit-install lilac3:
      scp purple lilac3:purple_install
      ssh lilac3 "chmod 750 purple_install;./purple_install"
   fi
fi

#
# Install on lilac.
#
rm -f lilac
cat <<EOF > lilac
#!/bin/sh
./visit-install -private -c closed -g visit -b bdivp -gw -l $ver linux_chaos /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on lilac"           >> resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-intel/bin        >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-intel/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-intel/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-intel\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.lilac
EOF
 
if [ $lilac = true ]
then
   if [ $test = no ]
   then
      scp lilac3:/usr/tmp/$user/lilac/visitbuild/visit$ver2.linux.tar.gz visit$ver2.linux_chaos.tar.gz
      scp visit$ver2.linux_chaos.tar.gz lilac3:
      scp visit-install lilac3:
      scp lilac lilac3:lilac_install
      ssh lilac3 "chmod 750 lilac_install;./lilac_install"
   fi
fi

#
# Install on gauss.
#
rm -f gauss
cat <<EOF > gauss
#!/bin/sh
./visit-install $verflag -c closed -g visit -b bdivp -gw -l $ver linux-x86_64-ib /usr/gapps/visit > installlog 2>&1
rm -f resultlog
echo ""                                            > resultlog 2>&1
echo "        install of visit on gauss"           >> resultlog 2>&1
echo "       ---------------------------"          >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/visit                             >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/visit/$ver/linux-x86_64-ib/bin    >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "number of database plugins = "\`ls /usr/gapps/visit/$ver/linux-x86_64-ib/plugins/databases/libI* | wc -l\` >> resultlog 2>&1
echo "number of operator plugins = "\`ls /usr/gapps/visit/$ver/linux-x86_64-ib/plugins/operators/libI* | wc -l\` >> resultlog 2>&1
echo "number of plot plugins = "\`ls /usr/gapps/visit/$ver/linux-x86_64-ib/plugins/plots/libI* | wc -l\` >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
echo "The database plugins:"                       >> resultlog 2>&1
ls /usr/gapps/visit/$ver/linux-x86_64-ib/plugins/databases/libI* | sed "s/\/usr\/gapps\/visit\/$ver\/linux-x86_64-ib\/plugins\/databases\/libI//" | sed "s/Database.so//" >> resultlog 2>&1
mv resultlog resultlog.gauss
EOF

if [ $gauss = true ]
then
   if [ $test = no ]
   then
      scp gauss2:/usr/tmp/$user/gauss/visitbuild/visit$ver2.linux-x86_64-ib.tar.gz .
      scp visit$ver2.linux-x86_64-ib.tar.gz lilac3:
      scp visit-install lilac3:
      scp gauss lilac3:gauss_install
      ssh lilac3 "chmod 750 gauss_install;./gauss_install"
   fi
fi

#
# Clean up.
#
if [ $test = no ]
then
   rm -f hitit sunset sc ice purple lilac gauss
fi
