// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: BoxPluginInfo.h
// ****************************************************************************

#ifndef BOX_PLUGIN_INFO_H
#define BOX_PLUGIN_INFO_H
#include <OperatorPluginInfo.h>
#include <operator_plugin_exports.h>

class BoxAttributes;

// ****************************************************************************
//  Class: BoxPluginInfo
//
//  Purpose:
//    Five classes that provide all the information about an Box operator
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
//  Modifications:
//
// ****************************************************************************

class BoxGeneralPluginInfo : public virtual GeneralOperatorPluginInfo
{
  public:
    virtual const char *GetName() const;
    virtual const char *GetVersion() const;
    virtual const char *GetID() const;
    virtual bool  EnabledByDefault() const;
    virtual const char *GetCategoryName() const;
};

class BoxCommonPluginInfo : public virtual CommonOperatorPluginInfo, public virtual BoxGeneralPluginInfo
{
  public:
    virtual AttributeSubject *AllocAttributes();
    virtual void CopyAttributes(AttributeSubject *to, AttributeSubject *from);
};

class BoxGUIPluginInfo : public virtual GUIOperatorPluginInfo, public virtual BoxCommonPluginInfo
{
  public:
    virtual QString *GetMenuName() const;
    virtual QvisPostableWindowObserver *CreatePluginWindow(int type,
        AttributeSubject *attr, const QString &caption, const QString &shortName,
        QvisNotepadArea *notepad);
    virtual const char **XPMIconData() const;
};

class BoxViewerEnginePluginInfo : public virtual ViewerEngineOperatorPluginInfo, public virtual BoxCommonPluginInfo
{
  public:
    virtual AttributeSubject *GetClientAtts();
    virtual AttributeSubject *GetDefaultAtts();
    virtual void SetClientAtts(AttributeSubject *atts);
    virtual void GetClientAtts(AttributeSubject *atts);

    virtual void InitializeOperatorAtts(AttributeSubject *atts,
                                        const avtPlotMetaData &plot,
                                        const bool fromDefault);
    virtual void UpdateOperatorAtts(AttributeSubject *atts,
                                    const avtPlotMetaData &plot);
    virtual const char *GetMenuName() const;

    static void InitializeGlobalObjects();
  private:
    static BoxAttributes *defaultAtts;
    static BoxAttributes *clientAtts;
};

class BoxViewerPluginInfo : public virtual ViewerOperatorPluginInfo, public virtual BoxViewerEnginePluginInfo
{
  public:
    virtual const char **XPMIconData() const;
};

class BoxEnginePluginInfo : public virtual EngineOperatorPluginInfo, public virtual BoxViewerEnginePluginInfo
{
  public:
    virtual avtPluginFilter *AllocAvtPluginFilter();
};

class BoxScriptingPluginInfo : public virtual ScriptingOperatorPluginInfo, public virtual BoxCommonPluginInfo
{
  public:
    virtual void InitializePlugin(AttributeSubject *subj, void *data);
    virtual void *GetMethodTable(int *nMethods);
    virtual bool TypesMatch(void *pyobject);
    virtual char *GetLogString();
    virtual void SetDefaults(const AttributeSubject *atts);
};

#endif
