// ************************************************************************* //
//  File: BoundaryPluginInfo.C
// ************************************************************************* //

#include <BoundaryPluginInfo.h>
#include <BoundaryAttributes.h>

#if defined(__APPLE__)
#define GetGeneralInfo Boundary_GetGeneralInfo
#endif

// ****************************************************************************
//  Function:  GetGeneralInfo
//
//  Purpose:
//    Return a new GeneralPluginInfo for the Boundary plot.
//
//  Programmer:  meredith -- generated by xml2info
//  Creation:    Wed May 7 01:03:30 PDT 2003
//
// ****************************************************************************
extern "C" GeneralPlotPluginInfo* GetGeneralInfo()
{
    return new BoundaryGeneralPluginInfo;
}

// ****************************************************************************
//  Method: BoundaryGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the plot plugin.
//
//  Returns:    A pointer to the name of the plot plugin.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Wed May 7 01:03:30 PDT 2003
//
// ****************************************************************************

char *
BoundaryGeneralPluginInfo::GetName() const
{
    return "Boundary";
}

// ****************************************************************************
//  Method: BoundaryGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the plot plugin.
//
//  Returns:    A pointer to the version of the plot plugin.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Wed May 7 01:03:30 PDT 2003
//
// ****************************************************************************

char *
BoundaryGeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: BoundaryGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the plot plugin.
//
//  Returns:    A pointer to the id of the plot plugin.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Wed May 7 01:03:30 PDT 2003
//
// ****************************************************************************

char *
BoundaryGeneralPluginInfo::GetID() const
{
    return "Boundary_1.0";
}
