// ************************************************************************* //
//  File: BoundaryEnginePluginInfo.C
// ************************************************************************* //

#include <BoundaryPluginInfo.h>
#include <avtBoundaryPlot.h>

// ****************************************************************************
//  Function:  GetEngineInfo
//
//  Purpose:
//    Return a new EnginePluginInfo for the Boundary plot.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Wed May 7 01:03:30 PDT 2003
//
// ****************************************************************************
extern "C" EnginePlotPluginInfo* GetEngineInfo()
{
    return new BoundaryEnginePluginInfo;
}

// ****************************************************************************
//  Method: BoundaryEnginePluginInfo::AllocAvtPlot
//
//  Purpose:
//    Return a pointer to a newly allocated avt plot.
//
//  Returns:    A pointer to the newly allocated avt plot.
//
//  Programmer: meredith -- generated by xml2info
//  Creation:   Wed May 7 01:03:30 PDT 2003
//
// ****************************************************************************

avtPlot *
BoundaryEnginePluginInfo::AllocAvtPlot()
{
    return new avtBoundaryPlot;
}
