// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ************************************************************************* //
//                          avtExtrudedVolOptions.h                          //
// ************************************************************************* //

#ifndef AVT_ExtrudedVol_OPTIONS_H
#define AVT_ExtrudedVol_OPTIONS_H

class DBOptionsAttributes;

#include <string>


// ****************************************************************************
//  Functions: avtExtrudedVolOptions
//
//  Purpose:
//      Creates the options for  ExtrudedVol readers and/or writers.
//
//  Programmer: childs -- generated by xml2avt
//  Creation:   Fri May 18 17:52:04 PST 2007
//
// ****************************************************************************

DBOptionsAttributes *GetExtrudedVolReadOptions(void);
DBOptionsAttributes *GetExtrudedVolWriteOptions(void);


#endif
