// ************************************************************************* //
//  File: RemoveCellsPluginInfo.h
// ************************************************************************* //

#ifndef REMOVECELLS_PLUGIN_INFO_H
#define REMOVECELLS_PLUGIN_INFO_H
#include <OperatorPluginInfo.h>
#include <operator_plugin_exports.h>

class RemoveCellsAttributes;

// ****************************************************************************
//  Class: RemoveCellsPluginInfo
//
//  Purpose:
//    Five classes that provide all the information about an RemoveCells operator
//
//  Programmer: whitlocb -- generated by xml2info
//  Creation:   Fri Jan 6 18:13:39 PST 2006
//
//  Modifications:
//
// ****************************************************************************

class RemoveCellsGeneralPluginInfo : public virtual GeneralOperatorPluginInfo
{
  public:
    virtual char *GetName() const;
    virtual char *GetVersion() const;
    virtual char *GetID() const;
    virtual bool  EnabledByDefault() const;
};

class RemoveCellsCommonPluginInfo : public virtual CommonOperatorPluginInfo, public virtual RemoveCellsGeneralPluginInfo
{
  public:
    virtual AttributeSubject *AllocAttributes();
    virtual void CopyAttributes(AttributeSubject *to, AttributeSubject *from);
};

class RemoveCellsGUIPluginInfo : public virtual GUIOperatorPluginInfo, public virtual RemoveCellsCommonPluginInfo
{
  public:
    virtual const char *GetMenuName() const;
    virtual QvisPostableWindowObserver *CreatePluginWindow(int type,
        AttributeSubject *attr, QvisNotepadArea *notepad);
    virtual const char **XPMIconData() const;
};

class RemoveCellsViewerPluginInfo : public virtual ViewerOperatorPluginInfo, public virtual RemoveCellsCommonPluginInfo
{
  public:
    virtual AttributeSubject *GetClientAtts();
    virtual AttributeSubject *GetDefaultAtts();
    virtual void SetClientAtts(AttributeSubject *atts);
    virtual void GetClientAtts(AttributeSubject *atts);

    virtual void InitializeOperatorAtts(AttributeSubject *atts,
                                        const ViewerPlot *plot,
                                        const bool fromDefault);
    virtual const char **XPMIconData() const;

    static void InitializeGlobalObjects();
  private:
    static RemoveCellsAttributes *defaultAtts;
    static RemoveCellsAttributes *clientAtts;
};

class RemoveCellsEnginePluginInfo : public virtual EngineOperatorPluginInfo, public virtual RemoveCellsCommonPluginInfo
{
  public:
    virtual avtPluginFilter *AllocAvtPluginFilter();
};

class RemoveCellsScriptingPluginInfo : public virtual ScriptingOperatorPluginInfo, public virtual RemoveCellsCommonPluginInfo
{
  public:
    virtual void InitializePlugin(AttributeSubject *subj, void *data);
    virtual void *GetMethodTable(int *nMethods);
    virtual bool TypesMatch(void *pyobject);
    virtual char *GetLogString();
    virtual void SetDefaults(const AttributeSubject *atts);
};

#endif
